<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>details – Taskweft — Manuals</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5a10fc84a7bff526434d52200a729576.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-f36f388c175c695e587c9d92b6af4f92.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5a10fc84a7bff526434d52200a729576.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-285d64067b7bfd38b4f886e30e47acef.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ebf6027466d64ce25e353d53063d38f8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-285d64067b7bfd38b4f886e30e47acef.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Taskweft — Manuals</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-flight-levels" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Flight Levels</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-flight-levels">    
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-1-operations.html">
 <span class="dropdown-text">L1 · Operations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-2-coordination.html">
 <span class="dropdown-text">L2 · Coordination</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-3-strategy.html">
 <span class="dropdown-text">L3 · Strategy</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../pages/logbook.html"> 
<span class="menu-text">Logbook</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../pages/serials.html"> 
<span class="menu-text">Register</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#rfd-1134-details-running-loop-1-in-the-browser" id="toc-rfd-1134-details-running-loop-1-in-the-browser" class="nav-link active" data-scroll-target="#rfd-1134-details-running-loop-1-in-the-browser">RFD 1134 details: Running loop 1 in the browser</a>
  <ul class="collapse">
  <li><a href="#the-server" id="toc-the-server" class="nav-link" data-scroll-target="#the-server">The server</a></li>
  <li><a href="#the-browser" id="toc-the-browser" class="nav-link" data-scroll-target="#the-browser">The browser</a></li>
  <li><a href="#the-run" id="toc-the-run" class="nav-link" data-scroll-target="#the-run">The run</a></li>
  <li><a href="#the-defect-this-exposes" id="toc-the-defect-this-exposes" class="nav-link" data-scroll-target="#the-defect-this-exposes">The defect this exposes</a></li>
  <li><a href="#a-second-defect-found-by-reading" id="toc-a-second-defect-found-by-reading" class="nav-link" data-scroll-target="#a-second-defect-found-by-reading">A second defect, found by reading</a></li>
  <li><a href="#the-repair-and-the-second-run" id="toc-the-repair-and-the-second-run" class="nav-link" data-scroll-target="#the-repair-and-the-second-run">The repair, and the second run</a></li>
  <li><a href="#the-round-trip-re-measured" id="toc-the-round-trip-re-measured" class="nav-link" data-scroll-target="#the-round-trip-re-measured">The round trip, re-measured</a></li>
  <li><a href="#the-detector-and-a-retraction-of-the-paragraph-above" id="toc-the-detector-and-a-retraction-of-the-paragraph-above" class="nav-link" data-scroll-target="#the-detector-and-a-retraction-of-the-paragraph-above">The detector, and a retraction of the paragraph above</a></li>
  <li><a href="#the-1.56-px-figure-was-not-stale-and-this-retracts-that-call" id="toc-the-1.56-px-figure-was-not-stale-and-this-retracts-that-call" class="nav-link" data-scroll-target="#the-1.56-px-figure-was-not-stale-and-this-retracts-that-call">The 1.56 px figure was not stale, and this retracts that call</a></li>
  <li><a href="#a-wrist-is-not-a-hand" id="toc-a-wrist-is-not-a-hand" class="nav-link" data-scroll-target="#a-wrist-is-not-a-hand">A wrist is not a hand</a></li>
  <li><a href="#the-third-run-and-the-two-gaps-it-reached" id="toc-the-third-run-and-the-two-gaps-it-reached" class="nav-link" data-scroll-target="#the-third-run-and-the-two-gaps-it-reached">The third run, and the two gaps it reached</a></li>
  <li><a href="#the-document-completes-and-the-score-is-zero-for-a-nameable-reason" id="toc-the-document-completes-and-the-score-is-zero-for-a-nameable-reason" class="nav-link" data-scroll-target="#the-document-completes-and-the-score-is-zero-for-a-nameable-reason">The document completes, and the score is zero for a nameable reason</a></li>
  <li><a href="#the-render-found-the-defect-the-residual-hid" id="toc-the-render-found-the-defect-the-residual-hid" class="nav-link" data-scroll-target="#the-render-found-the-defect-the-residual-hid">The render found the defect the residual hid</a></li>
  <li><a href="#the-scorer-is-the-next-thing-that-needs-a-baseline" id="toc-the-scorer-is-the-next-thing-that-needs-a-baseline" class="nav-link" data-scroll-target="#the-scorer-is-the-next-thing-that-needs-a-baseline">The scorer is the next thing that needs a baseline</a></li>
  <li><a href="#the-bound-on-a-pose-has-two-forms-and-neither-is-wired-in" id="toc-the-bound-on-a-pose-has-two-forms-and-neither-is-wired-in" class="nav-link" data-scroll-target="#the-bound-on-a-pose-has-two-forms-and-neither-is-wired-in">The bound on a pose has two forms, and neither is wired in</a></li>
  <li><a href="#a-correction-the-frames-were-never-the-wrong-part" id="toc-a-correction-the-frames-were-never-the-wrong-part" class="nav-link" data-scroll-target="#a-correction-the-frames-were-never-the-wrong-part">A correction: the frames were never the wrong part</a></li>
  <li><a href="#the-two-fitted-subjects-were-deleted" id="toc-the-two-fitted-subjects-were-deleted" class="nav-link" data-scroll-target="#the-two-fitted-subjects-were-deleted">The two fitted subjects were deleted</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/rfd/1134-notebooks-tested-in-the-browser/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/rfd/1134-notebooks-tested-in-the-browser/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>





<section id="rfd-1134-details-running-loop-1-in-the-browser" class="level1">
<h1>RFD 1134 details: Running loop 1 in the browser</h1>
<p>The apparatus, the failure text, and the defects that the first run found.</p>
<section id="the-server" class="level2">
<h2 class="anchored" data-anchor-id="the-server">The server</h2>
<p>The command in the project README does not start the server on this desk. <code>mix run --no-halt</code> runs in the dev environment. Livebook’s endpoint is compiled there with code reloading on, and <code>phoenix_live_reload</code> is a dev-only dependency of Livebook that this project never fetches. The boot ends with this:</p>
<pre><code>ERROR!!! [Livebook] shutdown: failed to start child: LivebookWeb.Endpoint
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function
        Phoenix.LiveReloader.Socket.child_spec/1 is undefined</code></pre>
<p><code>MIX_ENV=prod mix run --no-halt -e 'IO.puts ServiceLivebook.start()'</code> serves. It printed <code>http://localhost:8080/?token=pzodiirf3iumgvvni2fculpsmf2mx4kb</code>, and <code>/public/health</code> returned 200.</p>
</section>
<section id="the-browser" class="level2">
<h2 class="anchored" data-anchor-id="the-browser">The browser</h2>
<p>Playwright 1.62.1, Chromium 151, headed, on the desk display. The launch script holds the window open and opens a debug port:</p>
<pre><code>chromium.launch({headless: false,
                 args: ['--remote-debugging-port=9222']})</code></pre>
<p>Each later step calls <code>chromium.connectOverCDP('http://localhost:9222')</code> and takes the open page. The window stays under the person’s hand.</p>
<p>The open route needs an absolute path. A path written as a string literal loses its backslashes to escape sequences, and <code>7-service</code> becomes a bell character. Livebook then redirects to the open dialog and reports nothing. Join the parts instead:</p>
<pre><code>['C:', 'weftspun-keypoint', '7-service', 'service-livebook',
 'notebooks', '1-keypoints-to-anny.livemd'].join(sep)</code></pre>
</section>
<section id="the-run" class="level2">
<h2 class="anchored" data-anchor-id="the-run">The run</h2>
<p>Loop 1 holds 20 cells, 11 of them code. Escape, then <code>e</code>, then <code>a</code> ran them. The states after the run:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>cell</th>
<th>content</th>
<th>state</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><code>Mix.install</code></td>
<td>Evaluated, 1.0 s</td>
</tr>
<tr class="even">
<td>1</td>
<td><code>pyproject.toml</code></td>
<td>Evaluated, CPython 3.11</td>
</tr>
<tr class="odd">
<td>4</td>
<td>paths and <code>weft_loop</code> import</td>
<td>Evaluated</td>
</tr>
<tr class="even">
<td>5</td>
<td><code>PHOTO</code>, <code>WORK</code></td>
<td>Evaluated</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>detect</code></td>
<td>Evaluated</td>
</tr>
<tr class="even">
<td>9</td>
<td><code>propose</code>, <code>score</code></td>
<td>Evaluated</td>
</tr>
<tr class="odd">
<td>12</td>
<td>the fit</td>
<td>Evaluated, traceback</td>
</tr>
<tr class="even">
<td>14</td>
<td><code>residuals_by_region</code></td>
<td>never ran</td>
</tr>
<tr class="odd">
<td>16</td>
<td><code>report</code></td>
<td>never ran</td>
</tr>
<tr class="even">
<td>18</td>
<td><code>run(propose, score, ...)</code></td>
<td>never ran</td>
</tr>
<tr class="odd">
<td>19</td>
<td>provenance</td>
<td>never ran</td>
</tr>
</tbody>
</table>
<p>Cell 12 reported this:</p>
<pre><code>Traceback (most recent call last):
  File "&lt;string&gt;", line 3, in &lt;module&gt;
  File "priv/python/loop1_fit.py", line 38, in &lt;module&gt;
    import torch
ModuleNotFoundError: No module named 'torch'</code></pre>
</section>
<section id="the-defect-this-exposes" class="level2">
<h2 class="anchored" data-anchor-id="the-defect-this-exposes">The defect this exposes</h2>
<p>The notebook states that every cell which touches the card is a subprocess into a pixi environment. Cell 12 is not. It imports <code>loop1_fit</code> into the notebook’s own Python process, and <code>loop1_fit</code> imports torch at module level. The setup cell declares pillow, numpy and matplotlib. So the fit cannot run in the notebook as written, and the reason is not the missing detector.</p>
<p>Two repairs are open, and this document records both rather than picking one.</p>
<ul>
<li>Run the fit as a subprocess into the <code>anny</code> pixi environment, which holds torch. This keeps the rule the notebook already states, and it moves the fit result across a file.</li>
<li>Declare torch and roma in the setup <code>pyproject.toml</code>. This keeps the fit in process, and it makes the notebook boot download a large wheel set that the pixi environments already hold.</li>
</ul>
</section>
<section id="a-second-defect-found-by-reading" class="level2">
<h2 class="anchored" data-anchor-id="a-second-defect-found-by-reading">A second defect, found by reading</h2>
<p>The prose in loop 1 reports a round trip median of 1.19 px on a 591 px stature, which is 0.202% of stature. The provenance cell in the same notebook records 1.56 px and 0.263%. One of the two is stale. The run above could not settle it, because the cell that would recompute it never ran.</p>
</section>
<section id="the-repair-and-the-second-run" class="level2">
<h2 class="anchored" data-anchor-id="the-repair-and-the-second-run">The repair, and the second run</h2>
<p>The repair chosen is the pythonx one. The setup <code>pyproject.toml</code> cell now declares <code>torch&gt;=2.6</code>, <code>anny</code> and <code>roma</code> beside the three packages it already held. CLAUDE.md blocklists <code>uv</code> for project environments and exempts an embedded interpreter that pins its dependencies in source. This cell is that exemption. The pins travel with the notebook, and a reader rebuilds the environment from the file.</p>
<p>The server was restarted so the session read the new file. Livebook holds the notebook in memory and shows no notice when the file changes on disk.</p>
<p>The second run reached further. <code>build_model</code> and <code>bone_names</code> ran in the notebook’s own interpreter, and the fit cell stopped 22.9 s later at line 7 with the refusal the code already carried:</p>
<pre><code>weft_loop.PreconditionFailed: no environment here carries rfdetr</code></pre>
<p>So the torch defect is closed and the detector gap is now the first blocker, which is the state the notebook prose already describes. Cells 14, 16, 18 and 19 stayed queued a second time. They are NOT_RUN, and no number is reported for them.</p>
</section>
<section id="the-round-trip-re-measured" class="level2">
<h2 class="anchored" data-anchor-id="the-round-trip-re-measured">The round trip, re-measured</h2>
<p><code>test_loop1_fit.py</code> ran in the <code>anny</code> pixi environment on 2026-08-25: median 1.193 px on a 591.1 px stature, 0.202% of stature, 3.44 mm on a 1.7 m body, about two stacked pennies. It took 2.3 s on CPU at 60 LBFGS iterations over 104 points. Shuffled targets reach 233.039 px. All five referee regions fill: 31 body, 30 feet, 20 per hand and 3 face.</p>
<p>The prose figure was right and the provenance figure was stale. The notebook now carries 1.193 px in both places, and the retracted 1.56 px stays beside it in the provenance record.</p>
</section>
<section id="the-detector-and-a-retraction-of-the-paragraph-above" class="level2">
<h2 class="anchored" data-anchor-id="the-detector-and-a-retraction-of-the-paragraph-above">The detector, and a retraction of the paragraph above</h2>
<p>Installing <code>rfdetr</code> in the setup cell closed the import error and showed what it had been hiding. <code>RFDETRKeypointPreviewConfig</code> in rfdetr 1.9.4 carries <code>num_keypoints_per_class = [17]</code>. The published preview model is COCO-17. No fullbody checkpoint ships, so the notebook’s own claim that the detector is the fullbody one is retracted, in the notebook and in <code>loop1_fit.py</code>.</p>
<p>A 17-row target cannot use the 104 bone names, and <code>fit_2d</code> refuses that pairing by design. It goes through the 23-point regressor instead. <code>coco_regressor</code> returns the regressor and its first 17 labels, and it checks those labels against COCO’s order rather than trusting them. A reordered <code>coco.pth</code> would otherwise fit each point to the wrong joint and still report a small residual.</p>
</section>
<section id="the-1.56-px-figure-was-not-stale-and-this-retracts-that-call" class="level2">
<h2 class="anchored" data-anchor-id="the-1.56-px-figure-was-not-stale-and-this-retracts-that-call">The 1.56 px figure was not stale, and this retracts that call</h2>
<p>The section above says the provenance cell held a stale number. That was wrong. The two figures measure two vocabularies:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>vocabulary</th>
<th>median</th>
<th>of stature</th>
<th>on a 1.7 m body</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ANNY bone joints, 104</td>
<td>1.193 px</td>
<td>0.202%</td>
<td>3.44 mm, two pennies</td>
</tr>
<tr class="even">
<td>COCO-17, regressor</td>
<td>1.555 px</td>
<td>0.263%</td>
<td>4.48 mm, one pencil</td>
</tr>
</tbody>
</table>
<p>The prose recorded the first and the provenance cell recorded the second. <code>test_loop1_fit.py</code> now runs both round trips, so neither figure can be mistaken for the other again. Shuffled targets reach 233.039 px and 111.844 px. The notebook carries both, each named by its vocabulary.</p>
</section>
<section id="a-wrist-is-not-a-hand" class="level2">
<h2 class="anchored" data-anchor-id="a-wrist-is-not-a-hand">A wrist is not a hand</h2>
<p>The 17-point control found a defect in <code>region_of</code>. <code>HAND_MARKERS</code> held <code>wrist</code>, so a COCO-17 target filled <code>left_hand</code> and <code>right_hand</code> with one point each. The referee would then judge a hand from a single boundary joint and report a region rather than NOT_RUN. That is the pass a missing region exists to prevent.</p>
<p><code>wrist</code> is out of <code>HAND_MARKERS</code>. The fullbody vocabulary loses nothing, because it carries 19 further points per hand. The counts move from 31 body and 20 per hand to 33 body and 19 per hand. A 17-point target now fills body, face and feet, and both hands stay NOT_RUN.</p>
<p>The control that found it is a negative control and it stays: the test fails if either hand region fills from 17 points.</p>
</section>
<section id="the-third-run-and-the-two-gaps-it-reached" class="level2">
<h2 class="anchored" data-anchor-id="the-third-run-and-the-two-gaps-it-reached">The third run, and the two gaps it reached</h2>
<p><code>rfdetr</code> in the setup cell reaches the checkpoint, and the notebook then found a data defect before a code one. At threshold 0.4 the detector returns nothing for <code>hv_0.png</code>, which was the notebook’s default photo. Measured over the three renders at 1024 by 1024: <code>hv_0</code> gives 0 detections at 0.4 and 2 at 0.2, while <code>hv_1</code> and <code>hv_2</code> give one person at 0.999 and 1.000. The default is now <code>hv_1.png</code>.</p>
<p>The fit then ran in the browser and printed a median of 0.34 px on a 508 px stature, 0.07%, over 17 of 104 points. That number is not evidence of a correct pose. Seventeen points constrain 104 bones loosely, so the solve is underdetermined and a small reprojection error is what an underdetermined fit gives. The referee answers NOT_RUN, which is the honest verdict.</p>
<p>Cells 12, 14 and 16 evaluated. Cell 18 stopped, and it names the next gap: <code>propose</code> shells into the <code>anny</code> pixi environment to run <code>render_view.py</code>, and that environment reports</p>
<pre><code>ModuleNotFoundError: No module named 'drjit'</code></pre>
<p><code>mitsuba</code> is a dependency of the corpus repository’s default feature, and the <code>anny</code> environment sets <code>no-default-feature = true</code>, so the renderer is not in the environment the loop calls. Behind that sits a second gap already recorded above: <code>propose</code> reads <code>fit_{i}.npz</code> and nothing writes one. Neither is repaired here, because closing them is a design step rather than a test step.</p>
</section>
<section id="the-document-completes-and-the-score-is-zero-for-a-nameable-reason" class="level2">
<h2 class="anchored" data-anchor-id="the-document-completes-and-the-score-is-zero-for-a-nameable-reason">The document completes, and the score is zero for a nameable reason</h2>
<p>Every cell evaluates. The referee reports <code>NOT_RUN</code>, which is correct on 17 points. The three rounds report this:</p>
<pre><code>baseline 0.000 on hv_1.png
  round=1  iters=80   score=0.0  delta=0.0  35.2 s  scorer 28.0 s  6.74 GiB
  round=2  iters=120  score=0.0  delta=0.0  42.7 s  scorer 33.5 s  6.74 GiB
  round=3  iters=160  score=0.0  delta=0.0  40.4 s  scorer 25.9 s  6.74 GiB</code></pre>
<p>Zero three times is not a converged loop. It is the loop measuring the wrong thing, and the camera vocabulary says which thing in one line.</p>
<p><code>propose</code> returns <code>rendered[0]</code>, and view 0 of the sequence is azimuth 0 with elevation -90: a camera directly underneath the body. In fal’s vocabulary that camera has no phrase at all, because the elevation bands stop at -45. The scorer’s own words for it were “the edited image shows the person lying down”.</p>
<p>So each round handed EditScore a view from beneath a standing figure and asked whether it matched an upright photograph. The answer is 0.0, and it is the right answer to the question that was asked.</p>
<p>Two things follow, and neither is repaired here.</p>
<ul>
<li>The scored view must be the one the fit claims. The fit solves a weak-perspective camera facing the subject, so the comparison belongs at that camera, not at whichever index the sequence happens to start on.</li>
<li>Rendering the whole sequence stays. The rule is about what is rendered, never about which render is scored, and the two were conflated.</li>
</ul>
<p><code>describe_camera</code> in <code>weft_loop.py</code> names every view of the sequence, and five of the eight have no phrase because they sit between the vocabulary’s elevation steps. That is a fact about <code>sphere_hammersley_sequence</code> rather than a fault in either.</p>
</section>
<section id="the-render-found-the-defect-the-residual-hid" class="level2">
<h2 class="anchored" data-anchor-id="the-render-found-the-defect-the-residual-hid">The render found the defect the residual hid</h2>
<p>Rendering the fitted mesh through 96 poses showed a body sprawled in every frame. The cause is one interface, and it retracts every percent-of-stature figure above.</p>
<p>ANNY’s rest mesh measures X 1.046, Y 0.434, Z 1.660, so the rig is Z-up, and <code>render_view</code> agrees with <code>up=[0,0,1]</code>. <code>fit_2d</code> projected <code>points3d[:, :2]</code>, which feeds the body’s DEPTH axis to image-vertical. Against an upright target the solver’s only way to match was to rotate the whole figure about ninety degrees. <code>stature</code> read component 1 for the same reason, so residuals were normalised by a depth of 0.434 where a height of 1.660 belonged.</p>
<p>The known-answer round trip could not catch it. It built its targets through the same two axes, so it was wrong and self-consistent together, and reported 1.19 px while the pose it recovered was lying down. That is the sampled-check failure in a different costume: a control that shares an assumption with the thing it checks tests everything except that assumption.</p>
<p><code>image_axes</code> now measures the axes off the rest pose and raises when the longest extent is not clearly longest, and <code>to_image</code> negates the up axis because image rows count downward and a positive scale cannot absorb a flip.</p>
<p>Re-measured, and these supersede the figures above:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>vocabulary</th>
<th>median</th>
<th>of stature</th>
<th>on a 1.7 m body</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ANNY bone joints, 104</td>
<td>3.131 px</td>
<td>0.212%</td>
<td>3.60 mm, 2.4 pennies</td>
</tr>
<tr class="even">
<td>COCO-17, regressor</td>
<td>0.947 px</td>
<td>0.064%</td>
<td>1.09 mm, one penny</td>
</tr>
</tbody>
</table>
<p>The fitted mesh now measures X 0.526, Y 0.813, Z 1.544 against a rest height of 1.660. It stands.</p>
</section>
<section id="the-scorer-is-the-next-thing-that-needs-a-baseline" class="level2">
<h2 class="anchored" data-anchor-id="the-scorer-is-the-next-thing-that-needs-a-baseline">The scorer is the next thing that needs a baseline</h2>
<p>With the axes fixed and the comparison view chosen, the three rounds report:</p>
<pre><code>round 1  iters 80   score 2.530  view 16, 12.9 deg from a front view
round 2  iters 120  score 0.000  view 16, 12.9 deg from a front view
round 3  iters 160  score 0.000  view 16, 12.9 deg from a front view</code></pre>
<p>Every round scored the same view of nearly the same pose, and the score moved by 2.53 and back. That is not the extra LBFGS iterations. EditScore runs at NF4 and samples, so the loop is currently measuring the scorer’s variance.</p>
<p>Nothing here knows how large that variance is, because it has never been measured: score one image k times and report the spread. Until that number exists, a round-to-round delta from this loop is not a measurement, and CLAUDE.md’s rule is the one that applies – a number without a baseline is not a measurement, and the baseline for a noisy instrument is its own noise.</p>
</section>
<section id="the-bound-on-a-pose-has-two-forms-and-neither-is-wired-in" class="level2">
<h2 class="anchored" data-anchor-id="the-bound-on-a-pose-has-two-forms-and-neither-is-wired-in">The bound on a pose has two forms, and neither is wired in</h2>
<p>The fitted pose that opened this work folds bones through each other at 0.022% of stature, so the residual does not see it and neither does the referee. What would see it exists in this workspace, in two halves.</p>
<p><code>2-contract/swing-twist-kusudama</code> authors the limits. It is a Lean 4 and Plausible simulation of <code>SwingTwistIK3D</code> with <code>JointLimitationKusudama3D</code>, holding the live humanoid rig as five chains, seventeen kusudama joints and sixty-five cones, checked against Godot’s own output. A cone is a thing a person can see and edit, which is why the limits live there.</p>
<p><code>3-interactor/physics</code> enforces them. It is MuJoCo with MJCF scenes and the <code>mj_physics</code> wiring. Converted into that, a limit stops being an overlay on a solver and becomes physical: the simulation refuses the pose rather than a person noticing it in a render.</p>
<p>Two things are open, and both are numbers rather than opinions.</p>
<ul>
<li><p><strong>The conversion is lossy, and the loss is measurable.</strong> Sixty-five cones across seventeen joints is more expressive than a MuJoCo ball joint’s single cone range, so one constraint per joint cannot carry it. EditScore judges it: render one pose under the authored limits and under the converted ones, from the same camera, and ask whether they are the same pose. That is the loop this project already runs, pointed at the conversion instead of at a fit.</p>
<p>It cannot be read until EditScore has a noise floor. Three rounds of this notebook scored the same view of nearly the same pose and returned 2.53, 0.0 and 0.0, so a difference smaller than that swing is the scorer and not the conversion. Score one image k times and report the spread first.</p>
<p>Pair it with the physical quantity rather than replacing one with the other: millimetres of surface deviation between the two posed meshes, and degrees at each joint. EditScore says whether a viewer would call it the same pose. The millimetres say by how much it is not.</p></li>
<li><p><strong>Neither half is wired into <code>loop1_fit</code>.</strong> The solver runs unconstrained today, which is why the rest pose is the corpus subject.</p></li>
</ul>
<p>The range-of-motion dataset in the kusudama project is AddBiomechanics ROM. CLAUDE.md blocklists AddBiomechanics <code>.b3d</code> as an IDENTITY source, for a narrow and inequitable population, and bounding a joint angle is not that use. Worth stating so the row is not read as wider than it is.</p>
</section>
<section id="a-correction-the-frames-were-never-the-wrong-part" class="level2">
<h2 class="anchored" data-anchor-id="a-correction-the-frames-were-never-the-wrong-part">A correction: the frames were never the wrong part</h2>
<p>The section above calls the fitted pose broken and says so plainly. It is worth separating what that does and does not condemn, because the first version of this record blurred them.</p>
<p>The renders are ground truth. ANNY was posed, the renderer put the vertices where the rig said, and every joint label is exact whatever the pose looks like. For training a decoder or an autoencoder, a folded limb is geometry the reconstruction has to handle, not a defect in the data, and that is the reason to render a constructed corpus at all: the label is true by construction rather than annotated.</p>
<p>What was wrong was narrower, and it was a claim rather than a frame.</p>
<ul>
<li><strong>The correspondence.</strong> “This render is that photograph’s pose” is false when the solve folded a limb to reach the pixels, and that is precisely the claim the loop scores.</li>
<li><strong>The prior.</strong> A corpus whose poses a body cannot hold teaches a distribution the world does not have, which matters to anything learning what a pose usually is and not at all to a reconstruction.</li>
</ul>
<p>So the rest pose is the right subject for a clip that explains the pipeline, and a rig-representable pose needs no defence when the corpus is for a decoder. Both were true at once and the earlier text implied only the first.</p>
</section>
<section id="the-two-fitted-subjects-were-deleted" class="level2">
<h2 class="anchored" data-anchor-id="the-two-fitted-subjects-were-deleted">The two fitted subjects were deleted</h2>
<p><code>grid96-anny</code> and <code>grid96-anny-hv2</code> are gone, deleted on 2026-08-25 as invalid poses. Between them they held 397 files and 115 MB: two posed meshes, 192 rendered frames with sidecars, two citations and one clip.</p>
<p>The measurements they produced stay in this record because they are what the runs measured, and the reader should know the sets behind them no longer exist:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>subject</th>
<th>median</th>
<th>of stature</th>
<th>chest facing</th>
<th>why it went</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>hv_1 fit</td>
<td>0.17 px</td>
<td>0.033%</td>
<td>345.9 deg</td>
<td><code>.L</code> joints at +0.009, limbs cross</td>
</tr>
<tr class="even">
<td>hv_2 fit</td>
<td>0.14 px</td>
<td>0.022%</td>
<td>72.7 deg</td>
<td>same class of fit</td>
</tr>
</tbody>
</table>
<p>Both are what an unconstrained 17-point solve produces, and both report a residual small enough to look converged. The rest pose is the only corpus subject until a joint bound exists, which is the state RFD 1137’s skill already describes and RFD 1138’s question has to be answered before it changes.</p>
<p>Nothing in the argument depends on the files. The conventions check still refuses that class of rig, and <code>check_conventions.py</code> carries the hv_1 numbers as the reason the feet are not the forward witness.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/weftspun\.github\.io\/request-for-discussion");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Serials are OID arcs under the 66606 PEN and are never reused.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/rfd/1134-notebooks-tested-in-the-browser/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/rfd/1134-notebooks-tested-in-the-browser/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/weftspun/request-for-discussion">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>