<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>details – Taskweft — Manuals</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5a10fc84a7bff526434d52200a729576.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-f36f388c175c695e587c9d92b6af4f92.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5a10fc84a7bff526434d52200a729576.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-285d64067b7bfd38b4f886e30e47acef.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ebf6027466d64ce25e353d53063d38f8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-285d64067b7bfd38b4f886e30e47acef.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Taskweft — Manuals</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-flight-levels" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Flight Levels</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-flight-levels">    
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-1-operations.html">
 <span class="dropdown-text">L1 · Operations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-2-coordination.html">
 <span class="dropdown-text">L2 · Coordination</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-3-strategy.html">
 <span class="dropdown-text">L3 · Strategy</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../pages/logbook.html"> 
<span class="menu-text">Logbook</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../pages/serials.html"> 
<span class="menu-text">Register</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#rfd-2161-details-cleanroom-vn-avatar-on-the-maskscore-stack" id="toc-rfd-2161-details-cleanroom-vn-avatar-on-the-maskscore-stack" class="nav-link active" data-scroll-target="#rfd-2161-details-cleanroom-vn-avatar-on-the-maskscore-stack">RFD 2161 details: cleanroom VN-avatar on the MaskScore stack</a>
  <ul class="collapse">
  <li><a href="#retractions-from-the-2026-09-01-compute-ladder" id="toc-retractions-from-the-2026-09-01-compute-ladder" class="nav-link" data-scroll-target="#retractions-from-the-2026-09-01-compute-ladder">Retractions from the 2026-09-01 compute ladder</a></li>
  <li><a href="#the-stack-that-landed" id="toc-the-stack-that-landed" class="nav-link" data-scroll-target="#the-stack-that-landed">The stack that landed</a></li>
  <li><a href="#compute-pivot-mac-mini---windows-11-rtx-3090" id="toc-compute-pivot-mac-mini---windows-11-rtx-3090" class="nav-link" data-scroll-target="#compute-pivot-mac-mini---windows-11-rtx-3090">Compute pivot: Mac mini -&gt; Windows 11 + RTX 3090</a></li>
  <li><a href="#original-substitution-table-retained-for-the-record" id="toc-original-substitution-table-retained-for-the-record" class="nav-link" data-scroll-target="#original-substitution-table-retained-for-the-record">Original substitution table (retained for the record)</a></li>
  <li><a href="#true-qaft-only-mirror-candidates-2026-09-01-refined" id="toc-true-qaft-only-mirror-candidates-2026-09-01-refined" class="nav-link" data-scroll-target="#true-qaft-only-mirror-candidates-2026-09-01-refined">True-QAFT-only mirror candidates (2026-09-01, refined)</a></li>
  <li><a href="#ptq-only-variants-dropped-not-true-qaft" id="toc-ptq-only-variants-dropped-not-true-qaft" class="nav-link" data-scroll-target="#ptq-only-variants-dropped-not-true-qaft">PTQ-only variants (dropped, not true-QAFT)</a></li>
  <li><a href="#maskscore-stack-models-rfd-1173" id="toc-maskscore-stack-models-rfd-1173" class="nav-link" data-scroll-target="#maskscore-stack-models-rfd-1173">MaskScore-stack models (RFD 1173)</a></li>
  <li><a href="#what-the-spec-side-read-its-only-inputs" id="toc-what-the-spec-side-read-its-only-inputs" class="nav-link" data-scroll-target="#what-the-spec-side-read-its-only-inputs">What the spec side read (its only inputs)</a></li>
  <li><a href="#boot-order" id="toc-boot-order" class="nav-link" data-scroll-target="#boot-order">Boot order</a></li>
  <li><a href="#language-boundaries" id="toc-language-boundaries" class="nav-link" data-scroll-target="#language-boundaries">Language boundaries</a></li>
  <li><a href="#frame-protocol-on-the-websocket" id="toc-frame-protocol-on-the-websocket" class="nav-link" data-scroll-target="#frame-protocol-on-the-websocket">Frame protocol on the WebSocket</a></li>
  <li><a href="#speakingfaces---vn-avatar-personas-construction" id="toc-speakingfaces---vn-avatar-personas-construction" class="nav-link" data-scroll-target="#speakingfaces---vn-avatar-personas-construction">SpeakingFaces -&gt; vn-avatar-personas construction</a></li>
  <li><a href="#trace-row-shape-mirrors-maskscore-8-stub-schema" id="toc-trace-row-shape-mirrors-maskscore-8-stub-schema" class="nav-link" data-scroll-target="#trace-row-shape-mirrors-maskscore-8-stub-schema">Trace row shape (mirrors MaskScore §8-stub schema)</a></li>
  <li><a href="#bootstrap-on-the-rented-vast-machine-3090-24-gib" id="toc-bootstrap-on-the-rented-vast-machine-3090-24-gib" class="nav-link" data-scroll-target="#bootstrap-on-the-rented-vast-machine-3090-24-gib">Bootstrap on the rented Vast machine (3090, 24 GiB)</a></li>
  <li><a href="#mvp-smoke-in-one-sentence" id="toc-mvp-smoke-in-one-sentence" class="nav-link" data-scroll-target="#mvp-smoke-in-one-sentence">MVP smoke, in one sentence</a></li>
  <li><a href="#what-is-not-here-deferred-to-follow-on-rfds" id="toc-what-is-not-here-deferred-to-follow-on-rfds" class="nav-link" data-scroll-target="#what-is-not-here-deferred-to-follow-on-rfds">What is not here (deferred to follow-on RFDs)</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/rfd/2161-vn-avatar-cleanroom-on-maskscore/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/rfd/2161-vn-avatar-cleanroom-on-maskscore/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>





<section id="rfd-2161-details-cleanroom-vn-avatar-on-the-maskscore-stack" class="level1">
<h1>RFD 2161 details: cleanroom VN-avatar on the MaskScore stack</h1>
<section id="retractions-from-the-2026-09-01-compute-ladder" class="level2">
<h2 class="anchored" data-anchor-id="retractions-from-the-2026-09-01-compute-ladder">Retractions from the 2026-09-01 compute ladder</h2>
<p>The session that filed this RFD climbed down five rungs of a compute ladder. Each pivot’s reason is recorded so a future reader does not reopen the same bets.</p>
<ol type="1">
<li><strong>“Rent an RTX 3090 on Vast”</strong>; two cheapest-tier hosts failed to spin up (bad GPU error, image never pulled). Spent $0.003 total before pivoting. The Vast market-snapshot dataset survives at <code>6-datasource/vast-market-snapshots/</code> (three ETNF Parquet snapshots with 40% churn per ~12 min at the hot $0.18-0.22 band; Wilson 95%-lower on pooled 3-snapshot evidence).</li>
<li><strong>“Qwen3-Omni-30B does thinker + talker + OmniScore reward”</strong> ; RETRACTED. The team behind Qwen3-Omni was disbanded (operator report), and no true-QAFT 4-bit checkpoint exists upstream for it or for Wan-VACE 14B, Pixal3D, VoxHammer, MoGe-3. Full QAFT training sized at ~$7-15K compute we do not have.</li>
<li><strong>“Gemma-4-31B-it-qat as the visual-LLM replacement”</strong>; RETRACTED. Google publishes it (apache-2.0, image-text-to-text), but 62.6 GB fp16 exceeds the shipping budget once compute constraints landed. The mirror plan for <code>chibifire/gemma-4-31B-it-qat-*</code> never fired.</li>
<li><strong>“Gemma-4-E4B-it-qat + train EditScore LoRA ourselves”</strong> ; RETRACTED at the smoke stage. EditScore already published its own LoRA over Qwen3-VL-4B (<code>EditScore/EditScore-Qwen3-VL-4B-Instruct</code>, 270 MB, apache-2.0 inheriting from base). Training a duplicate would burn compute we don’t have to reproduce upstream work.</li>
<li><strong>“Vision encoder split onto Hailo NPU via QFT”</strong>; PARKED. No Linux x86_64 host to run the proprietary DFC wheel, no Hailo hardware to deploy to. Scaffold survives at <code>3-interactor/editscore-lora-qwen3vl-4b/scripts/gate_vision_encoder.py</code> with a real ONNX export the DFC-side gate can consume when hardware arrives.</li>
</ol>
</section>
<section id="the-stack-that-landed" class="level2">
<h2 class="anchored" data-anchor-id="the-stack-that-landed">The stack that landed</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>role</th>
<th>model</th>
<th>licence</th>
<th>footprint on Mac mini M2 Pro 32 GB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Visual LLM + reward</td>
<td><code>mlx-community/Qwen3-VL-4B-Instruct-4bit</code> + <code>EditScore/EditScore-Qwen3-VL-4B-Instruct</code> LoRA</td>
<td>apache-2.0</td>
<td><strong>3.1 GB base + 270 MB adapter, ~0.9 s load, ~1.9 s first token</strong></td>
</tr>
<tr class="even">
<td>TTS voice-clone</td>
<td><code>ResembleAI/chatterbox</code></td>
<td>mit</td>
<td>~500 MB, MPS or CPU</td>
</tr>
<tr class="odd">
<td>STT</td>
<td><code>whisper-small</code> or <code>distil-whisper</code> via MLX</td>
<td>mit</td>
<td>~500 MB</td>
</tr>
<tr class="even">
<td>VAD</td>
<td><code>silero-vad</code></td>
<td>mit</td>
<td>tiny</td>
</tr>
<tr class="odd">
<td>Viseme (MFCC -&gt; SOMA)</td>
<td>cleanroom small classifier</td>
<td>ours</td>
<td>negligible</td>
</tr>
<tr class="even">
<td>Body</td>
<td>ANNY + SOMA rig</td>
<td>ours</td>
<td>fits</td>
</tr>
<tr class="odd">
<td>Renderer</td>
<td>Godot 4.7 via <code>lib_godot_connector</code></td>
<td>mit</td>
<td>fits</td>
</tr>
<tr class="even">
<td>Locations</td>
<td><code>6-datasource/{kenney,thebasemesh,quaternius}-stage</code></td>
<td>cc-* clean</td>
<td>assets on disk</td>
</tr>
</tbody>
</table>
<p><strong>One real inference proved on Mac mini M2 Pro 32 GB (2026-09-01):</strong> <code>scripts/smoke_editscore_mlx.py</code> in <code>3-interactor/editscore-lora-qwen3vl-4b/</code> loaded the MLX 4-bit Qwen3-VL-4B in 0.9 s and generated a one-token reward response in 1.9 s from a dummy 224x224 image + edit-instruction prompt. Wiring holds; real numbers arrive with real (image, edit) pairs.</p>
</section>
<section id="compute-pivot-mac-mini---windows-11-rtx-3090" class="level2">
<h2 class="anchored" data-anchor-id="compute-pivot-mac-mini---windows-11-rtx-3090">Compute pivot: Mac mini -&gt; Windows 11 + RTX 3090</h2>
<p>The operator is moving to Windows 11 with an RTX 3090 (24 GB). That changes what becomes viable, in dependency order:</p>
<ol type="1">
<li><strong>QAFT-LoRA training on Qwen3-VL-4B against <code>EditScore/EditScore-Reward-Data</code> (97,300 rows, 161.8 GB, apache-2.0)</strong> returns to the table. The <code>3-interactor/editscore-lora-qwen3vl-4b/scripts/smoke.py</code> scaffold targets this exactly; needs <code>bitsandbytes</code> (already linux-64 target-scoped in <code>pixi.toml</code>; add <code>win-64</code> when the Windows path is real). Model VRAM footprint: Qwen3-VL-4B fp16 ~8.9 GB + optimizer state + gradients fits 24 GB comfortably at LoRA rank 32.</li>
<li><strong>Larger reward candidates</strong> (<code>EditScore/EditScore-Qwen3-VL-8B-Instruct</code>, <code>EditScore/EditScore-7B</code>, <code>EditScore/EditScore-32B</code>) become tractable at inference on the 3090. The 4B stays as the Mac-mini reference.</li>
<li><strong>Wan-VACE 14B NF4</strong> (~8.7 GB) fits alongside the reward model on the 3090 with swap. Reopens the image-generation slot RFD 1173 originally sized for.</li>
<li><strong>Hailo track</strong> stays parked; 3090 does not change Linux/DFC gap.</li>
</ol>
</section>
<section id="original-substitution-table-retained-for-the-record" class="level2">
<h2 class="anchored" data-anchor-id="original-substitution-table-retained-for-the-record">Original substitution table (retained for the record)</h2>
<p>The target space’s <code>README.md</code> (fetched cleanroom, README only) names <code>gemma-4-31B-it on Cerebras</code> as its assistant model. The final substitution collapses onto EditScore’s own release; the intermediate Gemma-4 mapping is retained here so the retraction trail is legible.</p>
</section>
<section id="true-qaft-only-mirror-candidates-2026-09-01-refined" class="level2">
<h2 class="anchored" data-anchor-id="true-qaft-only-mirror-candidates-2026-09-01-refined">True-QAFT-only mirror candidates (2026-09-01, refined)</h2>
<p>The target space’s README (fetched cleanroom, README only) names <code>gemma-4-31B-it on Cerebras</code> as the assistant model; Google’s own release. Google publishes true-QAFT (quantization-aware training) variants for the entire Gemma 4 lineup, including the target’s exact size. Community forks named “-qat” are excluded because their true- QAT provenance is not verifiable without vetting each individually.</p>
<p><strong>Vendor-QAFT candidates from <code>google/</code> (all Gemma Terms of Use):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 15%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>candidate</th>
<th>format</th>
<th>note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>google/gemma-4-31B-it-qat-w4a16-ct</code></td>
<td>Compressed-Tensors W4A16</td>
<td>target’s exact model; not GGUF, no blocklist question</td>
</tr>
<tr class="even">
<td><code>google/gemma-4-31B-it-qat-q4_0-gguf</code></td>
<td>GGUF Q4_0</td>
<td>same model, GGUF (vendor-runtime exemption via llama.cpp)</td>
</tr>
<tr class="odd">
<td><code>google/gemma-4-31B-it-qat-q4_0-unquantized</code></td>
<td>fp16 (QAT-trained)</td>
<td>for further fine-tuning on top of QAT weights</td>
</tr>
<tr class="even">
<td><code>google/gemma-4-26B-A4B-it-qat-q4_0-gguf</code></td>
<td>GGUF</td>
<td>26B MoE (4B active); same shape as Qwen3-Omni</td>
</tr>
<tr class="odd">
<td><code>google/gemma-4-12B-it-qat-w4a16-ct</code></td>
<td>CT W4A16</td>
<td>matches workspace’s <code>gemma4-composer</code> size</td>
</tr>
<tr class="even">
<td><code>google/gemma-4-E4B-it-qat-w4a16-ct</code></td>
<td>CT W4A16</td>
<td>effective 4B</td>
</tr>
<tr class="odd">
<td><code>google/gemma-4-E2B-it-qat-w4a16-ct</code></td>
<td>CT W4A16</td>
<td>effective 2B</td>
</tr>
</tbody>
</table>
</section>
<section id="ptq-only-variants-dropped-not-true-qaft" class="level2">
<h2 class="anchored" data-anchor-id="ptq-only-variants-dropped-not-true-qaft">PTQ-only variants (dropped, not true-QAFT)</h2>
<p>All other 4-bit variants surveyed for these families use post-training quantization, not QAT: <code>Intel/...int4-AutoRound</code>, every AWQ (including <code>Sabomako/...heretic-AWQ-4bit</code>; the licence-less community fork noted in an earlier pass), every GPTQ, every bitsandbytes NF4. Recorded here so a future session does not re-derive their presence and mistake them for QAT-refined weights.</p>
</section>
<section id="maskscore-stack-models-rfd-1173" class="level2">
<h2 class="anchored" data-anchor-id="maskscore-stack-models-rfd-1173">MaskScore-stack models (RFD 1173)</h2>
<p>Zero true-QAFT 4-bit checkpoints on Hub as of 2026-09-01 for any of: Qwen3-Omni-30B, Wan-VACE 14B, Pixal3D, VoxHammer, MoGe-3. PTQ variants exist for the first two only.</p>
<p><strong>True QAFT means the model was retrained with a fake-quant simulator in the loop</strong> (quantization-aware fine-tuning), so NF4 becomes its published precision. PTQ methods (AutoRound, AWQ, GPTQ, bitsandbytes, int8-convrot, GGUF) do not qualify: they take a released fp16 checkpoint and quantize it after the fact, no re-training.</p>
<p>Hub was searched for each of the five MaskScore-stack model families (RFD 1173) using both the family name and QAFT-specific naming conventions (<code>QAFT</code>, <code>QAT</code>, <code>-qat</code>, <code>quantization-aware</code>).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>model family</th>
<th>true-QAFT 4-bit upstream</th>
<th>PTQ-4-bit exists?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Qwen3-Omni-30B (Instruct)</td>
<td><strong>none</strong></td>
<td>yes; <code>Intel/...int4-AutoRound</code> (AutoRound), several AWQ variants</td>
</tr>
<tr class="even">
<td>Qwen3-Omni-30B (Thinking)</td>
<td><strong>none</strong></td>
<td>yes; Sabomako AWQ (source has no licence)</td>
</tr>
<tr class="odd">
<td>Wan-VACE 14B</td>
<td><strong>none</strong></td>
<td>only FP8 / INT8 / GGUF (GGUF blocklisted); no 4-bit at all</td>
</tr>
<tr class="even">
<td>Pixal3D</td>
<td><strong>none</strong></td>
<td>no quant variants at all</td>
</tr>
<tr class="odd">
<td>VoxHammer</td>
<td><strong>none</strong></td>
<td>no quant variants at all</td>
</tr>
<tr class="even">
<td>MoGe-3</td>
<td><strong>none</strong></td>
<td>no quant variants at all</td>
</tr>
</tbody>
</table>
<p><strong>Nothing was mirrored</strong> because operator scope is true QAFT only, and zero true-QAFT 4-bit checkpoints for any of the five exist upstream today. Reproducing the survey: <code>python3</code> + <code>huggingface_hub</code> <code>list_models(search=&lt;needle&gt;)</code> filtered client-side for <code>{QAFT, qaft, -qat, quantization-aware}</code> in the repo id.</p>
<p><code>heretic</code> (ARA) and <code>abliterated</code> are <strong>different</strong> guard-lifting techniques; the workspace blocklist row on abliterated weights does not extend to heretic. Not relevant to the mirror decision here because Sabomako’s heretic variant is also PTQ (AWQ), not QAFT.</p>
</section>
<section id="what-the-spec-side-read-its-only-inputs" class="level2">
<h2 class="anchored" data-anchor-id="what-the-spec-side-read-its-only-inputs">What the spec side read (its only inputs)</h2>
<ol type="1">
<li><code>https://huggingface.co/spaces/victor/gemma-avatar/raw/main/README.md</code> (README only; the space’s source tree was not opened).</li>
<li>The operator’s VN twist: “visual novel style travel between different locations and pop up talking head interactions via prompts.”</li>
</ol>
<p>The implementer side must not open any other file in that space.</p>
</section>
<section id="boot-order" class="level2">
<h2 class="anchored" data-anchor-id="boot-order">Boot order</h2>
<pre><code>personas/*.grafcet.jsonld
  -&gt; mix taskweft.grafcet.lower                  (Elixir, RFD 2148)
  -&gt; personas/lowered/*.htn.jsonld
  -&gt; mix vn_avatar.serve --port 4000             (Elixir, weftspun-studio)
     Elixir Router  ;  WebSocket  ;  Browser (canvas + prompt input)
         |
         +-&gt; BusNif -&gt; iox2 (RFD's 2-contract/bus)
         |             |
         |             +-&gt; Qwen3-VL worker    (Python, EditScore LoRA reward + text)
         |             +-&gt; Qwen3-TTS-12Hz worker (Python, RFD 1170)
         |             +-&gt; Wan-VACE worker    (Python, background gen)
         |
         +-&gt; LibGodot NIF (RFD 2154's lib_godot_connector 4.5.1)
              |
              +-&gt; headless godot process
                   SubViewport(1024x1024) -&gt; get_texture per frame
                   ANNY-in-Godot scene (soma-x rig, godot-soma-twist joint driver)
         |
         +-&gt; taskweft RECTGTN interpreter (RFD 2148)
              issues bodytags_v3.json part-mask edits ("mouth", "eyewhite")
              at each dialog beat
         |
         +-&gt; MASKSCORE row writer  (RFD 1173, taskweft-nmm-personas pattern)
         |    -&gt; traces/&lt;session&gt;.jsonl + traces/&lt;session&gt;.parquet
         +-&gt; USD writer            (RFD 2160)
              -&gt; scenes/&lt;location&gt;.usda</code></pre>
</section>
<section id="language-boundaries" class="level2">
<h2 class="anchored" data-anchor-id="language-boundaries">Language boundaries</h2>
<ol type="1">
<li><strong>Elixir</strong>; Router, WebSocket, taskweft interpreter, MASKSCORE writer, USD writer.</li>
<li><strong>Python</strong>; one file per model worker (<code>env_bus_server.py</code> shape).</li>
<li><strong>GDScript</strong>; one file: <code>vn_bridge.gd</code>, reads viseme frames off <code>set_program_variable</code>, writes SOMA facial-action weights onto the ANNY rig, publishes SubViewport texture bytes back.</li>
<li><strong>C++</strong>; none new. The bus NIF from <code>taskweft-nmm-personas</code> handles iox2.</li>
</ol>
<p>Stdio JSON is blocklisted as an Elixir&lt;-&gt;Python wire.</p>
</section>
<section id="frame-protocol-on-the-websocket" class="level2">
<h2 class="anchored" data-anchor-id="frame-protocol-on-the-websocket">Frame protocol on the WebSocket</h2>
<p>Text frames upstream (browser -&gt; server): <code>{"prompt":"...","persona":"s0042"}</code>.</p>
<p>Binary frames downstream (server -&gt; browser), one per Godot frame:</p>
<pre><code>magic  u32 = 0x56 4E 41 56  ("VNAV")
kind   u8  = 1 image, 2 audio, 3 text, 4 done
ts     u64 microseconds since session start
len    u32 payload bytes
payload len bytes</code></pre>
<p>Image frames carry a WebP-encoded 1024x1024 render of the SubViewport. Audio frames carry Opus-encoded 20 ms Qwen3-TTS-12Hz output (RFD 1170). Text frames carry the current dialog line (redundant with audio, for captioning). Done frames end a turn.</p>
</section>
<section id="speakingfaces---vn-avatar-personas-construction" class="level2">
<h2 class="anchored" data-anchor-id="speakingfaces---vn-avatar-personas-construction">SpeakingFaces -&gt; vn-avatar-personas construction</h2>
<p>Per RFD 1173 §“The undivided unit: 1 SpeakingFaces trial”:</p>
<pre><code>for subject in issai/Speaking_Faces subjects:
  pick a representative frame
  fit ANNY canonical rig via AnnyInverter + LBFGS polish
  save soma bones (78 * 3 rot + 3 root translation, float64)
  derive voice-clone conditioning tokens from a 5s audio clip
  pair with a persona .grafcet.jsonld (hand-authored per subject
    for the MVP; later, generated from the transcript vocabulary)</code></pre>
<p>Row shape:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>column</th>
<th>type</th>
<th>description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>key</td>
<td>string</td>
<td>subject id (SpeakingFaces “s0001”..”s0142”)</td>
</tr>
<tr class="even">
<td>anny_identity</td>
<td>list[float]</td>
<td>ANNY identity params</td>
</tr>
<tr class="odd">
<td>soma_pose</td>
<td>list[float]</td>
<td>78x3 + 3, canonical neutral</td>
</tr>
<tr class="even">
<td>voice_tokens</td>
<td>list[int]</td>
<td>Qwen3-TTS-12Hz CustomVoice conditioning (RFD 1170)</td>
</tr>
<tr class="odd">
<td>persona_grafcet</td>
<td>string</td>
<td>path into the same repo</td>
</tr>
<tr class="even">
<td>license</td>
<td>string</td>
<td>CC-BY-4.0 attribution to issai/Speaking_Faces</td>
</tr>
</tbody>
</table>
</section>
<section id="trace-row-shape-mirrors-maskscore-8-stub-schema" class="level2">
<h2 class="anchored" data-anchor-id="trace-row-shape-mirrors-maskscore-8-stub-schema">Trace row shape (mirrors MaskScore §8-stub schema)</h2>
<p>Each VN turn produces one row per modality (text, audio, video):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>column</th>
<th>type</th>
<th>description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>key</td>
<td>string</td>
<td>session_id + turn_index</td>
</tr>
<tr class="even">
<td>instruction</td>
<td>string</td>
<td>player’s prompt</td>
</tr>
<tr class="odd">
<td>persona</td>
<td>string</td>
<td>subject id</td>
</tr>
<tr class="even">
<td>output_text</td>
<td>string</td>
<td>Qwen3-VL line</td>
</tr>
<tr class="odd">
<td>output_audio</td>
<td>string</td>
<td>.opus path</td>
</tr>
<tr class="even">
<td>output_video</td>
<td>string</td>
<td>.webp sequence path</td>
</tr>
<tr class="odd">
<td>scores</td>
<td>list[float]</td>
<td>reward-model score per dimension</td>
</tr>
<tr class="even">
<td>task_type</td>
<td>string</td>
<td>dialog_reply</td>
</tr>
<tr class="odd">
<td>dimension</td>
<td>string</td>
<td>instruction_following</td>
</tr>
</tbody>
</table>
</section>
<section id="bootstrap-on-the-rented-vast-machine-3090-24-gib" class="level2">
<h2 class="anchored" data-anchor-id="bootstrap-on-the-rented-vast-machine-3090-24-gib">Bootstrap on the rented Vast machine (3090, 24 GiB)</h2>
<pre><code># 1. Pick a 3090 image with CUDA 12.4 + Python 3.11 + git-lfs preinstalled.
#    Expect ~$0.20-$0.35/hour on Vast; $40 buys 110-200 hours.

# 2. Clone this workspace's minimal set (not the whole hexagon).
for r in \
  2-contract/manuals-weftspun \
  2-contract/bus \
  3-interactor/taskweft \
  3-interactor/taskweft-nmm-personas \
  3-interactor/taskweft-godot-sandbox \
  3-interactor/anny \
  3-interactor/soma-x \
  3-interactor/pose-consensus \
  3-interactor/moge-upstream \
  3-interactor/pixal3d-upstream \
  3-interactor/voxhammer-upstream \
  3-interactor/wan-vace-upstream \
  1-transport/weftspun-studio ; do ...; done

# 3. Fetch SpeakingFaces (huggingface_hub, CC-BY-4.0), download
#    Qwen3-VL-4B-Instruct at fp16 (8.9 GiB) + EditScore LoRA
#    (270 MB), download Wan-VACE NF4 (8.7 GiB). Total &lt; 24 GiB
#    with swap; no QAFT round required (per RFD 1173).

# 4. mix vn_avatar.build_personas --subjects 8   (MVP corpus: 8 subjects)
#    ~30 min on the 3090.

# 5. mix vn_avatar.smoke                        (one turn end to end)
#    Asserts: WebSocket receives &gt;=1 image frame + &gt;=1 audio frame,
#    trace row lands with a non-nil reward-model score.

# 6. COMMIT AND PUSH before tear down. Everything not in a git
#    repo goes with the machine (CLAUDE.md).

# 7. `vast destroy instance &lt;id&gt;` and double-check the console.</code></pre>
</section>
<section id="mvp-smoke-in-one-sentence" class="level2">
<h2 class="anchored" data-anchor-id="mvp-smoke-in-one-sentence">MVP smoke, in one sentence</h2>
<p>Player types “hello” into the browser, one WebSocket message goes up, one Qwen3-VL line comes back, the anny-in-godot mouth moves, the SubViewport streams five WebP frames, one MaskScore trace row lands with <code>task_type = dialog_reply</code> and a non-nil reward-model score, one <code>.usda</code> records the scene. Everything after that is expansion.</p>
</section>
<section id="what-is-not-here-deferred-to-follow-on-rfds" class="level2">
<h2 class="anchored" data-anchor-id="what-is-not-here-deferred-to-follow-on-rfds">What is not here (deferred to follow-on RFDs)</h2>
<ol type="1">
<li>Voice-in phase 2. Text-in is the MVP.</li>
<li>The full 142-subject corpus. MVP is 8.</li>
<li>3D locations. MVP uses 2D Wan-VACE background stills.</li>
<li>The RL-train dataset construction. Bench + reward-train are the first two; RL-train follows once the reward model is on Hub.</li>
<li>The verifier RFD asserting our SpeechEditReward decode agrees with an independent lip-sync ground truth. That is the anti- entropy check the follow-on adds.</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/weftspun\.github\.io\/request-for-discussion");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Serials are OID arcs under the 66606 PEN and are never reused.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/rfd/2161-vn-avatar-cleanroom-on-maskscore/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/rfd/2161-vn-avatar-cleanroom-on-maskscore/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/weftspun/request-for-discussion">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>