"""Render every RFD into a page Quarto will publish, and check none was missed.

Quarto excludes `README.md` from rendering and only an exact path beats that, so
this writes `NNNN-slug/index.md` beside each README with front matter the listing
sorts on. The README stays the source: `check-rfd-structure.py` reads it by name.
Generated pages are gitignored, so nothing is committed twice.

    python scripts/render_site.py            # write the pages
    python scripts/render_site.py --check    # render, then fail if a page is absent
    python scripts/render_site.py --self-test
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

RFD_DIR = re.compile(r"^([12]\d{3})-[a-z0-9-]+$")
TITLE = re.compile(r"^#\s+(.+?)\s*$", re.M)
#: Optional: an absent field is omitted, never emitted empty.
FIELDS = ("State", "Feature", "Scope")
GENERATED = "<!-- generated by scripts/render_site.py; edit README.md instead -->"

REGISTERS = (("SERIALS.usda", 1000, 2000),
             ("SERIALS-vsekai-fabric.usda", 2000, 3000))


def arcs(root):
    out = {}
    for fname, _lo, _hi in REGISTERS:
        s = open(os.path.join(root, fname), encoding="utf8").read()
        m = re.search(r'string arc = "([0-9.]+)"', s)
        if m:
            out[fname] = m.group(1)
    return out


def oid(serial, by_arc):
    for fname, lo, hi in REGISTERS:
        if lo <= serial < hi and fname in by_arc:
            return "urn:oid:%s.%d" % (by_arc[fname], serial)
    return None


def rfd_dirs(root):
    return sorted(d for d in os.listdir(os.path.join(root, "rfd"))
                  if RFD_DIR.match(d) and os.path.isfile(os.path.join(root, "rfd", d, "README.md")))


def meta(text):
    out = {}
    for f in FIELDS:
        m = re.search(r"^\*\*%s:\*\*\s*(.+?)\s*$" % f, text, re.M)
        if m:
            out[f.lower()] = m.group(1).strip().strip("`")
    return out


def body(text):
    """The README without its title or metadata lines; both move into front matter."""
    text = TITLE.sub("", text, count=1)
    for f in FIELDS:
        text = re.sub(r"^\*\*%s:\*\*.*$\n?" % f, "", text, count=1, flags=re.M)
    return text.lstrip("\n")


def page(d, text, has_details, has_figure, oid_urn=None):
    m = TITLE.search(text)
    if not m:
        sys.exit("FAIL  %s/README.md has no title heading" % d)
    serial = int(RFD_DIR.match(d).group(1))
    front = {"rfd": serial, "title": m.group(1)}
    if oid_urn:
        front["oid"] = oid_urn
    front.update(meta(text))
    lines = ["---"]
    lines += ["%s: %s" % (k, json.dumps(v)) for k, v in front.items()]
    lines += ["---", "", GENERATED, ""]
    out = "\n".join(lines) + body(text)
    if has_details:
        out += "\n\n## Details\n\n[The measurements and the retractions](DETAILS.md)\n"
    if has_figure:
        out += "\n\n## Figure\n\n[The report as a page](page.qmd)\n"
    return out


def render(root, write=True):
    made, stale = [], []
    by_arc = arcs(root)
    for d in rfd_dirs(root):
        src = os.path.join(root, "rfd", d, "README.md")
        dst = os.path.join(root, "rfd", d, "index.md")
        serial = int(RFD_DIR.match(d).group(1))
        want = page(d, open(src, encoding="utf8").read(),
                    os.path.isfile(os.path.join(root, "rfd", d, "DETAILS.md")),
                    os.path.isfile(os.path.join(root, "rfd", d, "page.qmd")),
                    oid(serial, by_arc))
        have = open(dst, encoding="utf8").read() if os.path.isfile(dst) else None
        if have != want:
            stale.append(d)
            if write:
                open(dst, "w", encoding="utf8", newline="\n").write(want)
        made.append(d)
    return made, stale


AGREEMENTS = [
    "## Working agreements", '',
    "The standing constraints for every project in this workspace live in",
    "`CLAUDE.md` at the repository root, which reaches the workspace root",
    "through a `linkfile` in `default.xml` rather than a second copy.", '',
    "They are not rendered into this site. The file is read by an agent at",
    "the top of every session, and a published copy would be a second home",
    "for a document whose whole point is having one -- the same failure the",
    "serial register was built against.", '',
    "- [Working agreements](https://github.com/weftspun/request-for-discussion/blob/main/CLAUDE.md)",
    "- [Blocklist, with the argument behind each row](https://github.com/weftspun/request-for-discussion/blob/main/BLOCKLIST.md)",
    "- [Recurring failure modes and the guards that catch them](https://github.com/weftspun/request-for-discussion/blob/main/PITFALLS.md)",
]


def serials_page(root):
    """The register as a table, read with the gate's own parser rather than a second one."""
    import importlib.util

    g = os.path.join(HERE, "check-rfd-serials.py")
    spec = importlib.util.spec_from_file_location("rfd_serials", g)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    by_arc = arcs(root)

    def rows(t, note, fname):
        out = []
        for serial in sorted(t, key=int):
            urn = oid(int(serial), by_arc) or ""
            out.append("| `%s` | %s | %s | %s |" % (urn, serial, t[serial], note))
        return out

    lines = ['---', 'title: "Register"', 'toc: true', '---', '', GENERATED, '',
             '## Serials', '',
             "Every serial this site has allocated and every one it has retired.",
             "A serial is appended once. It is never removed and never reused,",
             "because it is the last arc of an OID and an arc names one document",
             "for as long as that document exists. The OID column is the RFC 3061",
             "URN and is stable enough to cite like a DOI.", '']
    registers = (("Weftspun (1000)", "SERIALS.usda"),
                 ("V-Sekai-Fabric (2000)", "SERIALS-vsekai-fabric.usda"))
    total_a = total_d = 0
    for heading, fname in registers:
        allocated, deleted = mod.read(open(os.path.join(root, fname), encoding="utf8").read())
        total_a += len(allocated)
        total_d += len(deleted)
        lines += ["## %s" % heading, '',
                  "| OID (urn:oid:) | Serial | Slug | State |",
                  "| --- | --- | --- | --- |"]
        lines += rows(allocated, "allocated", fname) + rows(deleted, "deleted", fname) + ['']
    lines += ["%d allocated, %d retired." % (total_a, total_d), '']
    lines += AGREEMENTS
    return "\n".join(lines) + "\n"


def self_test():
    """A renderer that has never refused a bad page has not shown it can."""
    text = ("# RFD 1234: A title, with a colon\n\n**State:** ideation\n"
            "**Scope:** `some/path`\n\n## Problem\n\nBody.\n")
    p = page("1234-a-slug", text, False, False, "urn:oid:1.3.6.1.4.1.66606.1.1.1234")
    if not p.startswith("---\n"):
        sys.exit("FAIL  no front matter emitted")
    if '"RFD 1234: A title, with a colon"' not in p:
        sys.exit("FAIL  a title containing a colon was not quoted, so the YAML would break")
    if "feature:" in p:
        sys.exit("FAIL  an absent Feature was emitted as an empty value")
    if '"some/path"' not in p:
        sys.exit("FAIL  the scope backticks were not stripped")
    if "**State:**" in p or "# RFD 1234" in p:
        sys.exit("FAIL  metadata or title left in the body, so the page renders it twice")

    if page("1234-a-slug", text, True, False, None).count("DETAILS.md") != 1:
        sys.exit("FAIL  a DETAILS.md beside the README was not linked")
    if "DETAILS.md" in p:
        sys.exit("FAIL  a DETAILS.md link was emitted where no DETAILS.md exists")
    if page("1234-a-slug", text, False, True, None).count("page.qmd") != 1:
        sys.exit("FAIL  a page.qmd beside the README was not linked")
    if "page.qmd" in p:
        sys.exit("FAIL  a page.qmd link was emitted where none exists")
    if 'oid: "urn:oid:1.3.6.1.4.1.66606.1.1.1234"' not in p:
        sys.exit("FAIL  the OID URN was not emitted in the front matter")

    n = len(rfd_dirs(ROOT))
    if n < 100:
        sys.exit("FAIL  found %d RFD directories, far below the register's count" % n)
    print("self-test: colons quoted, absent fields omitted, title and metadata "
          "moved out of the body, DETAILS and page.qmd linked only when present, "
          "%d dirs seen" % n)
    return 0


def book_page(root):
    by_arc = arcs(root)
    lines = ['---', 'title: "Weftspun RFDs"',
             'subtitle: "The register as one book"', 'author: "Weftspun"',
             'toc: true', 'number-sections: false',
             '---', '', GENERATED, '']
    for d in sorted(rfd_dirs(root), key=lambda x: int(RFD_DIR.match(x).group(1))):
        serial = int(RFD_DIR.match(d).group(1))
        src = os.path.join(root, "rfd", d, "README.md")
        text = open(src, encoding="utf8").read().rstrip()
        urn = oid(serial, by_arc)
        if urn:
            text = re.sub(r"^(# .+?)$", r"\1\n\n**OID:** `" + urn + "`", text, count=1, flags=re.M)
        lines.append(text)
        lines.append("")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()

    made, wrote = render(ROOT)
    sp = os.path.join(ROOT, "pages", "serials.md")
    os.makedirs(os.path.dirname(sp), exist_ok=True)
    open(sp, "w", encoding="utf8", newline="\n").write(serials_page(ROOT))
    bp = os.path.join(ROOT, "book.qmd")
    open(bp, "w", encoding="utf8", newline="\n").write(book_page(ROOT))

    if a.check:
        missing = [d for d in made if not os.path.isfile(os.path.join(ROOT, "rfd", d, "index.md"))]
        if missing or not os.path.isfile(sp):
            print("FAIL  %d RFD page(s) absent after a render: %s"
                  % (len(missing), ", ".join(missing[:5])))
            return 1
        print("  ok    %d RFD directories, %d pages, serials rendered"
              % (len(rfd_dirs(ROOT)), len(made)))
        return 0
    print("  ok    %d RFD pages, %d rewritten" % (len(made), len(wrote)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
