#!/usr/bin/env python3
"""Render three Flight Level listing pages from serial-register tags."""
from __future__ import annotations

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

LEVELS = [
    ("L1", "flight-level-1-operations.qmd",   "Level 1 — Operations",
     "How individual teams execute. Fast cadence, team-scoped, done means the ticket is complete."),
    ("L2", "flight-level-2-coordination.qmd", "Level 2 — Coordination",
     "How work flows across teams to reach a customer. Medium cadence, product and delivery leads."),
    ("L3", "flight-level-3-strategy.qmd",     "Level 3 — Strategy",
     "Portfolio decisions about where to invest. Slow cadence, executive decision-makers."),
]

SERIAL_BLOCK = re.compile(
    r'def\s+"S(?P<serial>\d+)"\s*{(?P<body>[^{}]*)}',
    re.DOTALL,
)
SLUG_FIELD  = re.compile(r'custom\s+string\s+slug\s*=\s*"([^"]+)"')
LEVEL_FIELD = re.compile(r'custom\s+string\s+flight_level\s*=\s*"(L[123])"')


def read_tags(root: str) -> dict[str, list[tuple[int, str]]]:
    by_level: dict[str, list[tuple[int, str]]] = {"L1": [], "L2": [], "L3": []}
    for entry in sorted(os.listdir(root)):
        if not (entry == "SERIALS.usda"
                or (entry.startswith("SERIALS-") and entry.endswith(".usda"))):
            continue
        text = open(os.path.join(root, entry), encoding="utf-8", errors="replace").read()
        # Only look inside the Allocated scope; Deleted serials keep their
        # historical flight_level tag but do not have a live directory to
        # point at, so listing them here produces broken links.
        alloc_m = re.search(r'def\s+Scope\s+"Allocated"\s*{', text)
        if not alloc_m:
            continue
        # Walk from Allocated's opening brace forward, tracking depth to find
        # its closing brace. Everything between is the Allocated body.
        start = alloc_m.end()
        depth = 1
        i = start
        while i < len(text) and depth > 0:
            if text[i] == '{': depth += 1
            elif text[i] == '}': depth -= 1
            i += 1
        allocated_body = text[start:i - 1]
        for m in SERIAL_BLOCK.finditer(allocated_body):
            serial = int(m.group("serial"))
            body = m.group("body")
            level_m = LEVEL_FIELD.search(body)
            slug_m  = SLUG_FIELD.search(body)
            if not (level_m and slug_m):
                continue
            by_level[level_m.group(1)].append((serial, slug_m.group(1)))
    for lvl in by_level:
        by_level[lvl].sort(reverse=True)
    return by_level


def rfd_index_path(serial: int, slug: str) -> str:
    return f"../rfd/{serial}-{slug}/index.md"


def render_page(level_id: str, fname: str, title: str, blurb: str,
                items: list[tuple[int, str]]) -> str:
    if items:
        contents = "\n".join(f'    - "{rfd_index_path(s, slug)}"' for s, slug in items)
        listing = (
            "listing:\n"
            "  filter-ui: true\n"
            "  sort-ui: true\n"
            "  type: table\n"
            "  contents:\n" + contents + "\n"
            "  sort:\n"
            "    - \"rfd desc\"\n"
            "  fields: [rfd, title, state, scope]\n"
            "  exclude:\n"
            "    state: [\"abandoned\", \"moved\"]\n"
            "  page-size: 50\n"
        )
    else:
        listing = "# (no RFDs tagged at this level yet)\n"
    return (
        "---\n"
        f"title: \"{title}\"\n"
        "toc: true\n"
        f"{listing}"
        "---\n\n"
        "<!-- generated by scripts/render_flight_level_pages.py -->\n\n"
        f"{blurb}\n\n"
        f"RFDs tagged `flight_level = \"{level_id}\"` in the serial register. "
        "RFD 2177 defines the scheme (Klaus Leopold, `Rethinking Agile`,\n"
        "LEANability, 2018).\n"
    )


def write_pages(root: str, tags: dict[str, list[tuple[int, str]]],
                check: bool = False) -> int:
    pages_dir = os.path.join(root, "pages")
    os.makedirs(pages_dir, exist_ok=True)
    missing = 0
    for level, fname, title, blurb in LEVELS:
        want = render_page(level, fname, title, blurb, tags[level])
        p = os.path.join(pages_dir, fname)
        open(p, "w", encoding="utf-8").write(want)
        if not os.path.exists(p):
            missing += 1
            print(f"missing: {p}")
        else:
            print(f"ok    {p} ({len(tags[level])} RFDs)")
    return missing if check else 0


def self_test() -> int:
    import tempfile
    tmp = tempfile.mkdtemp()
    open(os.path.join(tmp, "SERIALS-plant.usda"), "w").write(
        '#usda 1.0\n'
        'def "S9001" { custom string slug = "ops-thing"; '
        'custom string flight_level = "L1" }\n'
        'def "S9002" { custom string slug = "strat-thing"; '
        'custom string flight_level = "L3" }\n'
        'def "S9003" { custom string slug = "malformed"; '
        'custom string flight_level = "NOT-A-LEVEL" }\n'
        'def "S9004" { custom string slug = "no-tag" }\n'
    )
    tags = read_tags(tmp)
    assert tags["L1"] == [(9001, "ops-thing")], f"L1 mismatch: {tags['L1']}"
    assert tags["L3"] == [(9002, "strat-thing")], f"L3 mismatch: {tags['L3']}"
    assert tags["L2"] == [], f"L2 should be empty: {tags['L2']}"
    print("ok: self-test passed (2 planted tags grouped, 1 malformed ignored, 1 untagged ignored)")
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args(argv[1:])
    if a.self_test:
        return self_test()
    tags = read_tags(ROOT)
    drift = write_pages(ROOT, tags, check=a.check)
    return 1 if (a.check and drift) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
