"""Render every RFD into a page Quarto will publish, and check none was missed.

Quarto excludes `README.md` from rendering and only an exact path beats that, so
this writes `NNNN-slug/index.md` beside each README with front matter the listing
sorts on. The README stays the source: `check-rfd-structure.py` reads it by name.
Generated pages are gitignored, so nothing is committed twice.

    python scripts/render_site.py            # write the pages
    python scripts/render_site.py --check    # render, then fail if a page is absent
    python scripts/render_site.py --self-test
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

RFD_DIR = re.compile(r"^(\d+)-[a-z0-9-]+$")
TITLE = re.compile(r"^#\s+(.+?)\s*$", re.M)
#: Optional: an absent field is omitted, never emitted empty.
FIELDS = ("State", "Feature", "Scope")
GENERATED = "<!-- generated by scripts/render_site.py; edit README.md instead -->"


def rfd_dirs(root):
    return sorted(d for d in os.listdir(root)
                  if RFD_DIR.match(d) and os.path.isfile(os.path.join(root, d, "README.md")))


def meta(text):
    out = {}
    for f in FIELDS:
        m = re.search(r"^\*\*%s:\*\*\s*(.+?)\s*$" % f, text, re.M)
        if m:
            out[f.lower()] = m.group(1).strip().strip("`")
    return out


def body(text):
    """The README without its title or metadata lines; both move into front matter."""
    text = TITLE.sub("", text, count=1)
    for f in FIELDS:
        text = re.sub(r"^\*\*%s:\*\*.*$\n?" % f, "", text, count=1, flags=re.M)
    return text.lstrip("\n")


def page(d, text, has_details):
    m = TITLE.search(text)
    if not m:
        sys.exit("FAIL  %s/README.md has no title heading" % d)
    front = {"rfd": int(RFD_DIR.match(d).group(1)), "title": m.group(1)}
    front.update(meta(text))
    lines = ["---"]
    lines += ["%s: %s" % (k, json.dumps(v)) for k, v in front.items()]
    lines += ["---", "", GENERATED, ""]
    out = "\n".join(lines) + body(text)
    if has_details:
        out += "\n\n## Details\n\n[The measurements and the retractions](DETAILS.md)\n"
    return out


def render(root, write=True):
    made, stale = [], []
    for d in rfd_dirs(root):
        src = os.path.join(root, d, "README.md")
        dst = os.path.join(root, d, "index.md")
        want = page(d, open(src, encoding="utf8").read(),
                    os.path.isfile(os.path.join(root, d, "DETAILS.md")))
        have = open(dst, encoding="utf8").read() if os.path.isfile(dst) else None
        if have != want:
            stale.append(d)
            if write:
                open(dst, "w", encoding="utf8", newline="\n").write(want)
        made.append(d)
    return made, stale


def serials_page(root):
    """The register as a table, read with the gate's own parser rather than a second one."""
    import importlib.util

    g = os.path.join(HERE, "check-rfd-serials.py")
    spec = importlib.util.spec_from_file_location("rfd_serials", g)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    allocated, deleted = mod.read(open(os.path.join(root, "SERIALS.usda"), encoding="utf8").read())

    def rows(t, note):
        out = []
        for serial in sorted(t, key=int):
            out.append("| %s | %s | %s |" % (serial, t[serial], note))
        return out

    lines = ['---', 'title: "Serials"', 'toc: true', '---', '', GENERATED, '',
             "Every serial this site has allocated and every one it has retired.",
             "A serial is appended once. It is never removed and never reused,",
             "because it is the last arc of an OID and an arc names one document",
             "for as long as that document exists.", '',
             "| Serial | Slug | State |", "| --- | --- | --- |"]
    lines += rows(allocated, "allocated") + rows(deleted, "deleted")
    lines += ['', "%d allocated, %d retired." % (len(allocated), len(deleted))]
    return "\n".join(lines) + "\n"


def self_test():
    """A renderer that has never refused a bad page has not shown it can."""
    text = ("# RFD 1234: A title, with a colon\n\n**State:** ideation\n"
            "**Scope:** `some/path`\n\n## Problem\n\nBody.\n")
    p = page("1234-a-slug", text, False)
    if not p.startswith("---\n"):
        sys.exit("FAIL  no front matter emitted")
    if '"RFD 1234: A title, with a colon"' not in p:
        sys.exit("FAIL  a title containing a colon was not quoted, so the YAML would break")
    if "feature:" in p:
        sys.exit("FAIL  an absent Feature was emitted as an empty value")
    if '"some/path"' not in p:
        sys.exit("FAIL  the scope backticks were not stripped")
    if "**State:**" in p or "# RFD 1234" in p:
        sys.exit("FAIL  metadata or title left in the body, so the page renders it twice")

    if page("1234-a-slug", text, True).count("DETAILS.md") != 1:
        sys.exit("FAIL  a DETAILS.md beside the README was not linked")
    if "DETAILS.md" in p:
        sys.exit("FAIL  a DETAILS.md link was emitted where no DETAILS.md exists")

    n = len(rfd_dirs(ROOT))
    if n < 100:
        sys.exit("FAIL  found %d RFD directories, far below the register's count" % n)
    print("self-test: colons quoted, absent fields omitted, title and metadata "
          "moved out of the body, DETAILS linked only when present, %d dirs seen" % n)
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()

    made, wrote = render(ROOT)
    sp = os.path.join(ROOT, "pages", "serials.md")
    os.makedirs(os.path.dirname(sp), exist_ok=True)
    open(sp, "w", encoding="utf8", newline="\n").write(serials_page(ROOT))

    if a.check:
        missing = [d for d in made if not os.path.isfile(os.path.join(ROOT, d, "index.md"))]
        if missing or not os.path.isfile(sp):
            print("FAIL  %d RFD page(s) absent after a render: %s"
                  % (len(missing), ", ".join(missing[:5])))
            return 1
        print("  ok    %d RFD directories, %d pages, serials rendered"
              % (len(rfd_dirs(ROOT)), len(made)))
        return 0
    print("  ok    %d RFD pages, %d rewritten" % (len(made), len(wrote)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
