<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>details – Taskweft — Manuals</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5a10fc84a7bff526434d52200a729576.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-f36f388c175c695e587c9d92b6af4f92.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5a10fc84a7bff526434d52200a729576.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-285d64067b7bfd38b4f886e30e47acef.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-ebf6027466d64ce25e353d53063d38f8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-285d64067b7bfd38b4f886e30e47acef.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Taskweft — Manuals</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-flight-levels" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Flight Levels</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-flight-levels">    
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-1-operations.html">
 <span class="dropdown-text">L1 · Operations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-2-coordination.html">
 <span class="dropdown-text">L2 · Coordination</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-3-strategy.html">
 <span class="dropdown-text">L3 · Strategy</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../pages/logbook.html"> 
<span class="menu-text">Logbook</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../pages/serials.html"> 
<span class="menu-text">Register</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#rfd-1142-details-what-the-neural-engine-reaches-and-what-it-holds" id="toc-rfd-1142-details-what-the-neural-engine-reaches-and-what-it-holds" class="nav-link active" data-scroll-target="#rfd-1142-details-what-the-neural-engine-reaches-and-what-it-holds">RFD 1142 details: what the Neural Engine reaches, and what it holds</a>
  <ul class="collapse">
  <li><a href="#the-placement-gate-and-why-it-comes-first" id="toc-the-placement-gate-and-why-it-comes-first" class="nav-link" data-scroll-target="#the-placement-gate-and-why-it-comes-first">The placement gate, and why it comes first</a></li>
  <li><a href="#two-ceilings-and-the-first-sweep-found-neither" id="toc-two-ceilings-and-the-first-sweep-found-neither" class="nav-link" data-scroll-target="#two-ceilings-and-the-first-sweep-found-neither">Two ceilings, and the first sweep found neither</a>
  <ul class="collapse">
  <li><a href="#the-total-ceiling-is-2-gib-and-it-is-exactly-231-bytes" id="toc-the-total-ceiling-is-2-gib-and-it-is-exactly-231-bytes" class="nav-link" data-scroll-target="#the-total-ceiling-is-2-gib-and-it-is-exactly-231-bytes">The total ceiling is 2 GiB, and it is exactly 2^31 bytes</a></li>
  <li><a href="#what-the-literature-does-and-does-not-say" id="toc-what-the-literature-does-and-does-not-say" class="nav-link" data-scroll-target="#what-the-literature-does-and-does-not-say">What the literature does and does not say</a></li>
  </ul></li>
  <li><a href="#throughput-and-a-cliff-that-is-not-the-ceiling" id="toc-throughput-and-a-cliff-that-is-not-the-ceiling" class="nav-link" data-scroll-target="#throughput-and-a-cliff-that-is-not-the-ceiling">Throughput, and a cliff that is not the ceiling</a></li>
  <li><a href="#the-same-graph-on-metal" id="toc-the-same-graph-on-metal" class="nav-link" data-scroll-target="#the-same-graph-on-metal">The same graph on Metal</a></li>
  <li><a href="#the-comparison-on-the-two-axes-that-decide-it" id="toc-the-comparison-on-the-two-axes-that-decide-it" class="nav-link" data-scroll-target="#the-comparison-on-the-two-axes-that-decide-it">The comparison, on the two axes that decide it</a>
  <ul class="collapse">
  <li><a href="#four-confounds-stated-rather-than-buried" id="toc-four-confounds-stated-rather-than-buried" class="nav-link" data-scroll-target="#four-confounds-stated-rather-than-buried">Four confounds, stated rather than buried</a></li>
  </ul></li>
  <li><a href="#the-real-model-converted-natively-and-what-it-settles" id="toc-the-real-model-converted-natively-and-what-it-settles" class="nav-link" data-scroll-target="#the-real-model-converted-natively-and-what-it-settles">The real model, converted natively, and what it settles</a>
  <ul class="collapse">
  <li><a href="#three-faults-paid-for-on-the-way" id="toc-three-faults-paid-for-on-the-way" class="nav-link" data-scroll-target="#three-faults-paid-for-on-the-way">Three faults paid for on the way</a></li>
  </ul></li>
  <li><a href="#what-this-does-not-resolve" id="toc-what-this-does-not-resolve" class="nav-link" data-scroll-target="#what-this-does-not-resolve">What this does NOT resolve</a></li>
  <li><a href="#four-bits-and-why-the-column-is-absent" id="toc-four-bits-and-why-the-column-is-absent" class="nav-link" data-scroll-target="#four-bits-and-why-the-column-is-absent">Four bits, and why the column is absent</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/rfd/1142-the-mac-against-the-ugen300/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/rfd/1142-the-mac-against-the-ugen300/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>





<section id="rfd-1142-details-what-the-neural-engine-reaches-and-what-it-holds" class="level1">
<h1>RFD 1142 details: what the Neural Engine reaches, and what it holds</h1>
<p>Every number here is from <code>scripts/ane_bench.py</code> on one machine: Apple M2 Pro, 32 GiB unified, 16-core ANE, macOS 26.5.2, coremltools 9.0. A timing without the machine is not a measurement, so the machine is printed by the script rather than recalled into the table.</p>
<section id="the-placement-gate-and-why-it-comes-first" class="level2">
<h2 class="anchored" data-anchor-id="the-placement-gate-and-why-it-comes-first">The placement gate, and why it comes first</h2>
<p><code>rfd1122-plan.usda</code> carries <code>neuralEngineUsefulForBackbone = 0</code>, backed by 1685.1 ms at 576 against the CPU’s 476.4. That ran through ONNX Runtime’s CoreML execution provider, which partitions a graph and falls back per operator, and it recorded no placement. So the number is consistent with two opposite worlds and selects neither.</p>
<p><code>MLComputePlan</code> answers it per operation. Two details cost time to find:</p>
<ul>
<li>It requires a <strong>compiled</strong> model. Handed an <code>.mlpackage</code> it does not raise — it aborts the process with an <code>ios_base::failure</code> from libc++. The compile step is inside <code>placement()</code> so no caller can meet that.</li>
<li>Constants carry no device and are <strong>excluded from the denominator</strong>. A graph is mostly weights, so counting them lets anything look well placed.</li>
</ul>
<p>The negative control is <code>ComputeUnit.CPU_ONLY</code>, which cannot reach the device:</p>
<pre><code>positive (ComputeUnit.ALL)      ane=8/8   {'ane': 8}  consts=28
negative (ComputeUnit.CPU_ONLY) ane=0/8   {'cpu': 8}  consts=28</code></pre>
<p>Rule 2 is the whole reason that second line exists. A placement gate that has never returned “no” certifies nothing, which is precisely the defect it was built to correct.</p>
</section>
<section id="two-ceilings-and-the-first-sweep-found-neither" class="level2">
<h2 class="anchored" data-anchor-id="two-ceilings-and-the-first-sweep-found-neither">Two ceilings, and the first sweep found neither</h2>
<p>The first sweep grew width at depth 8 and found a cliff between 1543.7 MiB and 1599.3 MiB of fp16 weights, placement collapsing from 16/16 operations to 1/16. Read alone, that says the device holds about 1.5 GiB.</p>
<p>It says nothing of the kind. Holding parameters near constant and changing the shape moves the cliff:</p>
<pre><code>depth  width   params        pkg MiB   ANE fraction
8      3584    809,392,640   1543.7    1.000
8      3648    838,554,816   1599.3    0.062
32     1704    810,263,928   1545.3    1.000
32     1800    904,123,800   1724.3    1.000</code></pre>
<p>A <strong>larger</strong> model passed where a smaller one failed. Shape decides the cliff; total size fails to explain it. The decisive control is a two-layer graph, where the total is small and one tensor is large:</p>
<pre><code>depth  width   one weight   total MiB   ANE fraction
2      3584    220.5 MiB    220.7       1.000
2      3648    228.4 MiB    228.6       0.250
2      4096    288.0 MiB    288.2       0.250</code></pre>
<p>Same boundary as depth 8, at a seventh of the total. <strong>The limit is a single weight tensor between 220.5 and 228.4 MiB</strong>, and 224 MiB sits inside that bracket. The sweep resolution is one width step, so the bracket is the answer and 224 is a guess at a round number inside it.</p>
<p>RETRACTED, IN THE SAME SESSION THAT WROTE IT: “the Neural Engine has no model-size ceiling worth planning around. It has a layer-width ceiling.” The second sentence stands. The first was an artifact of stopping the sweep at 1.7 GiB, and the paragraph is kept because the error is instructive — a shape control disproved a total-size limit and was then read as proving no total-size limit existed. It disproved one number, not the category.</p>
<section id="the-total-ceiling-is-2-gib-and-it-is-exactly-231-bytes" class="level3">
<h3 class="anchored" data-anchor-id="the-total-ceiling-is-2-gib-and-it-is-exactly-231-bytes">The total ceiling is 2 GiB, and it is exactly 2^31 bytes</h3>
<p>Continuing the sweep with a deep, narrow stack — every tensor 55.6 MiB, far under the per-tensor cap — finds the second limit:</p>
<pre><code>depth  width   weights MiB   ops   ANE fraction
36     1800    1946.8         72   1.000
37     1800    2002.4         74   1.000
38     1800    2058.0         76   0.000
40     1800    2169.3         80   0.000
64     1800    3504.1        128   0.000</code></pre>
<p>2048 MiB sits between the passing 2002.4 and the failing 2058.0, and 2^31 bytes is 2,147,483,648 against those two at 2,099,520,000 and 2,157,840,000. The limit is 2 GiB of weights.</p>
<p>It is bytes rather than operation count, and one control separates them: depth 32 at width 2020 carries 2171.5 MiB in only 64 operations and fails, while depth 36 at width 1800 carries 1946.8 MiB in 72 operations and passes. Fewer operations and more bytes still fails.</p>
<p>When it fails it fails wholesale. Placement goes to 0.000 and every operation moves to the GPU together, rather than the graph splitting across the two.</p>
</section>
<section id="what-the-literature-does-and-does-not-say" class="level3">
<h3 class="anchored" data-anchor-id="what-the-literature-does-and-does-not-say">What the literature does and does not say</h3>
<p>Bryngelson’s <em>Apple Neural Engine: Architecture, Programming, and Performance</em> (arXiv 2606.22283) documents a per-axis extent cap of 16384 on the M1 generation, “applied per-axis rather than to the last axis alone”. The weights measured above are <code>[3648, 3648, 3, 3]</code> — every axis is an order of magnitude inside that cap. So the boundary found here is <strong>not</strong> the documented one, and searching turned up the reason: Apple does not publish the internal buffer limits. This bracket is measured, not cited.</p>
</section>
</section>
<section id="throughput-and-a-cliff-that-is-not-the-ceiling" class="level2">
<h2 class="anchored" data-anchor-id="throughput-and-a-cliff-that-is-not-the-ceiling">Throughput, and a cliff that is not the ceiling</h2>
<p>Convolution stacks at 3x3 stride-1, FLOPs counted as <code>2 * MACs</code> — <code>gpu_tops.py</code>’s convention, so the numbers compose with the GPU rows already in the plan.</p>
<pre><code>width   GMAC/inf   ms med    TFLOP/s   of 15.8 peak   ANE fraction
128       16.97      6.484     5.234   0.331          1.000
256       67.76     15.339     8.835   0.559          1.000
512      270.81     45.887    11.803   0.747          1.000
768      609.15     89.694    13.583   0.860          1.000
1024    1082.78    168.062    12.886   0.816          1.000
1536    2435.93    371.910    13.100   0.829          1.000
2048    4330.23   1319.102     6.565   0.416          1.000</code></pre>
<p><strong>13.583 TFLOP/s, 86.0% of the cited 15.8 TOPS</strong>, is the best rate with every operation on the device.</p>
<p>The last row matters more than the best one. At width 2048 the rate halves while placement stays at 1.000 — the work is still on the Neural Engine and is running at half speed. Its weights are 72 MiB per tensor, well inside the 224 MiB cap, so this is a bandwidth or residency effect and not the ceiling above. <strong>Throughput degrades before placement does</strong>, which means a placement check alone is not a health check, and a model sized by the cap alone will be slow before it is rejected.</p>
</section>
<section id="the-same-graph-on-metal" class="level2">
<h2 class="anchored" data-anchor-id="the-same-graph-on-metal">The same graph on Metal</h2>
<p>The Neural Engine’s rate means little without the other engine in the same machine running the same work. <code>--units gpu</code> confines the identical convolution stack to <code>CPU_AND_GPU</code>:</p>
<pre><code>width   GMAC/inf   ms med    TFLOP/s   placement
512      270.81     80.472     6.731   {'gpu': 16}
768      609.15    174.665     6.975   {'gpu': 16}
1024    1082.78    311.664     6.948   {'gpu': 16}
1536    2435.93    719.915     6.767   {'gpu': 16}</code></pre>
<p><strong>6.98 TFLOP/s against the Neural Engine’s 13.58 on the same graph — 1.95x.</strong> This also corroborates <code>gpu_tops.py</code>’s 6.20 TFLOP/s fp16 for this desk from dense GEMM, measured by a different route on a different shape.</p>
<p>The GPU has no 2 GiB wall: it ran the 3504.1 MiB stack the Neural Engine refused. So above 2 GiB this machine still executes the model, at half the rate.</p>
</section>
<section id="the-comparison-on-the-two-axes-that-decide-it" class="level2">
<h2 class="anchored" data-anchor-id="the-comparison-on-the-two-axes-that-decide-it">The comparison, on the two axes that decide it</h2>
<p>Compared at ONE precision, fp16, because both parts offer a choice of precision and a comparison across two of them measures the choice rather than the hardware.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>M2 Pro ANE</th>
<th>M2 Pro Metal</th>
<th>Hailo-10H / UGen300</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>fp16 rate</td>
<td><strong>13.58 TFLOP/s</strong> measured</td>
<td><strong>6.98</strong> measured</td>
<td>~10 TOPS, halved from 20 INT8</td>
</tr>
<tr class="even">
<td>of cited peak</td>
<td>0.86 of 15.8</td>
<td>1.03 of the 6.8 fp32 derivation</td>
<td>not measured, no device</td>
</tr>
<tr class="odd">
<td>weights it holds</td>
<td><strong>2 GiB</strong>, measured</td>
<td>&gt;= 3.5 GiB, measured</td>
<td>8 GiB nominal</td>
</tr>
<tr class="even">
<td>per-tensor cap</td>
<td>~224 MiB, measured</td>
<td>none found</td>
<td>unknown</td>
</tr>
<tr class="odd">
<td>host bandwidth</td>
<td>~200 GB/s</td>
<td>~200 GB/s</td>
<td>USB 3.1 Gen2, ~1.2 GB/s</td>
</tr>
<tr class="even">
<td>power</td>
<td>unmeasured, needs sudo</td>
<td>unmeasured</td>
<td>2.5 W typical</td>
</tr>
</tbody>
</table>
<p><strong>The crossover is 2 GiB of weights.</strong> Under it the Mac runs at 13.58 against the UGen300’s derived 10, and wins. Over it the Neural Engine refuses wholesale, Metal picks the work up at 6.98, and the UGen300 holds its rate over four times the memory.</p>
<p>The earlier reading of this table had the memory axis backwards. It compared the Mac’s 32 GiB of unified memory against the device’s 8 GiB, when the quantity that decides placement is the 2 GiB the Neural Engine will accept.</p>
<section id="four-confounds-stated-rather-than-buried" class="level3">
<h3 class="anchored" data-anchor-id="four-confounds-stated-rather-than-buried">Four confounds, stated rather than buried</h3>
<ol type="1">
<li><strong>The units measure different work.</strong> 13.58 TFLOP/s fp16 against 12 TOPS INT4 assumes one INT4 operation is worth one fp16 operation. It does less. The comparison is generous to the Hailo, and it only holds under 2 GiB.</li>
<li><strong>The Hailo column is derived.</strong> No UGen300 is attached to this machine and none of its rows were observed. RFD 1130 exists to replace them.</li>
<li><strong>0.86 is an upper bound, and it is this device’s.</strong> A 3x3 stride-1 stack is the friendliest shape either part sees. Carrying 0.86 across to the Hailo would be assuming what the plan already declines to assume at 0.3.</li>
<li><strong>The Hailo fp16 rate is halved from its INT8 row, not read from a datasheet.</strong> 20 TOPS INT8 halving to about 10 at sixteen bits follows the pattern its own INT4 and INT8 rows set. The plan carries no fp16 entry for this part, and one belongs there before the crossover above is planned against.</li>
<li><strong>Power went unmeasured.</strong> <code>powermetrics --samplers ane_power</code> needs sudo and was not run, so the 2.5 W column has no counterpart. Named and counted, per rule 3, rather than dropped to make the table symmetrical.</li>
</ol>
</section>
</section>
<section id="the-real-model-converted-natively-and-what-it-settles" class="level2">
<h2 class="anchored" data-anchor-id="the-real-model-converted-natively-and-what-it-settles">The real model, converted natively, and what it settles</h2>
<p><code>rf-detr-cpp/scripts/gate_coreml_device.py</code> converts the same traced module <code>gate_onnx_device.py</code> hands its exporter, so the two gates measure one graph by two routes. 373 operations, resolution 576, num_windows 1, fp16, 2 resizes folded:</p>
<pre><code>units   ms med   max|diff|   bound 4.2e-03   placement
ane      121.6   4.311e-02   FAIL            {'ane': 373}
gpu       62.0   3.524e-03   ok              {'gpu': 373}
cpu      133.0   2.425e-01   FAIL            {'cpu': 373}</code></pre>
<p><strong><code>neuralEngineUsefulForBackbone = 0</code> is settled, and its evidence is retracted.</strong> The flag came from 1685.1 ms through onnxruntime’s CoreML provider, reproduced here at 3758.9 with <code>--num-windows 1</code>. Natively the same graph runs at 121.6 ms, so that route was 31x pessimistic and was measuring a partitioner. The VERDICT stands on a different ground: at fp16 the Neural Engine misses the port’s own bound by ten times, while Metal passes it and is twice as fast. A right answer held for a wrong reason is corrected because the wrong reason predicts wrongly elsewhere.</p>
<p>Metal’s margin is thin and worth stating: 3.524e-03 against 4.2e-03 is 1.19x of headroom.</p>
<section id="three-faults-paid-for-on-the-way" class="level3">
<h3 class="anchored" data-anchor-id="three-faults-paid-for-on-the-way">Three faults paid for on the way</h3>
<p><strong>A coremltools bug, shimmed rather than vendored.</strong> <code>_cast</code> validates its input as “a scalar or a (1 x 1 x … x 1) tensor”, then its constant branch calls <code>dtype(x.val)</code> without the squeeze its non-constant branch applies. <code>int(np.array([48]))</code> raises. The device half hits it at <code>encoder/encoder/embeddings/68</code>, where transformers’ Dinov2 <code>interpolate_pos_encoding</code> computes <code>sqrt_num_positions</code> as shape (1,). Identical at torch 2.11.0 and at the tested 2.7.1, so the version warning was a red herring — which is why <code>rf-detr-cpp</code> gained a <code>coreml</code> feature pinning the tested torch rather than repinning the shared <code>gate</code>.</p>
<p><strong>An unimplemented operator, folded with the project’s own fold.</strong> coremltools has no converter for <code>_upsample_bicubic2d_aa</code>. <code>gate_onnx_device._fold_antialias</code> already folds it for the ONNX route, exactly because the resize reads a parameter and a size rather than the image, so at fixed resolution folding is exact. Borrowed rather than reimplemented, so the two gates cannot disagree about the graph they measured.</p>
<p><strong>A comparison that paired outputs by shape.</strong> The device half returns two tensors of identical (1, 256, 48, 48) shape, so the first version compared one reference against the other output and reported 2.501e+00 on every row. The CPU row exposed it: Core ML’s own CPU cannot disagree with PyTorch by 2.5. Outputs are now assigned to their closest free reference and the chosen pairing is printed, so the assignment is auditable.</p>
</section>
</section>
<section id="what-this-does-not-resolve" class="level2">
<h2 class="anchored" data-anchor-id="what-this-does-not-resolve">What this does NOT resolve</h2>
<p>The UGen300 column stays derived. Its fp16 rate is halved from its 20 TOPS INT8 row rather than read from a datasheet, no such part is attached to this machine, and RFD 1130 exists to replace those rows. The physical device is expected, and until it lands every Hailo figure here predicts rather than reports.</p>
<p>Metal’s own ceiling above 8176.2 MiB went unmeasured. The sweep stopped at the UGen300’s 8 GiB because that is the quantity being compared against, rather than because Metal refused.</p>
<p>Power went unmeasured on both Mac engines. <code>powermetrics --samplers ane_power</code> needs sudo and stayed unrun, so the device’s 2.5 W typical has no counterpart here. Named and counted rather than dropped to make the table symmetrical.</p>
</section>
<section id="four-bits-and-why-the-column-is-absent" class="level2">
<h2 class="anchored" data-anchor-id="four-bits-and-why-the-column-is-absent">Four bits, and why the column is absent</h2>
<p>The first plan for this work measured a precision ladder. Two findings closed it early.</p>
<p>Core ML does store four-bit weights: an int4 package is exactly a quarter of the fp16 one on disk, 126.0 MiB against 504.1 at 264M parameters. But the graph gains eight <code>ios18.constexpr_lut_to_dense</code> operations, which carry no device assignment, and the sixteen arithmetic operations stay exactly where they were. The compute width does not change, because the int4 and int8-int8 fast paths arrived with A17 Pro and M4 and this is an M2. Four bits buys disk here and adds decompression.</p>
<p>The ladder was dropped when the memory axis looked unbounded. With the ceiling at 2 GiB that reasoning no longer holds: four bits would quarter the weights and move a model from Metal’s 6.98 back onto the Neural Engine’s 13.58, which is a real trade rather than a disk saving. Reinstating the ladder is the next work this RFD asks for.</p>
<p>An <code>int4-linear</code> row would still close the question cheaply, and it remains unrun. <code>--precisions int4-linear</code> is wired and takes minutes; <code>int4</code> k-means does not, at these sizes, and hung a sweep at 838M parameters before it was killed.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/weftspun\.github\.io\/request-for-discussion");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Serials are OID arcs under the 66606 PEN and are never reused.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/rfd/1142-the-mac-against-the-ugen300/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/rfd/1142-the-mac-against-the-ugen300/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/weftspun/request-for-discussion">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>