<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>details – Taskweft — Manuals</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ea71ec77f2e5f2de0947d12aa6258b01.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-3336bfa29d6298ea485ddf0d64c2ca2e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-ea71ec77f2e5f2de0947d12aa6258b01.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Taskweft — Manuals</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../pages/rfd.html"> 
<span class="menu-text">RFDs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/serials.html"> 
<span class="menu-text">Serials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/logbook.html"> 
<span class="menu-text">Logbook</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/agreements.html"> 
<span class="menu-text">Working agreements</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#rfd-1169-details-the-tower-the-fork-gap-and-the-half-that-has-no-path" id="toc-rfd-1169-details-the-tower-the-fork-gap-and-the-half-that-has-no-path" class="nav-link active" data-scroll-target="#rfd-1169-details-the-tower-the-fork-gap-and-the-half-that-has-no-path">RFD 1169 details: the tower, the fork gap, and the half that has no path</a>
  <ul class="collapse">
  <li><a href="#why-this-is-the-vision-tower-again" id="toc-why-this-is-the-vision-tower-again" class="nav-link" data-scroll-target="#why-this-is-the-vision-tower-again">Why this is the vision tower again</a></li>
  <li><a href="#the-operator-question-which-is-the-encouraging-one" id="toc-the-operator-question-which-is-the-encouraging-one" class="nav-link" data-scroll-target="#the-operator-question-which-is-the-encouraging-one">The operator question, which is the encouraging one</a></li>
  <li><a href="#the-fork-gap-stated-precisely" id="toc-the-fork-gap-stated-precisely" class="nav-link" data-scroll-target="#the-fork-gap-stated-precisely">The fork gap, stated precisely</a></li>
  <li><a href="#asr-against-voice-cloning-and-the-correction" id="toc-asr-against-voice-cloning-and-the-correction" class="nav-link" data-scroll-target="#asr-against-voice-cloning-and-the-correction">ASR against voice cloning, and the correction</a></li>
  <li><a href="#qwen3.5-omni-has-no-checkpoint-to-take-a-projector-from" id="toc-qwen3.5-omni-has-no-checkpoint-to-take-a-projector-from" class="nav-link" data-scroll-target="#qwen3.5-omni-has-no-checkpoint-to-take-a-projector-from">Qwen3.5-Omni has no checkpoint to take a projector from</a></li>
  <li><a href="#the-better-answer-for-asr-is-a-smaller-model-not-a-bigger-tower" id="toc-the-better-answer-for-asr-is-a-smaller-model-not-a-bigger-tower" class="nav-link" data-scroll-target="#the-better-answer-for-asr-is-a-smaller-model-not-a-bigger-tower">The better answer for ASR is a smaller model, not a bigger tower</a></li>
  <li><a href="#the-checkpoint-licence-clean-but-the-projector-does-not-transfer" id="toc-the-checkpoint-licence-clean-but-the-projector-does-not-transfer" class="nav-link" data-scroll-target="#the-checkpoint-licence-clean-but-the-projector-does-not-transfer">The checkpoint: licence clean, but the projector does not transfer</a></li>
  <li><a href="#the-fixed-window-which-is-unresolved" id="toc-the-fixed-window-which-is-unresolved" class="nav-link" data-scroll-target="#the-fixed-window-which-is-unresolved">The fixed window, which is unresolved</a></li>
  <li><a href="#what-to-measure-cheapest-first" id="toc-what-to-measure-cheapest-first" class="nav-link" data-scroll-target="#what-to-measure-cheapest-first">What to measure, cheapest first</a></li>
  <li><a href="#what-this-does-not-claim" id="toc-what-this-does-not-claim" class="nav-link" data-scroll-target="#what-this-does-not-claim">What this does not claim</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/1169-the-audio-tower-for-qwen3-vl/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/1169-the-audio-tower-for-qwen3-vl/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>





<section id="rfd-1169-details-the-tower-the-fork-gap-and-the-half-that-has-no-path" class="level1">
<h1>RFD 1169 details: the tower, the fork gap, and the half that has no path</h1>
<section id="why-this-is-the-vision-tower-again" class="level2">
<h2 class="anchored" data-anchor-id="why-this-is-the-vision-tower-again">Why this is the vision tower again</h2>
<p>RFD 1157 established the shape: EditScore is a LoRA over Qwen3-VL, and <code>llama-cpp-npu-vision</code> compiles the encoder into a HEF while decode stays on the host. The audio proposal is the same arrangement with a different front end.</p>
<pre><code>tower              input                       output

vision, ViT        image, fixed edge           tokens at 4096
audio, AuT         128-bin log-mel, fixed      1280, needing a new
                   frame count                 projector to 4096</code></pre>
<p>Both end in an MLP projector writing into the decoder’s sequence space, which is why one hook can serve both and why the fork’s refusal to is the thing to fix rather than a reason to look elsewhere. The widths differ and the section on the checkpoint below is where that is paid for.</p>
</section>
<section id="the-operator-question-which-is-the-encouraging-one" class="level2">
<h2 class="anchored" data-anchor-id="the-operator-question-which-is-the-encouraging-one">The operator question, which is the encouraging one</h2>
<p>A Whisper-shaped encoder is two strided convolutions, a positional add, then transformer blocks. Every operator that needs is already in <code>DEVICE_OPS</code>:</p>
<pre><code>Conv                 the mel front end
MatMul, Softmax      attention
LayerNormalization   45 of them survived in rf-detr's graph
Erf                  inside the gelu sequence, and only there
Transpose, Slice, Concat, Add, Mul   shape plumbing</code></pre>
<p><code>hailo_ops.usda</code> records that <code>Erf</code> is accepted <strong>only</strong> as part of the gelu pattern and is rejected standing alone, so an encoder using a gelu approximation rather than the exact form is worth checking before assuming it translates.</p>
<p><strong>The input rank is the risk worth naming, and it looks survivable.</strong> <code>_add_input_layers</code> refused Pixal3D four times because its inputs are a voxel grid and a timestep rather than anything image-shaped. A log-mel is 128 bins by a fixed frame count — a single-channel 2D array, which is exactly the shape the parser wants. This is the one place the audio path is structurally luckier than the 3D one.</p>
</section>
<section id="the-fork-gap-stated-precisely" class="level2">
<h2 class="anchored" data-anchor-id="the-fork-gap-stated-precisely">The fork gap, stated precisely</h2>
<p><code>tools/mtmd/clip.cpp:2834</code>, <code>clip_init_hailo</code>:</p>
<ul>
<li>refuses any <code>proj_type</code> but <code>PROJECTOR_TYPE_QWEN3VL</code></li>
<li>sets <code>ctx-&gt;model.modality = CLIP_MODALITY_VISION</code> unconditionally</li>
<li>takes <code>max_image_edge</code>, <code>patch_size</code>, <code>spatial_merge_size</code>, <code>image_mean[3]</code>, <code>image_std[3]</code> — every parameter image-shaped</li>
</ul>
<p>Upstream <code>mtmd</code> is already more general than this. It carries <code>CLIP_MODALITY_AUDIO</code>, a <code>clip_graph_whisper_enc</code> builder, <code>KEY_A_NUM_MEL_BINS</code> and <code>KEY_AUDIO_PROJ_TYPE</code>. So the work is to widen the Hailo entry point to the modality the surrounding code already knows about: a modality argument, mel bins and frame count where edge and patch go, and no three-channel normalization.</p>
<p><strong>This is a change to a repository we own.</strong> <code>weftspun/llama-cpp-npu-vision</code> is in <code>default.xml</code> pinned at <code>6a27290</code>, forked from <code>hailo-ai/llama.cpp</code> for exactly this kind of edit. CLAUDE.md’s rule for other people’s codebases applies to the upstream part: match the density of the code being edited and put the reasoning in the commit message.</p>
</section>
<section id="asr-against-voice-cloning-and-the-correction" class="level2">
<h2 class="anchored" data-anchor-id="asr-against-voice-cloning-and-the-correction">ASR against voice cloning, and the correction</h2>
<p>An earlier revision of this section said voice cloning was “not in reach” and that this buys ears and not a voice. <strong>That was too strong, and asking for the cloning variant is what exposed it.</strong> Qwen publishes one, and it is clean:</p>
<pre><code>model                            licence      params   released

Qwen3-TTS-12Hz-1.7B-CustomVoice  Apache-2.0   1.92 B   2026-01-21
Qwen3-TTS-12Hz-1.7B-VoiceDesign  Apache-2.0   1.92 B   2026-01-21
Qwen3-TTS-Tokenizer-12Hz         Apache-2.0   0.17 B   2026-01-21</code></pre>
<p>All ungated, all newer than Qwen3-VL-8B, and 1.92 B is 1.92 GB at eight bits against the device’s 8 GB. Nothing about availability, licensing or memory blocks a voice.</p>
<p><strong>What was actually true is narrower: the synthesis stage does not compile.</strong> That is a claim about the accelerator and not about the capability, and conflating the two is the error the earlier wording made. Split properly:</p>
<pre><code>stage                          shape              device half?

audio in, AuT or ASR encoder   fixed              yes
speaker embedding from a       fixed              yes
reference clip
codec tokens to waveform,      fixed, feed        probably, and
the 0.17 B tokenizer           forward            worth measuring
text to codec tokens,          autoregressive,    no, RFD 1126
the 1.92 B backbone            growing cache</code></pre>
<p><strong>12 Hz is the number that makes this comfortable.</strong> Most neural codecs run at 25 to 75 tokens a second; this one emits twelve, so a ten-second utterance is 120 autoregressive steps rather than several hundred. The stage that cannot be accelerated is also the stage that needs least accelerating, and it runs on the host exactly as Qwen3-VL’s own decode already does.</p>
<p><strong>So the corrected statement is that the accelerator buys ears, and the host can still supply a voice.</strong> That is a different sentence from the one this document shipped, and the difference matters to anyone reading it to decide whether the capability is available at all.</p>
<p>The 0.17 B tokenizer is the interesting unmeasured piece. If its decode side is a feed-forward vocoder it is a small fixed-shape graph and a plausible rung-1 candidate on its own, which would put the waveform generation on the device while the token generation stays off it.</p>
</section>
<section id="qwen3.5-omni-has-no-checkpoint-to-take-a-projector-from" class="level2">
<h2 class="anchored" data-anchor-id="qwen3.5-omni-has-no-checkpoint-to-take-a-projector-from">Qwen3.5-Omni has no checkpoint to take a projector from</h2>
<p>Ripping the projector from Qwen3.5-Omni was proposed on the grounds that a retrain is happening anyway. <strong>No official Qwen3.5-Omni exists.</strong> The Qwen organisation’s newest Omni release is Qwen3-Omni-30B-A3B; the Qwen3.5 line is published in other shapes, and every <code>Qwen3.5-Omni</code> name on Hugging Face belongs to a third party rather than to Qwen. The announcement page is a JavaScript shell that serves no text to a fetcher, so this is what the model index says rather than what the blog says.</p>
<p>That is a statement about what can be downloaded today, not a claim the model does not exist. If it lands, the argument for taking the newer projector stands – a projector being retrained is a projector whose provenance is free to change.</p>
</section>
<section id="the-better-answer-for-asr-is-a-smaller-model-not-a-bigger-tower" class="level2">
<h2 class="anchored" data-anchor-id="the-better-answer-for-asr-is-a-smaller-model-not-a-bigger-tower">The better answer for ASR is a smaller model, not a bigger tower</h2>
<p>Searching for that checkpoint turned up three releases that change the recommendation:</p>
<pre><code>model                        licence      audio enc       mel

Qwen3-ASR-0.6B-hf            Apache-2.0   896, 18 layers   128
Qwen3-ASR-1.7B-hf            Apache-2.0   1024, 24 layers  128
Qwen3-ForcedAligner-0.6B-hf  Apache-2.0   -                 -</code></pre>
<p>All three are ungated Apache-2.0 and take <strong>128 mel bins</strong>, exactly the front end this proposal specified.</p>
<p><strong>The 1.7B is the one to take, and it fits.</strong> Its parameter count is 2.04 B whole – 4.08 GB at bf16 and 2.04 GB at eight bits against the device’s 8 GB, so unlike almost every row in RFD 1166 it does not meet RFD 1128’s four-bit question at all. Its encoder is 1024 wide over 24 layers, against the 0.6B’s 896 over 18, and its decoder is 2048 rather than 1024.</p>
<p>That is the better trade here. The thing this buys is transcription quality, the smaller model saves 2 GB that nothing else is waiting for, and both compile the same way because the encoder is the device half in either case.</p>
<p><strong>Its age was queried, and checking inverted the concern.</strong> The <code>-hf</code> suffixes are June transformers conversions; the models themselves are older. But older than what is the question that matters:</p>
<pre><code>checkpoint                  released      relative to our base

Qwen3-Omni-30B-A3B          2025-09-20    3 weeks OLDER
Qwen3-VL-8B                 2025-10-11    the base
Qwen3-ASR-0.6B              2026-01-28    3.5 months newer</code></pre>
<p><strong>The AuT tower comes out of the oldest artifact in the set</strong>, older than the model it would be bolted onto, while the ASR model that looked stale is the newest thing here by a wide margin. A recency objection to <code>Qwen3-ASR-0.6B</code> argues harder against the Omni route it was raised to defend.</p>
<p><strong>This is arXiv:2608.12875’s argument arriving in the concrete.</strong> The paper’s finding is not “smaller is fine” but that a specialised model ties a general one on the task it was built for, at a fraction of the cost, and that the general model should be reserved for the class where it genuinely leads. Transcription is the specialised task. A 0.6B ASR model against a 300M tower extracted from a 30B mixture-of-experts is the same trade the paper measures at 1431x, and it resolves the same way.</p>
<p>So the two routes are not competing, they answer different questions:</p>
<pre><code>want                                   route

transcription, alignment, captions     Qwen3-ASR-0.6B, standalone
audio inside the VLM's reasoning --    the AuT tower, a new
"what is the tone of this clip,        projector to 4096, and a
given the image"                       LoRA on Qwen3-VL</code></pre>
<p><strong>The first costs a download and the second costs a training run.</strong> Nothing yet says the second is needed, and RFD 1168’s ordering rule says find out with the first.</p>
</section>
<section id="the-checkpoint-licence-clean-but-the-projector-does-not-transfer" class="level2">
<h2 class="anchored" data-anchor-id="the-checkpoint-licence-clean-but-the-projector-does-not-transfer">The checkpoint: licence clean, but the projector does not transfer</h2>
<p><strong>The licence is usable.</strong> Qwen3-Omni-30B-A3B, in all three variants, is <strong>Apache-2.0</strong>. The Hugging Face API reports <code>license: other</code> while <code>license_name</code> and the card badge both say <code>apache-2.0</code>, which is metadata noise rather than a second licence – worth recording because <code>other</code> is the value that should always be chased rather than assumed.</p>
<p><strong>There is no standalone AuT checkpoint.</strong> Only the three 30B-A3B variants are published, so obtaining a 300M tower means extracting it from a 30B mixture-of-experts download.</p>
<p><strong>AND THE PROJECTOR TARGETS THE WRONG WIDTH.</strong></p>
<pre><code>model                  text hidden   audio hidden   audio layers

Qwen3-Omni-30B-A3B        2048          1280            32
Qwen3-VL-8B               4096          none            none
Qwen3-ASR-0.6B            1024           896            18</code></pre>
<p>The proposal was stated as log-mel into “the same 4096 sequence space”. 4096 is right for Qwen3-VL-8B’s decoder and <strong>wrong for every projector that exists</strong>: Qwen3-Omni’s AuT writes into 2048 and the ASR model’s into 1024, because those are the decoders they were trained inside.</p>
<p>So the transfer splits in two. The <strong>encoder</strong> carries over, and it is the part that would compile. The <strong>projector does not</strong>, and a new MLP into 4096 has to be trained with a LoRA teaching Qwen3-VL to read it.</p>
<p><strong>That is exactly EditScore’s arrangement.</strong> RFD 1157 records EditScore as a LoRA over Qwen3-VL holding 516 tensors, 12 of them at <code>deepstack_merger_list</code> – the projector adaptation – with the ViT left stock. An audio LoRA is the same object with an audio tower behind it, which is a reason to think the arrangement works and not a reason to think the training is free.</p>
<p><code>PROJECTOR_TYPE_QWEN3A</code>’s <code>conv2d_1/2/3</code> are worth noting separately: QWEN2A uses <code>conv1d</code>, QWEN3A uses <strong>2D</strong> convolutions, direct evidence that the log-mel is handled as a single-channel image and support for the input-rank argument above.</p>
</section>
<section id="the-fixed-window-which-is-unresolved" class="level2">
<h2 class="anchored" data-anchor-id="the-fixed-window-which-is-unresolved">The fixed window, which is unresolved</h2>
<p>Audio is variable length and the compiler is not. Whisper answers this by padding every clip to 30 seconds, which is a fixed shape bought with wasted compute on short utterances.</p>
<p>Nothing here has decided the window, and the choice is a real trade:</p>
<ul>
<li>a long window wastes the device on short utterances, and most utterances are short</li>
<li>a short window forces chunking, and chunking across a sentence boundary is where transcription errors concentrate</li>
</ul>
<p>This wants measuring against the actual utterance length distribution before a number is picked, and no such distribution has been collected.</p>
</section>
<section id="what-to-measure-cheapest-first" class="level2">
<h2 class="anchored" data-anchor-id="what-to-measure-cheapest-first">What to measure, cheapest first</h2>
<p>Following RFD 1168’s ordering rule and the stratification argument in arXiv:2608.12875 — climb only as far as the answer requires:</p>
<ol type="1">
<li><strong>Export a stock Whisper-family encoder to ONNX at a fixed window</strong> and run <code>gate_onnx_device.py</code> against it. No fork change, no device, and it answers the operator question outright.</li>
<li><strong>Translate it with <code>gate_dfc_parse.py</code>.</strong> This is where the input rank claim above is confirmed or refused, and it is the step that stopped Pixal3D.</li>
<li><strong>Only then widen <code>clip_init_hailo</code></strong>, because the fork change is pointless if the graph does not translate.</li>
</ol>
<p>Steps 1 and 2 need no audio corpus and no AuT checkpoint. They test the architecture rather than the model, which is the same reason RFD 1168 starts with a one-hot constant.</p>
</section>
<section id="what-this-does-not-claim" class="level2">
<h2 class="anchored" data-anchor-id="what-this-does-not-claim">What this does not claim</h2>
<p>It does not claim the 300M AuT checkpoint is available under a licence this workspace can use. That has not been checked, and RFD 1166 records what happens when a row is scored without reading its weights.</p>
<p>It does not claim parity with Gemma 4. Gemma 4 was wanted for language, vision and sound in one model; this is three towers around one decoder, which is a different arrangement that happens to answer the same need.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/weftspun\.github\.io\/request-for-discussion");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Serials are OID arcs under the 66606 PEN and are never reused.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/1169-the-audio-tower-for-qwen3-vl/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/1169-the-audio-tower-for-qwen3-vl/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/weftspun/request-for-discussion">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>