<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>details – Taskweft — Manuals</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5a10fc84a7bff526434d52200a729576.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-f36f388c175c695e587c9d92b6af4f92.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5a10fc84a7bff526434d52200a729576.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9dc8f7b0063e587a5bbf917ac285fb0e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-dd645bdd3be9d8713d016f89b66f7356.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-9dc8f7b0063e587a5bbf917ac285fb0e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Taskweft — Manuals</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-flight-levels" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Flight Levels</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-flight-levels">    
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-1-operations.html">
 <span class="dropdown-text">L1 · Operations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-2-coordination.html">
 <span class="dropdown-text">L2 · Coordination</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-3-strategy.html">
 <span class="dropdown-text">L3 · Strategy</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../pages/logbook.html"> 
<span class="menu-text">Logbook</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../pages/serials.html"> 
<span class="menu-text">Register</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#rfd-1171-details-every-role-what-fills-it-and-the-five-that-are-empty" id="toc-rfd-1171-details-every-role-what-fills-it-and-the-five-that-are-empty" class="nav-link active" data-scroll-target="#rfd-1171-details-every-role-what-fills-it-and-the-five-that-are-empty">RFD 1171 details: every role, what fills it, and the five that are empty</a>
  <ul class="collapse">
  <li><a href="#every-movement-runs-both-ways-and-the-inverses-are-the-hard-half" id="toc-every-movement-runs-both-ways-and-the-inverses-are-the-hard-half" class="nav-link" data-scroll-target="#every-movement-runs-both-ways-and-the-inverses-are-the-hard-half">Every movement runs both ways, and the inverses are the hard half</a></li>
  <li><a href="#recover-not-undress" id="toc-recover-not-undress" class="nav-link" data-scroll-target="#recover-not-undress"><code>recover</code>, not <code>undress</code></a></li>
  <li><a href="#the-taxonomy-is-the-spine-and-it-already-splits-correctly" id="toc-the-taxonomy-is-the-spine-and-it-already-splits-correctly" class="nav-link" data-scroll-target="#the-taxonomy-is-the-spine-and-it-already-splits-correctly">The taxonomy is the spine, and it already splits correctly</a></li>
  <li><a href="#movement-one-make-a-persona" id="toc-movement-one-make-a-persona" class="nav-link" data-scroll-target="#movement-one-make-a-persona">Movement one: make a persona</a></li>
  <li><a href="#movement-two-dress-it" id="toc-movement-two-dress-it" class="nav-link" data-scroll-target="#movement-two-dress-it">Movement two: dress it</a></li>
  <li><a href="#movement-three-be-it" id="toc-movement-three-be-it" class="nav-link" data-scroll-target="#movement-three-be-it">Movement three: be it</a></li>
  <li><a href="#movement-four-make-a-friend" id="toc-movement-four-make-a-friend" class="nav-link" data-scroll-target="#movement-four-make-a-friend">Movement four: make a friend</a></li>
  <li><a href="#the-webcam-is-not-only-a-motion-source-and-each-head-is-its-own-compile" id="toc-the-webcam-is-not-only-a-motion-source-and-each-head-is-its-own-compile" class="nav-link" data-scroll-target="#the-webcam-is-not-only-a-motion-source-and-each-head-is-its-own-compile">The webcam is not only a motion source, and each head is its own compile</a></li>
  <li><a href="#so-the-camera-feeds-all-four-movements-not-just-be-it-so-the-camera-feeds-all-four-movements-not-just-be-it" id="toc-so-the-camera-feeds-all-four-movements-not-just-be-it-so-the-camera-feeds-all-four-movements-not-just-be-it" class="nav-link" data-scroll-target="#so-the-camera-feeds-all-four-movements-not-just-be-it-so-the-camera-feeds-all-four-movements-not-just-be-it">So the camera feeds all four movements, not just <code>be it</code>## So the camera feeds all four movements, not just <code>be it</code></a></li>
  <li><a href="#everything-is-a-contour-and-one-of-them-is-a-projection-not-an-inference" id="toc-everything-is-a-contour-and-one-of-them-is-a-projection-not-an-inference" class="nav-link" data-scroll-target="#everything-is-a-contour-and-one-of-them-is-a-projection-not-an-inference">Everything is a contour, and one of them is a projection not an inference</a></li>
  <li><a href="#moge-supplies-both-halves-and-the-second-is-the-one-nobody-asked-for" id="toc-moge-supplies-both-halves-and-the-second-is-the-one-nobody-asked-for" class="nav-link" data-scroll-target="#moge-supplies-both-halves-and-the-second-is-the-one-nobody-asked-for">MoGe supplies both halves, and the second is the one nobody asked for</a></li>
  <li><a href="#contour.py-which-is-the-first-piece-of-this-actually-built" id="toc-contour.py-which-is-the-first-piece-of-this-actually-built" class="nav-link" data-scroll-target="#contour.py-which-is-the-first-piece-of-this-actually-built"><code>contour.py</code>, which is the first piece of this actually built</a></li>
  <li><a href="#multi-view-is-preferred-and-the-input-decides-whether-it-exists" id="toc-multi-view-is-preferred-and-the-input-decides-whether-it-exists" class="nav-link" data-scroll-target="#multi-view-is-preferred-and-the-input-decides-whether-it-exists">Multi-view is preferred, and the input decides whether it exists</a></li>
  <li><a href="#lingbot-map-is-the-one-that-is-licence-clean-and-it-was-never-checked" id="toc-lingbot-map-is-the-one-that-is-licence-clean-and-it-was-never-checked" class="nav-link" data-scroll-target="#lingbot-map-is-the-one-that-is-licence-clean-and-it-was-never-checked">LingBot-Map is the one that is licence-clean, and it was never checked</a></li>
  <li><a href="#depth_term.py-is-written-against-marigold-which-is-now-blocked" id="toc-depth_term.py-is-written-against-marigold-which-is-now-blocked" class="nav-link" data-scroll-target="#depth_term.py-is-written-against-marigold-which-is-now-blocked"><code>depth_term.py</code> is written against Marigold, which is now blocked</a></li>
  <li><a href="#swapping-marigold-for-moge-loses-independence-and-that-is-the-cost" id="toc-swapping-marigold-for-moge-loses-independence-and-that-is-the-cost" class="nav-link" data-scroll-target="#swapping-marigold-for-moge-loses-independence-and-that-is-the-cost">Swapping Marigold for MoGe loses independence, and that is the cost</a></li>
  <li><a href="#the-trio-re-derived-for-metric-depth" id="toc-the-trio-re-derived-for-metric-depth" class="nav-link" data-scroll-target="#the-trio-re-derived-for-metric-depth">The trio re-derived for metric depth</a></li>
  <li><a href="#align_affine-must-not-stay-as-it-is-and-off-is-not-the-answer-either" id="toc-align_affine-must-not-stay-as-it-is-and-off-is-not-the-answer-either" class="nav-link" data-scroll-target="#align_affine-must-not-stay-as-it-is-and-off-is-not-the-answer-either"><code>align_affine</code> must not stay as it is, and off is not the answer either</a></li>
  <li><a href="#lingbot-depth-was-checked-and-is-not-a-candidate" id="toc-lingbot-depth-was-checked-and-is-not-a-candidate" class="nav-link" data-scroll-target="#lingbot-depth-was-checked-and-is-not-a-candidate">LingBot-Depth was checked and is not a candidate</a></li>
  <li><a href="#depth_term.py-is-written-against-marigold-which-is-now-blocked-1" id="toc-depth_term.py-is-written-against-marigold-which-is-now-blocked-1" class="nav-link" data-scroll-target="#depth_term.py-is-written-against-marigold-which-is-now-blocked-1"><code>depth_term.py</code> is written against Marigold, which is now blocked</a></li>
  <li><a href="#taking-moge-for-that-slot-spends-the-independence-knowingly" id="toc-taking-moge-for-that-slot-spends-the-independence-knowingly" class="nav-link" data-scroll-target="#taking-moge-for-that-slot-spends-the-independence-knowingly">Taking MoGe for that slot spends the independence, knowingly</a></li>
  <li><a href="#lingbot-depth-was-checked-and-is-not-a-candidate-1" id="toc-lingbot-depth-was-checked-and-is-not-a-candidate-1" class="nav-link" data-scroll-target="#lingbot-depth-was-checked-and-is-not-a-candidate-1">LingBot-Depth was checked and is not a candidate</a></li>
  <li><a href="#single-view-moge-3-is-taken-and-moge-2-stays-for-pixal3d" id="toc-single-view-moge-3-is-taken-and-moge-2-stays-for-pixal3d" class="nav-link" data-scroll-target="#single-view-moge-3-is-taken-and-moge-2-stays-for-pixal3d">Single view: MoGe-3 is taken, and MoGe-2 stays for Pixal3D</a></li>
  <li><a href="#the-rung-2-export-describes-the-wrong-model-now" id="toc-the-rung-2-export-describes-the-wrong-model-now" class="nav-link" data-scroll-target="#the-rung-2-export-describes-the-wrong-model-now">The rung-2 export describes the wrong model now</a></li>
  <li><a href="#the-walk-video-can-be-rendered-which-makes-the-error-measurable" id="toc-the-walk-video-can-be-rendered-which-makes-the-error-measurable" class="nav-link" data-scroll-target="#the-walk-video-can-be-rendered-which-makes-the-error-measurable">The walk video can be rendered, which makes the error measurable</a></li>
  <li><a href="#mapping-models-were-reconsidered-and-the-field-is-licence-hostile" id="toc-mapping-models-were-reconsidered-and-the-field-is-licence-hostile" class="nav-link" data-scroll-target="#mapping-models-were-reconsidered-and-the-field-is-licence-hostile">Mapping models were reconsidered, and the field is licence-hostile</a></li>
  <li><a href="#metric3d-v2-was-assessed-as-a-fallback-and-it-is-not-one" id="toc-metric3d-v2-was-assessed-as-a-fallback-and-it-is-not-one" class="nav-link" data-scroll-target="#metric3d-v2-was-assessed-as-a-fallback-and-it-is-not-one">Metric3D v2 was assessed as a fallback, and it is not one</a></li>
  <li><a href="#the-hazard-in-doing-this-which-is-not-small" id="toc-the-hazard-in-doing-this-which-is-not-small" class="nav-link" data-scroll-target="#the-hazard-in-doing-this-which-is-not-small">The hazard in doing this, which is not small</a></li>
  <li><a href="#what-the-mesh-contour-does-not-give" id="toc-what-the-mesh-contour-does-not-give" class="nav-link" data-scroll-target="#what-the-mesh-contour-does-not-give">What the mesh contour does not give</a></li>
  <li><a href="#decided-keep-keypoints-and-segmentation-drop-detection" id="toc-decided-keep-keypoints-and-segmentation-drop-detection" class="nav-link" data-scroll-target="#decided-keep-keypoints-and-segmentation-drop-detection">Decided: keep keypoints and segmentation, drop detection</a></li>
  <li><a href="#express-the-surviving-two-as-keypoints-because-keypoints-are-fixed-shape" id="toc-express-the-surviving-two-as-keypoints-because-keypoints-are-fixed-shape" class="nav-link" data-scroll-target="#express-the-surviving-two-as-keypoints-because-keypoints-are-fixed-shape">Express the surviving two as keypoints, because keypoints are fixed-shape</a></li>
  <li><a href="#what-the-unification-costs-which-is-not-nothing" id="toc-what-the-unification-costs-which-is-not-nothing" class="nav-link" data-scroll-target="#what-the-unification-costs-which-is-not-nothing">What the unification costs, which is not nothing</a></li>
  <li><a href="#the-five-stages-with-no-model" id="toc-the-five-stages-with-no-model" class="nav-link" data-scroll-target="#the-five-stages-with-no-model">The five stages with no model</a></li>
  <li><a href="#what-is-measured-against-what" id="toc-what-is-measured-against-what" class="nav-link" data-scroll-target="#what-is-measured-against-what">What is measured against what</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/rfd/1171-the-presence-loop-and-every-role-in-it/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/rfd/1171-the-presence-loop-and-every-role-in-it/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>





<section id="rfd-1171-details-every-role-what-fills-it-and-the-five-that-are-empty" class="level1">
<h1>RFD 1171 details: every role, what fills it, and the five that are empty</h1>
<section id="every-movement-runs-both-ways-and-the-inverses-are-the-hard-half" class="level2">
<h2 class="anchored" data-anchor-id="every-movement-runs-both-ways-and-the-inverses-are-the-hard-half">Every movement runs both ways, and the inverses are the hard half</h2>
<p>The frame is not new here. <code>pose-consensus/python/depth_term.py</code> opens by saying every stage of the avatar pipeline has a forward and an inverse, and tabulates four of them. The movements sit on top of the same column:</p>
<pre><code>forward                            inverse

make      a description becomes    fit        a picture becomes the
          a body                              body that cast it
dress     a layer goes onto the    recover    the body comes back
          body                                out from under it
be it     a person supplies the    a friend   a model supplies it
          motion and the voice                instead

pose      FK and LBS, sinew-solve  AnnyInverter, LBFGS
skinning  LBS apply                SkinTokens
build     624 blendshapes          soft silhouette
depth     soft_depth               a monocular estimator</code></pre>
<p><strong>The forwards are arithmetic and the inverses are not.</strong> Posing a mesh from joint angles has one answer. Recovering the joint angles from a picture has many, and the whole of <code>pose-consensus</code> exists because of that asymmetry: the LBFGS fit, the silhouette and the depth term are three opinions on one inverse, and RFD 1168’s masking-as-corruption is the same admission one movement up.</p>
<p><strong>So the checkers are not distributed evenly, and should not be.</strong> Nothing checks the forward directions. Every inverse has at least one check, and the ill-posed ones have several. A reader looking for where the risk sits should read the right-hand column.</p>
</section>
<section id="recover-not-undress" class="level2">
<h2 class="anchored" data-anchor-id="recover-not-undress"><code>recover</code>, not <code>undress</code></h2>
<p>The inverse of <code>dress</code> takes the body back out from under a garment. It is named for what it produces, and naming it after the clothing would lose that – the operation exists to obtain a body model, and the garment is what stands in the way.</p>
<p>It is also the subtraction already recorded here, read backwards: the posed mesh gives the body outline, MoGe depth gives the person’s outline, and the difference is the layer. Forwards that composes a clothed figure; backwards it recovers the body.</p>
</section>
<section id="the-taxonomy-is-the-spine-and-it-already-splits-correctly" class="level2">
<h2 class="anchored" data-anchor-id="the-taxonomy-is-the-spine-and-it-already-splits-correctly">The taxonomy is the spine, and it already splits correctly</h2>
<p><code>common/live2d/scrap_model.py</code> in See-Through’s tree carries <code>VALID_BODY_PARTS_V3</code>. RFD 1166 kept it as the one part of that project whose licence permits reuse, and it turns out to be the vocabulary this whole loop needs:</p>
<pre><code>worn, and therefore swappable    the body, and therefore given

headwear                          front hair
eyewear                           back hair
earwear                           face
neckwear                          irides, eyewhite, eyelash, eyebrow
topwear                           ears
handwear                          nose
bottomwear                        mouth
legwear                           neck
footwear                          tail, wings
                                  objects</code></pre>
<p><strong>Nine worn slots, thirteen body parts, one catch-all.</strong> The split was drawn by somebody decomposing illustrations into layers, not by anybody thinking about garments, and it lands exactly where a try-on needs it. That is worth noticing rather than assuming: a taxonomy that survives being used for a second purpose is usually describing something real.</p>
<p>Two of the body rows are load-bearing for the rest. <code>front hair</code> and <code>back hair</code> are a depth relation, which is why RFD 1168 argues the decomposition belongs in 3D, and it is the same reason a hat has to know which hair it sits under.</p>
</section>
<section id="movement-one-make-a-persona" class="level2">
<h2 class="anchored" data-anchor-id="movement-one-make-a-persona">Movement one: make a persona</h2>
<p>Language and an image become a character, and a character with a manner and a voice is a persona rather than a model sheet.</p>
<pre><code>role                       filled by            state

understand the ask         Qwen3-VL-8B          runs, host
generate and edit in 2D    OmniGen2             measured, never
                                                exported
style, 2D and 3D           cyclegan_style_...   no model in the
                                                workspace
photo to depth and         MoGe                 rung 2, MIT
intrinsics
image to 3D structure      TRELLIS.2 / Pixal3D  rung 2, refused at
                                                rung 3
accept or reject a         EditScore            runs, host
proposal
a manner                   Qwen3-VL, prompt     unwritten
                           or LoRA
a voice identity           Qwen3-TTS            Apache-2.0, ready
                           CustomVoice</code></pre>
<p><strong>The gate is the stage most worth questioning.</strong> EditScore is a LoRA over Qwen3-VL-8B at 6.75 GiB, which is most of an 8 GB device, and RFD 1166 records the open question from arXiv:2608.12875: if that gate is classification, an embedding model ties an LLM at a fraction of the cost. Nobody has established which it is.</p>
</section>
<section id="movement-two-dress-it" class="level2">
<h2 class="anchored" data-anchor-id="movement-two-dress-it">Movement two: dress it</h2>
<p>The character’s worn layers are swapped.</p>
<pre><code>role                       filled by            state

name the slots             VALID_BODY_PARTS_V3  in tree, licence
                                                clean
the body boundary          ANNY mesh through    silhouette.py
                           silhouette.py        exists
the person boundary        MoGe depth           rung 2, MIT
the camera both need       MoGe intrinsics      returned by infer
either, as a fixed ring    contour.py           WRITTEN, tested
carry it into the latent   VoxHammer's          the call exists,
                           grid_sample          payload untested
fill what the mask         LaMa,                MIT, does NOT
removed                    AnimeMangaInpaint    compile, rfftn
edit the asset in latent   VoxHammer            rung 0, wrapper
space                                           unwired
rig a mesh into a          SkinTokens           wrapper only, MIT
wearable                                        upstream
cloth against body         MuJoCo MJX           not a network</code></pre>
<p><strong>A try-on is the masking operation from RFD 1168, run for a different reason.</strong> Decomposition removes a layer to see it; a try-on removes a layer to replace it. The hole is the same hole and LaMa fills it either way, which is why one mechanism serves both and neither needs its own.</p>
<p><strong><code>objects</code> is where this gets hard and the taxonomy stops helping.</strong> A bag, a prop or a held item is not a slot on a body, and <code>VALID_BODY_PARTS_V3</code> puts all of them in one bucket. Anything beyond the nine slots is unmodelled here.</p>
</section>
<section id="movement-three-be-it" class="level2">
<h2 class="anchored" data-anchor-id="movement-three-be-it">Movement three: be it</h2>
<p>A person wears the character, live, and supplies its motion.</p>
<pre><code>role                       filled by            state

track a body every frame   rf-detr keypoints    RUNG 3, alone
keypoints to a rig         SOMA-X, anny_from_   topology exists,
                           soma                 gap is RFD 1122
lip-sync from the wearer   TalkingHead, MIT     unstudied
render, live               Godot                four checkouts
render, reference          Mitsuba 3            the oracle
body dynamics              MuJoCo MJX           not a network</code></pre>
</section>
<section id="movement-four-make-a-friend" class="level2">
<h2 class="anchored" data-anchor-id="movement-four-make-a-friend">Movement four: make a friend</h2>
<p>Nobody wears it. It has presence to someone, and supplies its own motion and its own voice.</p>
<pre><code>role                       filled by            state

hear                       Qwen3-ASR-1.7B       Apache-2.0, ready
think                      Qwen3-VL-8B          runs, host
speak, in its own voice    Qwen3-TTS 12Hz       Apache-2.0, ready
                           CustomVoice
move with no camera        Kimodo-SOMA + LoRA   wrapper unwired
lip-sync from its own      TalkingHead, MIT     unstudied
speech
render                     Godot                four checkouts</code></pre>
<p><strong>These two movements are the same avatar and opposite directions, and that is why the loop needs both motion sources.</strong> RFD 1170 called the split presence against authoring without noticing it is also first person against second. <code>be it</code> has a person in the room supplying everything; <code>make a friend</code> has nobody, so every input the person was providing has to come from a model instead.</p>
<pre><code>supplied by a person       supplied by a model

body motion, a webcam      Kimodo
what is in the room, the   nothing -- the friend sees only what it
same webcam                is shown
speech, a microphone       Qwen3-VL and Qwen3-TTS
intent                     the persona's manner</code></pre>
</section>
<section id="the-webcam-is-not-only-a-motion-source-and-each-head-is-its-own-compile" class="level2">
<h2 class="anchored" data-anchor-id="the-webcam-is-not-only-a-motion-source-and-each-head-is-its-own-compile">The webcam is not only a motion source, and each head is its own compile</h2>
<p>rf-detr covers three camera tasks – <strong>keypoints, segmentation and object detection</strong> – so the camera is an input to every movement and not just to <code>be it</code>.</p>
<p><strong>AN EARLIER REVISION SAID ONE HEF SERVES ALL THREE. THAT WAS WRONG.</strong> It reasoned from <code>gate_onnx_device.py</code> compiling “the backbone and projector” and from <code>rf-detr-cpp/scripts/</code> holding separate GGUF converters per head, and concluded one graph carried three tasks. The checkpoints say otherwise:</p>
<pre><code>checkpoint                patch   resolution   windows

keypoint-preview-xlarge     12       576          1
seg-nano                    12       312          1
seg-small                   12       384          2
large, detection            16       704          2</code></pre>
<p><strong>Different resolutions and different patch sizes are different graphs.</strong> A HEF is compiled for one fixed input shape, which is the whole premise of the device, so a 576-square keypoint HEF does not serve a 312-square segmenter. Each checkpoint is its own translate, its own calibration set and its own quantisation.</p>
<p>That matters because rung 4 is the expensive step. RFD 1165 measures QAFT at 32.5 GiB, which the desk’s 24 GiB cannot reach at any batch size, so every additional compiled model is another rented card rather than another afternoon.</p>
</section>
<section id="so-the-camera-feeds-all-four-movements-not-just-be-it-so-the-camera-feeds-all-four-movements-not-just-be-it" class="level2">
<h2 class="anchored" data-anchor-id="so-the-camera-feeds-all-four-movements-not-just-be-it-so-the-camera-feeds-all-four-movements-not-just-be-it">So the camera feeds all four movements, not just <code>be it</code>## So the camera feeds all four movements, not just <code>be it</code></h2>
<pre><code>movement        what the camera gives          through

make            a photograph of a person or    detection, then
                a garment becomes the source   segmentation
dress           show a real garment to the     segmentation, into
                camera and try it on           the slot it belongs
be it           a body tracked every frame     keypoints
make a friend   the friend sees what it is     detection
                shown</code></pre>
<p><strong>The <code>dress</code> row is the one worth noticing.</strong> RFD 1168 established that a try-on needs a boundary and a hole to fill. A webcam plus the segmentation head is a boundary from the real world, so a garment can enter the loop by being held up rather than by being modelled. Nothing in this workspace does that yet and the parts are all present.</p>
<p><strong>And <code>objects</code> stops being only a taxonomy problem.</strong> The detection head names things the nine worn slots do not cover, which is the bucket flagged above as unmodelled. Detection does not say what to do with a held prop, but it does say one is there, which is more than the taxonomy manages.</p>
</section>
<section id="everything-is-a-contour-and-one-of-them-is-a-projection-not-an-inference" class="level2">
<h2 class="anchored" data-anchor-id="everything-is-a-contour-and-one-of-them-is-a-projection-not-an-inference">Everything is a contour, and one of them is a projection not an inference</h2>
<p>A SOMA-X or ANNY body is vertices. What every stage above actually wants is an <strong>outline</strong>, and an outline is one representation:</p>
<pre><code>task            as a contour

pose            landmarks, a sparse contour
segmentation    a closed ordered ring
detection       that ring's extent
the body        the posed mesh, projected</code></pre>
<p><strong>The last row is not a model.</strong> Once a pose is fitted, the body outline is a render of geometry already held – deterministic, exact, no checkpoint, no calibration set and no rung to climb. Everything above it is an inference and that one is arithmetic.</p>
<p><strong>And it already exists.</strong> <code>pose-consensus/python/silhouette.py</code> is a differentiable soft silhouette, written under a docstring calling it “the route from pose to SHAPE” because keypoints give pose and not build: ANNY carries 11 phenotype parameters and 256 local changes, and no keypoint constrains any of them. CLAUDE.md already reports “photographic silhouette agreement” as a measured quantity, 0.776 against 0.825 in the precision table, so a silhouette is already this workspace’s currency for asking whether a body matches a pose.</p>
<p><strong>The garment is then the difference, and that is the useful part.</strong> The mesh silhouette is the body. What lies outside it and still belongs to the person is worn. A skirt, a coat and a hat all extend past the body outline, and that overhang is the garment boundary – derived from geometry rather than learned from labels, which is the corpus problem RFD 1168 could not solve any other way.</p>
<p>That inverts the <code>dress</code> movement. It does not need a segmenter that knows <code>topwear</code>; it needs a body it already has and the difference between that body and the picture.</p>
</section>
<section id="moge-supplies-both-halves-and-the-second-is-the-one-nobody-asked-for" class="level2">
<h2 class="anchored" data-anchor-id="moge-supplies-both-halves-and-the-second-is-the-one-nobody-asked-for">MoGe supplies both halves, and the second is the one nobody asked for</h2>
<p>The body contour comes from the mesh. The person’s outer edge has to come from the image, and <strong>MoGe answers that without a segmenter and without a taxonomy</strong> – a depth step separates a person from the wall behind them, and no labelled corpus is involved. That is the blocker RFD 1168 could not get past, sidestepped rather than solved.</p>
<p><strong>And it also hands over the camera.</strong> <code>silhouette.py</code> projects through a pinhole <code>Camera(width, height, fx, fy, cx, cy)</code>, and those numbers have to come from somewhere. MoGe v2’s <code>infer</code> returns <code>intrinsics</code> as a 3x3 alongside the point map, recovered from the picture by <code>recover_focal_shift</code>.</p>
<pre><code>what the loop needs        where it comes from

body outline               ANNY mesh, posed, through silhouette.py
person outline             MoGe depth, thresholded
the camera both project    MoGe intrinsics
through</code></pre>
<p><strong>Without that third row the first is guesswork.</strong> A projected silhouette is only as good as the camera it is projected through, and a wrong focal length yields a body outline of the wrong size in the right place – which subtracts into a garment boundary that is wrong everywhere and looks plausible. One model closing both gaps is worth more than the depth alone.</p>
<p><strong>The domain risk that applied elsewhere does not apply here.</strong> RFD 1166 records MoGe as unproven on illustration, which is why it was not a drop-in for See-Through’s depth stage. A webcam pointed at a person is photographs, which is exactly what MoGe was trained on. Same model, different use, and the caveat does not travel.</p>
<p>MoGe is MIT and already at rung 2 here: 885 nodes, 26 operators, with <code>Mod x4</code> outside <code>DEVICE_OPS</code> and unexplained. Nothing in this section needs it compiled – it runs on the host beside the fit.</p>
</section>
<section id="contour.py-which-is-the-first-piece-of-this-actually-built" class="level2">
<h2 class="anchored" data-anchor-id="contour.py-which-is-the-first-piece-of-this-actually-built"><code>contour.py</code>, which is the first piece of this actually built</h2>
<p><code>pose-consensus/python/contour.py</code> turns a mask into a fixed count of ordered points and back. Trace with Moore neighbours, keep the largest component, resample by arc length to N.</p>
<pre><code>shape    round trip IoU at 128 points

disc     0.966
square   0.969
L        0.959</code></pre>
<p><strong>The round trip is the test.</strong> Fill the contour back in and compare against the mask it came from; a contour that cannot rebuild its own mask is not describing it. The bound is 0.95.</p>
<p>Two negative controls, and the second is the useful one:</p>
<ul>
<li>shuffling the point order must break the round trip, or nothing has tested that the ordering means anything.</li>
<li><strong>two separate blobs must FAIL.</strong> One ring cannot hold two regions, which this document states as a limit rather than a defect, so the test asserts the limit still holds. If somebody later makes multi-region contours work, that test fails and sends them here to update the claim.</li>
</ul>
<p>numpy only, and nothing about it needs the accelerator. It is the smallest piece of the plan and it is done.</p>
</section>
<section id="multi-view-is-preferred-and-the-input-decides-whether-it-exists" class="level2">
<h2 class="anchored" data-anchor-id="multi-view-is-preferred-and-the-input-decides-whether-it-exists">Multi-view is preferred, and the input decides whether it exists</h2>
<p><strong>A webcam is multi-view by construction.</strong> Frames over time are views of one scene from a moving relationship, so the presence loop gets multi-view for free and should use it: “a person is scenery if they do not move” is a temporal statement, and a single frame cannot make it.</p>
<p><strong>An illustration has one view and there is no second one to take.</strong> A drawing is not a scene anybody can walk around. For that input, multi-view has to be <em>generated</em> – which is TRELLIS.2 or Pixal3D – and then verified back against what conditioned it, exactly the control rule CLAUDE.md states for poses.</p>
<pre><code>input          views available     what supplies geometry

webcam         many, over time     multi-view over frames
photograph     one, or a few       depends how many were taken
illustration   exactly one         generated views, then verified</code></pre>
<p><strong>That is the real split in this pipeline</strong>, and it is not depth against mapping. It is whether a second view exists.</p>
</section>
<section id="lingbot-map-is-the-one-that-is-licence-clean-and-it-was-never-checked" class="level2">
<h2 class="anchored" data-anchor-id="lingbot-map-is-the-one-that-is-licence-clean-and-it-was-never-checked">LingBot-Map is the one that is licence-clean, and it was never checked</h2>
<p>RFD 1050 abandoned it on scope and left two blockers open rather than answered: the parameter count, and <strong>“License | RFD 1028 gates the ship”</strong>. Nobody had looked. Looking resolves it in the good direction.</p>
<pre><code>Robbyant/lingbot-map      Apache-2.0, code
robbyant/lingbot-map      Apache-2.0, WEIGHTS, stated on the card
Robbyant/lingbot-depth    Apache-2.0
Robbyant/lingbot-world    Apache-2.0</code></pre>
<p>That is the pattern from Kimodo and See-Through inverted. There the code was permissive and the weights were not; here the card says the weights are Apache-2.0 in as many words.</p>
<p><strong>And it is the right shape.</strong> Streaming feed-forward reconstruction from video or an image sequence, emitting camera poses, metric scale and dense point clouds – roughly 20 fps at 518 by 378, over sequences past ten thousand frames.</p>
<pre><code>what the loop needs        MoGe            LingBot-Map

person against scene       depth step      the static map itself
camera                     intrinsics      full poses
scale                      affine          METRIC
views                      one             many, which is preferred</code></pre>
<p><strong>Taken, and placed.</strong> It answers the mapping role better than MoGe and better than Metric3D, which needed the camera it was supposed to supply. Forked to <code>weftspun/lingbot-map</code> and pinned at <code>1740f18</code> in the manifest at <code>3-interactor/lingbot-map-upstream</code>.</p>
<p>MoGe is not displaced. It keeps the single-image case, where no sequence exists and no map can be built – which is every illustration.</p>
</section>
<section id="depth_term.py-is-written-against-marigold-which-is-now-blocked" class="level2">
<h2 class="anchored" data-anchor-id="depth_term.py-is-written-against-marigold-which-is-now-blocked"><code>depth_term.py</code> is written against Marigold, which is now blocked</h2>
<p><code>pose-consensus/python/depth_term.py</code> is the forward that pairs with a learned depth inverse, and it names Marigold throughout: the docstring, the pipeline table, and the affine-alignment rationale. RFD 1166 blocklisted See-Through’s checkpoints, and the depth one is a Marigold derivative under OpenRAIL++-M.</p>
<p><strong>The code does not break.</strong> <code>depth_loss</code> takes <code>target_depth</code> as a tensor and nothing imports Marigold, so the source is swappable. What is stale is the reasoning, and it is stale in a way that matters.</p>
<p><strong>Why depth is the right third opinion is measured, not asserted.</strong> The silhouette scores 0.849 on a depth-plus-scale change, which is exactly its own self-IoU floor – perfectly blind. That is the strongest independence argument anywhere in this workspace:</p>
<pre><code>LBFGS vertex   sees 3D with correspondence  blind to whether the
                                            correspondence is right
silhouette     sees the outline             blind to depth and interior
depth          sees the interior            blind to absolute scale</code></pre>
</section>
<section id="swapping-marigold-for-moge-loses-independence-and-that-is-the-cost" class="level2">
<h2 class="anchored" data-anchor-id="swapping-marigold-for-moge-loses-independence-and-that-is-the-cost">Swapping Marigold for MoGe loses independence, and that is the cost</h2>
<p>Marigold is Stable-Diffusion-derived. rf-detr’s backbone and MoGe are both DINOv2 descendants. <strong>A second opinion is worth having only if it fails differently</strong>, which is <code>silhouette.py</code>’s own stated test, and two models from one lineage can fail together in a way an SD model and a DETR could not.</p>
<p>So taking MoGe for this slot keeps the depth signal and spends the independence. That is a real cost and it is being paid knowingly rather than overlooked.</p>
<p><strong>What would restore it, under a clean licence:</strong></p>
<pre><code>ZoeDepth              MIT, metric, BEiT backbone
DPT-BEiT-Large        MIT, relative, BEiT backbone
DPT-hybrid-MiDaS      Apache-2.0, ViT and ResNet
lingbot-map           Apache-2.0, but needs a sequence
classical MVS         OpenCV Apache-2.0, no learned prior at all</code></pre>
<p>Every row is off the DINOv2 lineage. None is chosen here, because the single-view decision was about the primary and not about the check.</p>
<p><strong>And the third opinion’s blind spot moved.</strong> The table above lists depth as blind to absolute scale, which was true of Marigold and of MoGe-1. MoGe-2 and MoGe-3 are metric, so that entry is wrong for the model now in the slot. The trio may still cover, and nobody has re-derived it.</p>
<p><strong><code>align_affine</code> needs a decision it has not been given.</strong> It solves an <code>(a, b)</code> alignment inside the objective because Marigold was affine-invariant. Against a metric source that alignment is optional, and leaving it on will absorb genuine scale error instead of reporting it – blinding the term to the axis metric depth was bought for.</p>
</section>
<section id="the-trio-re-derived-for-metric-depth" class="level2">
<h2 class="anchored" data-anchor-id="the-trio-re-derived-for-metric-depth">The trio re-derived for metric depth</h2>
<p>The covering argument was written when depth was affine-invariant. It still holds, and it holds better. Restated with the blind spots as they now are:</p>
<pre><code>term            correspondence   sees                      blind to

LBFGS vertex    REQUIRED         everything, precisely     whether the
                                                           correspondence
                                                           is right
silhouette      none             the outline, per view     depth, and the
                                                           interior
metric depth    none             the visible surface in    whatever that
                                 metres, scale included    surface occludes</code></pre>
<p><strong>What improved is not the depth term, it is where absolute scale comes from.</strong> Under affine depth, scale was visible to exactly one term – the LBFGS vertex fit – and only when its correspondence was right. The one quantity nothing else could see was sourced through the least trustworthy path in the system. Metric depth sees scale with no correspondence at all, so scale moves from single-sourced-through-the- weak-term to seen by two terms that fail differently.</p>
<p><strong>No new gap opens.</strong> Metric depth is blind to what the visible surface hides, which was equally true of the affine version, and multi-view covers it: <code>sphere_hammersley_sequence</code> is already mandated, and a silhouette from behind constrains the back that a front depth map cannot.</p>
<p><strong>The overlap with the silhouette is not redundancy.</strong> Both now constrain build, which is what the silhouette was introduced for – ANNY carries 11 phenotype parameters and no keypoint touches them. They constrain it differently: a body correct in outline but too thick front-to-back moves the depth field and not the silhouette, and a body of right thickness and wrong width moves both.</p>
</section>
<section id="align_affine-must-not-stay-as-it-is-and-off-is-not-the-answer-either" class="level2">
<h2 class="anchored" data-anchor-id="align_affine-must-not-stay-as-it-is-and-off-is-not-the-answer-either"><code>align_affine</code> must not stay as it is, and off is not the answer either</h2>
<pre><code>left on         the residual is scale-invariant, so the term cannot
                see the one thing metric depth was taken for
turned off      the term reports scale, and MoGe's own metric bias
                becomes a fitting force -- a five per cent under-read
                shrinks the body five per cent</code></pre>
<p>Both are wrong, and the reason they are both wrong is that <strong>one scalar is being asked to carry two residuals.</strong></p>
<p><strong>Separate them.</strong> Keep the alignment, so the shape residual stays scale-invariant and robust, and <strong>report <code>a</code> rather than discarding it</strong>. A fitted <code>a</code> far from 1 is the scale disagreement, stated instead of absorbed. Scale can then be constrained by its own term with its own weight, or simply watched.</p>
<p>Folding it into the returned scalar is a silent skip: the loss goes down because the alignment moved, and that reads exactly like a fit improving. <code>coverage_ok</code> exists in the same file for the same class of failure, which is the precedent for handling this one the same way.</p>
<p><strong>What is still unmeasured, and the number that decides the weight</strong>: nobody has measured MoGe-3’s metric accuracy against a rendered depth buffer of known geometry. Until that exists, any weight on a scale term is a guess – and RFD 1170’s rendered walk is exactly the apparatus that would produce it, since a Mitsuba render has known depth by construction.</p>
</section>
<section id="lingbot-depth-was-checked-and-is-not-a-candidate" class="level2">
<h2 class="anchored" data-anchor-id="lingbot-depth-was-checked-and-is-not-a-candidate">LingBot-Depth was checked and is not a candidate</h2>
<p>Same family, Apache-2.0, ViT-L/14. It takes RGB <strong>and</strong> a sparse or noisy depth map <strong>and</strong> camera intrinsics, and returns refined depth. It is completion rather than estimation, so it presupposes both things the single-view slot exists to produce. It belongs downstream of LingBot-Map, which emits exactly those inputs, and nowhere near the start of a chain.</p>
</section>
<section id="depth_term.py-is-written-against-marigold-which-is-now-blocked-1" class="level2">
<h2 class="anchored" data-anchor-id="depth_term.py-is-written-against-marigold-which-is-now-blocked-1"><code>depth_term.py</code> is written against Marigold, which is now blocked</h2>
<p><code>pose-consensus/python/depth_term.py</code> is the forward that pairs with a learned depth inverse, and it names Marigold in its docstring, its pipeline table and its affine-alignment rationale. RFD 1166 blocklisted See-Through’s checkpoints, and the depth one is a Marigold derivative.</p>
<p><strong>The code does not break.</strong> <code>depth_loss</code> takes <code>target_depth</code> as a tensor and nothing imports Marigold, so the source is swappable. What is stale is the reasoning around it.</p>
<p><strong>Why depth is the right third opinion is measured, not asserted</strong>, and that part survives any swap. The silhouette scores 0.849 on a depth-plus-scale change, which is exactly its own self-IoU floor – perfectly blind:</p>
<pre><code>LBFGS vertex   sees 3D with correspondence  blind to whether the
                                            correspondence is right
silhouette     sees the outline             blind to depth, interior
depth          sees the interior            blind to absolute scale</code></pre>
</section>
<section id="taking-moge-for-that-slot-spends-the-independence-knowingly" class="level2">
<h2 class="anchored" data-anchor-id="taking-moge-for-that-slot-spends-the-independence-knowingly">Taking MoGe for that slot spends the independence, knowingly</h2>
<p>Marigold is Stable-Diffusion-derived. rf-detr’s backbone and MoGe are both DINOv2 descendants. <strong>A second opinion is worth having only if it fails differently</strong> – <code>silhouette.py</code>’s own stated test – and two models from one lineage can fail together where an SD model and a DETR could not.</p>
<p>So the depth signal is kept and the independence is spent. Recorded as a cost rather than overlooked. What would restore it, all off the DINOv2 lineage and all licence-clean:</p>
<pre><code>ZoeDepth           MIT, metric, BEiT
DPT-BEiT-Large     MIT, relative, BEiT
DPT-hybrid-MiDaS   Apache-2.0, ViT and ResNet
lingbot-map        Apache-2.0, needs a sequence
classical MVS      OpenCV Apache-2.0, no learned prior at all</code></pre>
<p>None is chosen. The single-view decision was about the primary, not about the check.</p>
<p><strong>Two things the metric switch breaks that nobody has fixed.</strong> The table above lists depth as blind to absolute scale, which held for Marigold and MoGe-1 and does not hold for MoGe-2 or MoGe-3. The trio may still cover and nobody has re-derived it. And <code>align_affine</code> solves an <code>(a, b)</code> alignment inside the objective because Marigold was affine-invariant – against a metric source that is optional, and leaving it on absorbs genuine scale error instead of reporting it, blinding the term to the axis metric depth was bought for.</p>
</section>
<section id="lingbot-depth-was-checked-and-is-not-a-candidate-1" class="level2">
<h2 class="anchored" data-anchor-id="lingbot-depth-was-checked-and-is-not-a-candidate-1">LingBot-Depth was checked and is not a candidate</h2>
<p>Same family, Apache-2.0, ViT-L/14. It takes RGB <strong>and</strong> a sparse or noisy depth map <strong>and</strong> intrinsics, returning refined depth. Completion rather than estimation, so it presupposes both things the single-view slot exists to produce. It belongs downstream of LingBot-Map, which emits exactly those inputs.</p>
</section>
<section id="single-view-moge-3-is-taken-and-moge-2-stays-for-pixal3d" class="level2">
<h2 class="anchored" data-anchor-id="single-view-moge-3-is-taken-and-moge-2-stays-for-pixal3d">Single view: MoGe-3 is taken, and MoGe-2 stays for Pixal3D</h2>
<pre><code>checkpoint          licence   gives                        kept for

moge-3-vitl/vitg    MIT       metric points, depth,        new work
                              normals, FOV
moge-2-vitl         MIT       the same, one generation     Pixal3D
                              older
moge-vitl (v1)      MIT       AFFINE points and FOV        nothing</code></pre>
<p><strong>Two corrections fall out of choosing.</strong></p>
<p><strong>MoGe is not affine-invariant, and this document said it was.</strong> That was read off v1. Versions 2 and 3 return <strong>metric</strong> point maps, depth, normal maps and camera FOV, and the checkout at <code>3-interactor/moge-upstream</code> already carries <code>v1.py</code>, <code>v2.py</code> and <code>v3.py</code>. MoGe-3 landed 2026-08-18 under MIT, which is newer than most of the field discussed above.</p>
<p><strong>Pixal3D pins v2, not v1.</strong> <code>pixal3d-upstream/app.py:68</code> sets <code>MOGE_MODEL_NAME = "Ruicheng/moge-2-vitl"</code> and imports <code>moge.model.v2.MoGeModel</code>. So the version worth retaining for compatibility is the second, and nothing found here depends on the first.</p>
<p><strong>One checkout serves all of it</strong>, because the versions are modules in one repository and differ by checkpoint. No manifest change is needed.</p>
</section>
<section id="the-rung-2-export-describes-the-wrong-model-now" class="level2">
<h2 class="anchored" data-anchor-id="the-rung-2-export-describes-the-wrong-model-now">The rung-2 export describes the wrong model now</h2>
<p><code>moge-upstream/export_device_half.py</code> exports <code>dinov2_vitb14</code> with four intermediate layers, which is <strong>v1’s</strong> encoder. RFD 1167 records MoGe at rung 1 and 2 on that basis: 885 nodes, 26 operators, <code>Mod x4</code> outside <code>DEVICE_OPS</code>.</p>
<p>That measurement is still true and it is true about a model this workspace has now decided not to use. MoGe-2 and MoGe-3 are ViT-L, so the graph is larger and the operator census has to be redone rather than assumed to carry over. <strong>The rung entry stands with that caveat rather than being deleted</strong>, because the number was measured and deleting it would lose the fact that the family exports cleanly at all.</p>
</section>
<section id="the-walk-video-can-be-rendered-which-makes-the-error-measurable" class="level2">
<h2 class="anchored" data-anchor-id="the-walk-video-can-be-rendered-which-makes-the-error-measurable">The walk video can be rendered, which makes the error measurable</h2>
<p>A walk video is a camera path, and this workspace already renders camera paths deterministically. <strong>Mitsuba 3 can produce the input LingBot-Map consumes</strong>, from geometry already held.</p>
<p>That is worth more than convenience, because it turns an unmeasurable stage into a measured one:</p>
<pre><code>render a walk of KNOWN geometry, with a KNOWN camera path
reconstruct it with LingBot-Map
the difference is the reconstruction error, exactly</code></pre>
<p>Ground truth is not estimated here, it is the input. RFD 1170 already makes Mitsuba the reference renderer against Godot; this is the same instrument pointed at a different consumer, and CLAUDE.md already fixes the camera sequence, so <code>sphere_hammersley_sequence</code> is the path unless somebody argues otherwise.</p>
<p><strong>It is also constructed synthetic by CLAUDE.md’s definition</strong> – rendered deterministically from assets held here, labels true by construction, the same seed reproducing the corpus. Not generated data, so none of the four conditions apply.</p>
<p><strong>The domain gap is the honest caveat.</strong> LingBot-Map is trained on real rooms walked through by real cameras. A Mitsuba walk around one character is neither, and a model measured only on renders has been measured on renders. Use it to bound the error and to catch regressions, not to claim the number transfers to a webcam in a room.</p>
</section>
<section id="mapping-models-were-reconsidered-and-the-field-is-licence-hostile" class="level2">
<h2 class="anchored" data-anchor-id="mapping-models-were-reconsidered-and-the-field-is-licence-hostile">Mapping models were reconsidered, and the field is licence-hostile</h2>
<p>RFDs 1051 and 1052 abandoned WorldMirror 2.0 and TripoSplat when RFD 1064 turned toward character concepts and away from scene reconstruction. <strong>That reason has inverted</strong> – the presence loop makes scene reconstruction a character tool, because the static scene is what a moving person is separated from. So the abandonment was revisited.</p>
<p>The models are not available:</p>
<pre><code>tencent/HunyuanWorld-Mirror   tencent-hunyuanworld-mirror-community,
                              the same family as Hunyuan3D-Part,
                              blocklisted for excluding the EU, UK
                              and South Korea
facebook/VGGT-1B              CC-BY-NC-4.0, non-commercial
naver/dust3r                  CC-BY-NC-SA, non-commercial AND
                              share-alike, blocked twice over</code></pre>
<p><strong>Every learned multi-view reconstructor reachable from here is non-commercial or territory-restricted.</strong> That is worth recording as a property of the field rather than as three separate disappointments, and it is probably why RFD 1064’s pivot cost less than it looked like it would.</p>
<p><strong>What is licence-clean is classical.</strong> OpenCV is Apache-2.0 and COLMAP is new BSD, with the caveat COLMAP states itself: its dependencies are separately licensed and building against them can affect the result. For a fixed webcam the classical route is also the simpler one – accumulating a static scene over frames is arithmetic, not a model, and it needs no checkpoint, no corpus and no licence at all.</p>
</section>
<section id="metric3d-v2-was-assessed-as-a-fallback-and-it-is-not-one" class="level2">
<h2 class="anchored" data-anchor-id="metric3d-v2-was-assessed-as-a-fallback-and-it-is-not-one">Metric3D v2 was assessed as a fallback, and it is not one</h2>
<p>Proposed as a substitute for MoGe. It is not a substitute, and the reason is the half that was not being thought about.</p>
<pre><code>MoGe                          Metric3D v2

affine-invariant depth        METRIC depth, which is better
RECOVERS intrinsics           CONSUMES intrinsics
MIT, weights and code         code BSD-2, weights unstated
exported here, 885 nodes      ONNX published, CC0 claimed</code></pre>
<p><strong>It needs the camera it was meant to replace.</strong> <code>hubconf.py</code> takes <code>intrinsic = [fx, fy, cx, cy]</code> and line 197 computes <code>canonical_to_real_scale = intrinsic[0] / 1000.0</code>, dividing by the canonical camera’s focal length. The depth is only metric because the focal length was supplied. Swap MoGe out for it and the loop loses the camera <code>silhouette.py</code> projects the body mesh through, which is the gap MoGe was closing that nobody had asked it to.</p>
<p><strong>So they chain rather than compete.</strong> MoGe recovers the intrinsics, Metric3D turns them into metric depth. That is a better arrangement than either alone and it is two models rather than one, which is a cost to weigh rather than a free upgrade.</p>
<p><strong>The licence needs care, and in an unusual direction.</strong> The code is BSD 2-Clause, which is clean. The weights on <code>JUGGHM/Metric3D</code> state no licence at all. The ONNX re-exports at <code>onnx-community/metric3d-vit-*</code> declare <strong>CC0-1.0</strong> – a third party dedicating to the public domain weights whose author granted nothing. That is the See-Through problem inverted: there a downstream party could not relicense restrictions away, and here a downstream party cannot grant rights it was never given. A CC0 label over unlicensed weights is not a licence.</p>
<p><strong>What is genuinely attractive is the export.</strong> <code>onnx/model.onnx</code> and <code>model_fp16.onnx</code> are published for three sizes, so rung 1 costs a download rather than a script. If the licence were resolved this would be the cheapest operator census in the field.</p>
</section>
<section id="the-hazard-in-doing-this-which-is-not-small" class="level2">
<h2 class="anchored" data-anchor-id="the-hazard-in-doing-this-which-is-not-small">The hazard in doing this, which is not small</h2>
<p><strong>Spending the silhouette as an output spends it as a check.</strong> <code>silhouette.py</code> is valuable precisely because it has NO correspondence: its own docstring says a vertex mislabelled as its neighbour does not move the outline, so it fails differently from the LBFGS vertex fit and catches the candy-wrapper failure that fit cannot see.</p>
<p>If the projected contour becomes the segmentation, that independence is gone. The outline stops being a second opinion about whether the pose is right and becomes an assumption that it is. <strong>A wrong pose then produces a confidently wrong garment boundary with nothing left to notice</strong>, and the failure looks like a clothing bug rather than a fitting one.</p>
<p>So the two uses have to stay separated: fit the pose, check it against the image silhouette, and only then use the mesh contour as geometry. Using one silhouette for both is the thing to avoid.</p>
</section>
<section id="what-the-mesh-contour-does-not-give" class="level2">
<h2 class="anchored" data-anchor-id="what-the-mesh-contour-does-not-give">What the mesh contour does not give</h2>
<p><strong>Hair is not body.</strong> <code>front hair</code> and <code>back hair</code> are two of the taxonomy’s 23 parts and neither is in a body mesh, so the outline excludes exactly the parts RFD 1168 spends its argument on.</p>
<p><strong>A single ring cannot hold a hole or a split</strong>, which is the bound already stated for contour segmentation and applies here unchanged.</p>
<p><strong>Scene objects are not in the mesh.</strong> The taxonomy’s <code>objects</code> bucket is outside this entirely, and detection-as-contour would be answering about things no rig knows about.</p>
</section>
<section id="decided-keep-keypoints-and-segmentation-drop-detection" class="level2">
<h2 class="anchored" data-anchor-id="decided-keep-keypoints-and-segmentation-drop-detection">Decided: keep keypoints and segmentation, drop detection</h2>
<p>Two compiles, not three. The reason is not that keypoints can kludge a box, though they can.</p>
<p><strong>RF-DETR-Seg is a DETR, and a DETR’s queries carry a class and a box alongside the mask.</strong> Instance segmentation is not a mask floating free – each query emits <code>pred_logits</code>, <code>pred_boxes</code> and its mask together, because that is how the architecture separates instances at all. So the segmentation checkpoint already answers “what is there and where”, which is the whole of what a detection checkpoint would add.</p>
<pre><code>task            served by                    costs

pose            keypoint-preview-xlarge      its own HEF
segmentation    a seg checkpoint             its own HEF
detection       the seg checkpoint's boxes   nothing</code></pre>
<p><strong>Dropping detection therefore costs nothing rather than costing accuracy</strong>, which is a better position than the kludge argument reached. The kludge – deriving a coarse box from joints – stays available for the case where only the keypoint model is compiled, and it is a fallback rather than the plan.</p>
<p><strong>Keypoints cannot be dropped and segmentation should not be.</strong> Keypoints are <code>be it</code>, they are the only model at rung 3, and nothing else tracks a body every frame. Segmentation is <code>dress</code>: RFD 1168 needs a boundary before it needs anything else, and a garment held up to a webcam is a boundary from the real world.</p>
<p><strong>The order is settled by what is already measured.</strong> The keypoint model is at rung 3 and a seg checkpoint has never been exported here, so the second compile waits on the first reaching rung 5 – and on a card that can run QAFT.</p>
</section>
<section id="express-the-surviving-two-as-keypoints-because-keypoints-are-fixed-shape" class="level2">
<h2 class="anchored" data-anchor-id="express-the-surviving-two-as-keypoints-because-keypoints-are-fixed-shape">Express the surviving two as keypoints, because keypoints are fixed-shape</h2>
<p>Having dropped detection, the remaining question is what shape the segmentation output takes. <strong>A keypoint head has a fixed-shape output by construction, and fixed shape is the single thing the compiler demands.</strong></p>
<pre><code>task            as its own head              as keypoints

detection       boxes, a variable-length     N centre points, fixed
                list, then NMS
segmentation    a mask, then a per-pixel     M contour points in
                argmax or run-length          order, fixed
pose            joints                       joints</code></pre>
<p><strong>The head-shaped versions reach for operators RFD 1131 refuses.</strong> A detection head wants <code>TopK</code> for query selection and <code>NonMaxSuppression</code>, both in <code>KNOWN_BLOCKERS</code>, and the second is there specifically for a data-dependent output shape. A mask head wants <code>NonZero</code> or a scatter. A head that regresses a fixed count of coordinates wants none of them.</p>
<p>That is the argument. Not that one head is tidier than three, but that two of the three are shaped like the thing the accelerator cannot do, and the third is shaped like the thing it can.</p>
<p><strong>The technique is established rather than invented here.</strong> Detection as centre points and segmentation as an ordered contour are both published families, and this workspace would be choosing them for a reason the papers were not written for.</p>
<p><strong>It also suits the deployment rule.</strong> A contour is coordinates, which is data, and CLAUDE.md’s glTF constraint is that an export carries pure data. A mask is pixels and needs somewhere to live.</p>
</section>
<section id="what-the-unification-costs-which-is-not-nothing" class="level2">
<h2 class="anchored" data-anchor-id="what-the-unification-costs-which-is-not-nothing">What the unification costs, which is not nothing</h2>
<p><strong>A fixed contour cannot express a hole or a split.</strong> A garment occluded into two pieces by an arm is two regions, and an ordered ring of M points is one. That is a real loss and it lands on exactly the case a try-on produces most often.</p>
<p><strong>Fine boundaries get worse.</strong> M points around a silhouette is a polygon, and hair, lace or a fringe is not a polygon at any M this would use. RFD 1168 already bounds the fine parts out on latent resolution; this bounds them out again for a different reason, and two independent bounds agreeing is worth more than either alone.</p>
<p><strong>A kludge is available before any of this.</strong> If only the keypoint head is compiled, a coarse box follows from the joints and a coarse region per limb follows from the box. It would place <code>topwear</code> roughly where a torso is. That is enough for RFD 1168’s step 1, which only tests the plumbing, and nowhere near enough to cut a garment out of a photograph. Take it to close the loop early, not as the answer.</p>
<p><strong>Only one row differs in hardware terms</strong>, and it is the important one: <code>be it</code> needs rf-detr running every frame on the accelerator, and <code>make a friend</code> does not need the camera at all. The friend is the cheaper loop to build and the one that runs without the device.</p>
<p><strong>The division was not chosen.</strong> rf-detr is the only model the Dataflow Compiler has accepted, and it is the one that must run every frame with low latency. Everything with a voice in it is autoregressive and cannot compile. So the device took the body and the host took the speech because that is what the graphs allow, and it happens to be the right split — continuous tracking on the accelerator, bursty turn-taking on the host, which tolerates delay.</p>
</section>
<section id="the-five-stages-with-no-model" class="level2">
<h2 class="anchored" data-anchor-id="the-five-stages-with-no-model">The five stages with no model</h2>
<p>Naming these is most of the value of reorganising the document.</p>
<ol type="1">
<li><strong>Keypoints to a SOMA pose.</strong> rf-detr emits keypoints; ANNY needs a pose. <code>anny_from_soma</code> exists as a topology, and RFD 1122’s wholebody gap is the distance between them. Nothing fills it.</li>
<li><strong>A segmenter that knows these classes.</strong> rf-detr-seg is COCO-classed and knows <code>person</code>, not <code>topwear</code>. RFD 1168 records that corrupt-clean render pairs would generate the corpus.</li>
<li><strong>Audio to visemes.</strong> RFD 1170 found the Space ships this as two minified vendor modules and a <code>.bin</code> with no stated licence, so it is the part to replace rather than reuse — and whether ANNY even carries viseme morph targets is unchecked.</li>
<li><strong>A garment representation.</strong> Every row above treats a garment as pixels or voxels. Nothing here says what a <code>topwear</code> <em>is</em> as a shippable asset, and glTF’s pure-data rule constrains the answer.</li>
<li><strong>A persona.</strong> <code>make a friend</code> needs the character to have a manner – what it knows, how it speaks, what it will not say – and nothing in this workspace holds one. A system prompt is the cheap version and a LoRA over Qwen3-VL is the durable one, which is EditScore’s arrangement pointed at personality instead of judgement.</li>
</ol>
</section>
<section id="what-is-measured-against-what" class="level2">
<h2 class="anchored" data-anchor-id="what-is-measured-against-what">What is measured against what</h2>
<p>Three oracles, and they are the reason to believe any of it:</p>
<pre><code>fast thing            reference             the check

rf-detr C++           PyTorch, gen_reference  .bin diff per tensor
Godot                 Mitsuba 3               per pixel, per view,
                                              on sphere_hammersley
a compiled HEF        the same graph at       to be established
                      full precision</code></pre>
<p><strong>The third row is empty and that is the gap that matters most.</strong> Nothing yet compares a HEF’s output against the model it came from, so <code>compare_precision.py</code> in <code>rf-detr-cpp</code> is the closest thing and it compares precisions rather than devices. A quantised graph that runs is not a graph that is right.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/weftspun\.github\.io\/request-for-discussion");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Serials are OID arcs under the 66606 PEN and are never reused.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/rfd/1171-the-presence-loop-and-every-role-in-it/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/rfd/1171-the-presence-loop-and-every-role-in-it/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/weftspun/request-for-discussion">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>