<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>details – Taskweft — Manuals</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5a10fc84a7bff526434d52200a729576.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-f36f388c175c695e587c9d92b6af4f92.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5a10fc84a7bff526434d52200a729576.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9dc8f7b0063e587a5bbf917ac285fb0e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-dd645bdd3be9d8713d016f89b66f7356.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-9dc8f7b0063e587a5bbf917ac285fb0e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Taskweft — Manuals</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../pages/rfd.html"> 
<span class="menu-text">RFDs</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-flight-levels" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Flight Levels</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-flight-levels">    
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-1-operations.html">
 <span class="dropdown-text">L1 · Operations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-2-coordination.html">
 <span class="dropdown-text">L2 · Coordination</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/flight-level-3-strategy.html">
 <span class="dropdown-text">L3 · Strategy</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../pages/logbook.html"> 
<span class="menu-text">Logbook</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../pages/serials.html"> 
<span class="menu-text">Register</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#rfd-1121-details-the-coverage-table-the-rebuild-pipeline-and-the-ledger-protocol" id="toc-rfd-1121-details-the-coverage-table-the-rebuild-pipeline-and-the-ledger-protocol" class="nav-link active" data-scroll-target="#rfd-1121-details-the-coverage-table-the-rebuild-pipeline-and-the-ledger-protocol">RFD 1121 details: the coverage table, the rebuild pipeline, and the ledger protocol</a>
  <ul class="collapse">
  <li><a href="#what-hm08-actually-covers" id="toc-what-hm08-actually-covers" class="nav-link" data-scroll-target="#what-hm08-actually-covers">What hm08 actually covers</a></li>
  <li><a href="#the-correction-the-mesh-is-19158-vertices-and-the-joint-cubes-come-in-two-ranges" id="toc-the-correction-the-mesh-is-19158-vertices-and-the-joint-cubes-come-in-two-ranges" class="nav-link" data-scroll-target="#the-correction-the-mesh-is-19158-vertices-and-the-joint-cubes-come-in-two-ranges">The correction: the mesh is 19,158 vertices, and the joint cubes come in two ranges</a></li>
  <li><a href="#two-more-corrections-and-the-claim-that-was-true-all-along" id="toc-two-more-corrections-and-the-claim-that-was-true-all-along" class="nav-link" data-scroll-target="#two-more-corrections-and-the-claim-that-was-true-all-along">Two more corrections, and the claim that was true all along</a></li>
  <li><a href="#the-state-of-that-repository" id="toc-the-state-of-that-repository" class="nav-link" data-scroll-target="#the-state-of-that-repository">The state of that repository</a></li>
  <li><a href="#the-24-tags-against-those-groups" id="toc-the-24-tags-against-those-groups" class="nav-link" data-scroll-target="#the-24-tags-against-those-groups">The 24 tags, against those groups</a></li>
  <li><a href="#the-basemesh-vertex-order-is-frozen" id="toc-the-basemesh-vertex-order-is-frozen" class="nav-link" data-scroll-target="#the-basemesh-vertex-order-is-frozen">The basemesh vertex order is frozen</a>
  <ul class="collapse">
  <li><a href="#the-count-gate-was-decoration" id="toc-the-count-gate-was-decoration" class="nav-link" data-scroll-target="#the-count-gate-was-decoration">The count gate was decoration</a></li>
  </ul></li>
  <li><a href="#why-the-depth-order-needs-no-inpainting" id="toc-why-the-depth-order-needs-no-inpainting" class="nav-link" data-scroll-target="#why-the-depth-order-needs-no-inpainting">Why the depth order needs no inpainting</a></li>
  <li><a href="#the-rebuild-stage-by-stage" id="toc-the-rebuild-stage-by-stage" class="nav-link" data-scroll-target="#the-rebuild-stage-by-stage">The rebuild, stage by stage</a></li>
  <li><a href="#what-the-corpus-render-writes" id="toc-what-the-corpus-render-writes" class="nav-link" data-scroll-target="#what-the-corpus-render-writes">What the corpus render writes</a>
  <ul class="collapse">
  <li><a href="#the-keypoints-are-true-by-construction" id="toc-the-keypoints-are-true-by-construction" class="nav-link" data-scroll-target="#the-keypoints-are-true-by-construction">The keypoints are true by construction</a></li>
  <li><a href="#the-topology-must-be-pinned-or-the-keypoints-land-on-the-wrong-body" id="toc-the-topology-must-be-pinned-or-the-keypoints-land-on-the-wrong-body" class="nav-link" data-scroll-target="#the-topology-must-be-pinned-or-the-keypoints-land-on-the-wrong-body">The topology must be pinned, or the keypoints land on the wrong body</a></li>
  </ul></li>
  <li><a href="#gates-each-with-a-negative-control" id="toc-gates-each-with-a-negative-control" class="nav-link" data-scroll-target="#gates-each-with-a-negative-control">Gates, each with a negative control</a></li>
  <li><a href="#the-ledger-protocol" id="toc-the-ledger-protocol" class="nav-link" data-scroll-target="#the-ledger-protocol">The ledger protocol</a>
  <ul class="collapse">
  <li><a href="#where-it-lives" id="toc-where-it-lives" class="nav-link" data-scroll-target="#where-it-lives">Where it lives</a></li>
  <li><a href="#the-files" id="toc-the-files" class="nav-link" data-scroll-target="#the-files">The files</a></li>
  <li><a href="#the-row" id="toc-the-row" class="nav-link" data-scroll-target="#the-row">The row</a></li>
  <li><a href="#the-five-kinds" id="toc-the-five-kinds" class="nav-link" data-scroll-target="#the-five-kinds">The five kinds</a></li>
  <li><a href="#the-rules-a-linter-enforces" id="toc-the-rules-a-linter-enforces" class="nav-link" data-scroll-target="#the-rules-a-linter-enforces">The rules a linter enforces</a></li>
  <li><a href="#concurrency" id="toc-concurrency" class="nav-link" data-scroll-target="#concurrency">Concurrency</a></li>
  <li><a href="#the-five-negative-controls" id="toc-the-five-negative-controls" class="nav-link" data-scroll-target="#the-five-negative-controls">The five negative controls</a></li>
  </ul></li>
  <li><a href="#garments-come-from-geometry-too-and-cloth-fit-is-how-they-get-there" id="toc-garments-come-from-geometry-too-and-cloth-fit-is-how-they-get-there" class="nav-link" data-scroll-target="#garments-come-from-geometry-too-and-cloth-fit-is-how-they-get-there">Garments come from geometry too, and cloth-fit is how they get there</a>
  <ul class="collapse">
  <li><a href="#the-tag-count-in-this-document-does-not-match-the-code" id="toc-the-tag-count-in-this-document-does-not-match-the-code" class="nav-link" data-scroll-target="#the-tag-count-in-this-document-does-not-match-the-code">The tag count in this document does not match the code</a></li>
  <li><a href="#the-quads-exist-and-they-are-discarded-at-annys-python-boundary" id="toc-the-quads-exist-and-they-are-discarded-at-annys-python-boundary" class="nav-link" data-scroll-target="#the-quads-exist-and-they-are-discarded-at-annys-python-boundary">The quads exist, and they are discarded at ANNY’s Python boundary</a></li>
  <li><a href="#polyfem-does-not-export-to-onnx-and-the-corpus-path-does-not-want-it-to" id="toc-polyfem-does-not-export-to-onnx-and-the-corpus-path-does-not-want-it-to" class="nav-link" data-scroll-target="#polyfem-does-not-export-to-onnx-and-the-corpus-path-does-not-want-it-to">PolyFEM does not export to ONNX, and the corpus path does not want it to</a></li>
  <li><a href="#a-proxy-is-a-form-and-a-form-is-free" id="toc-a-proxy-is-a-form-and-a-form-is-free" class="nav-link" data-scroll-target="#a-proxy-is-a-form-and-a-form-is-free">A proxy is a form, and a form is free</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/rfd/1121-layers-from-geometry-and-the-missing-categories/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/rfd/1121-layers-from-geometry-and-the-missing-categories/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>





<section id="rfd-1121-details-the-coverage-table-the-rebuild-pipeline-and-the-ledger-protocol" class="level1">
<h1>RFD 1121 details: the coverage table, the rebuild pipeline, and the ledger protocol</h1>
<section id="what-hm08-actually-covers" class="level2">
<h2 class="anchored" data-anchor-id="what-hm08-actually-covers">What hm08 actually covers</h2>
<p>Ranges come from <code>anny/data/mpfb2/mesh_metadata/hm08_config.json</code> and <code>basemesh_vertex_groups.json</code>. Counts are inclusive at both ends. The 13 rows sum to 19,150.</p>
<p><strong>That is not the whole mesh. The mesh has 19,158 vertices.</strong> See the correction below.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>group</th>
<th>range</th>
<th>vertices</th>
<th>verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>body</code></td>
<td>0 to 13379</td>
<td>13,380</td>
<td>one block, no sub-parts</td>
</tr>
<tr class="even">
<td><code>helper-tongue</code></td>
<td>13380 to 13605</td>
<td>226</td>
<td>renderable</td>
</tr>
<tr class="odd">
<td>(unnamed helper block)</td>
<td>13606 to 14597</td>
<td>992</td>
<td>124 joint cubes, not renderable</td>
</tr>
<tr class="even">
<td><code>helper-l-eye</code></td>
<td>14598 to 14669</td>
<td>72</td>
<td>renderable</td>
</tr>
<tr class="odd">
<td><code>helper-r-eye</code></td>
<td>14670 to 14741</td>
<td>72</td>
<td>renderable</td>
</tr>
<tr class="even">
<td><code>helper-l-eyelashes</code></td>
<td>14742 to 14866</td>
<td>125</td>
<td>renderable</td>
</tr>
<tr class="odd">
<td><code>helper-r-eyelashes</code></td>
<td>14867 to 14991</td>
<td>125</td>
<td>renderable</td>
</tr>
<tr class="even">
<td><code>helper-lower-teeth</code></td>
<td>14992 to 15059</td>
<td>68</td>
<td>renderable</td>
</tr>
<tr class="odd">
<td><code>helper-upper-teeth</code></td>
<td>15060 to 15127</td>
<td>68</td>
<td>renderable</td>
</tr>
<tr class="even">
<td><code>helper-genital</code></td>
<td>15128 to 15327</td>
<td>200</td>
<td>renderable</td>
</tr>
<tr class="odd">
<td><code>helper-tights</code></td>
<td>15328 to 18001</td>
<td>2,674</td>
<td>proxy volume</td>
</tr>
<tr class="even">
<td><code>helper-skirt</code></td>
<td>18002 to 18721</td>
<td>720</td>
<td>proxy volume</td>
</tr>
<tr class="odd">
<td><code>helper-hair</code></td>
<td>18722 to 19149</td>
<td>428</td>
<td>proxy volume</td>
</tr>
</tbody>
</table>
<p><code>select_groups</code> names the 992-vertex block <code>HELPERS</code>. <code>groups_by_range</code> gives it no range. A caller who counts ranges misses it. <code>hm08-partition</code> proves this and names the block.</p>
</section>
<section id="the-correction-the-mesh-is-19158-vertices-and-the-joint-cubes-come-in-two-ranges" class="level2">
<h2 class="anchored" data-anchor-id="the-correction-the-mesh-is-19158-vertices-and-the-joint-cubes-come-in-two-ranges">The correction: the mesh is 19,158 vertices, and the joint cubes come in two ranges</h2>
<p><code>hm08-partition</code> states the mesh as 19,150 vertices and the unnamed block as one range, <code>13606</code> to <code>14597</code>, which is 992 vertices and reads as 124 joint helper cubes of 8.</p>
<p>Both numbers are short by one cube. <code>basemesh_vertex_groups.json</code> gives <code>JointCubes</code> <strong>two</strong> ranges, not one.</p>
<pre><code>"JointCubes": [[13606, 14597], [19150, 19157]]</code></pre>
<p>That totals 1,000 vertices, which is <strong>125</strong> cubes. The highest index in any of the 144 groups is <code>19157</code>, so the mesh holds 19,158 vertices.</p>
<p>The measurement confirms it. <code>anny.Anny(topology=TopologyConfig(base_mesh="makehuman", remove_unattached_vertices=False))</code> returns 19,158 vertices. The default returns 13,718, because the default drops every unattached vertex, and all of the helper geometry is unattached.</p>
<p>This repeats the exact error <code>hm08-partition</code> was written to catch, one level up. The original claim counted the ranges in <code>groups_by_range</code> and missed the helper block. The correction counted the same 12 ranges, stopped at <code>19149</code>, and missed the second <code>JointCubes</code> range. The tidy arithmetic is what sold it. <code>992 = 124 * 8</code> divides evenly, so nobody asked whether 992 was all of them.</p>
<p>The consequence is the one the original file named. Eight vertices at <code>19150</code> to <code>19157</code> fall through every mask <strong>built from <code>groups_by_range</code></strong>. They either vanish from the corpus or appear as one small floating box inside whichever layer catches the remainder.</p>
<p>Those eight have a name. They are <code>joint-ground</code>, which is MakeHuman’s ground joint and a group of its own. It sits at the end of the mesh instead of in the contiguous block, which is how one read of one range lost it.</p>
</section>
<section id="two-more-corrections-and-the-claim-that-was-true-all-along" class="level2">
<h2 class="anchored" data-anchor-id="two-more-corrections-and-the-claim-that-was-true-all-along">Two more corrections, and the claim that was true all along</h2>
<p><strong>The cubes are not unnamed.</strong> <code>hm08-partition</code> said 992 vertices belong to no group at all. They belong to <code>JointCubes</code>. The true claim is narrower. They belong to no group in <code>groups_by_range</code>.</p>
<p><strong><code>HELPERS</code> does not name them.</strong> The file said <code>select_groups</code> reaches them through <code>HELPERS -&gt; HelperGeometry</code>. <code>HelperGeometry</code> is <code>[[13380, 13605], [14598, 19149]]</code>, which excludes the joint cubes exactly. <code>select_groups</code> never mentions <code>JointCubes</code>.</p>
<p><strong>And the original sentence is true.</strong> Three top-level groups in <code>basemesh_vertex_groups.json</code> partition the mesh with nothing left over.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>group</th>
<th>vertices</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>body</code></td>
<td>13,380</td>
</tr>
<tr class="even">
<td><code>HelperGeometry</code></td>
<td>4,778</td>
</tr>
<tr class="odd">
<td><code>JointCubes</code></td>
<td>1,000</td>
</tr>
<tr class="even">
<td>total</td>
<td>19,158</td>
</tr>
</tbody>
</table>
<p>No overlap and no gap. So “hm08 partitions the mesh, so layer masks have no gaps by construction” holds through these three. It fails through <code>groups_by_range</code>’s twelve. A mask built from the twelve has gaps. A mask built from the three does not.</p>
<p>The count of 125 is also read from the data rather than divided out. The file holds 125 groups named <code>joint-*</code>. Each one is 8 vertices. Their union is <code>JointCubes</code> exactly.</p>
</section>
<section id="the-state-of-that-repository" class="level2">
<h2 class="anchored" data-anchor-id="the-state-of-that-repository">The state of that repository</h2>
<p><code>2-contract/hm08-partition</code> now carries the correction. <code>meshSet</code> is <code>Set.Ico 0 19158</code>. <code>helperBlock</code> is renamed <code>jointCubes</code> and holds two ranges. Two new theorems state the partition, <code>three_groups_cover</code> and <code>three_groups_disjoint</code>. Both retractions stay in the docstring beside what replaces them.</p>
<p><code>lake build</code> is clean and no theorem uses <code>sorry</code>. Reverting <code>jointCubes</code> to the single old range makes <code>three_groups_cover</code> and <code>covered_or_jointCubes</code> fail to compile, so both gates have teeth. <code>check_hm08_claims.py</code> re-derives every constant from the installed ANNY package and ships six negative controls that each must fail.</p>
<p>The repository is now a git repository with two commits, and <code>default.xml</code> places it on the contract side. The remote does not exist yet, so <code>repo sync</code> fails on that entry until it is created.</p>
</section>
<section id="the-24-tags-against-those-groups" class="level2">
<h2 class="anchored" data-anchor-id="the-24-tags-against-those-groups">The 24 tags, against those groups</h2>
<p>The 24 tags are the 13 body tags plus the 11 head tags. <code>head</code> expands into the head tags. Both lists live in <code>common/utils/inference_utils.py</code>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 35%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>tag</th>
<th>source</th>
<th>verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>head</code>, <code>neck</code>, <code>face</code>, <code>ears</code>, <code>nose</code></td>
<td>inside <code>body</code></td>
<td>geometry exists, no split</td>
</tr>
<tr class="even">
<td><code>mouth</code></td>
<td><code>body</code> lips, plus teeth and tongue helpers</td>
<td>partial, needs a split</td>
</tr>
<tr class="odd">
<td><code>eyes</code></td>
<td><code>helper-l-eye</code>, <code>helper-r-eye</code></td>
<td>separated</td>
</tr>
<tr class="even">
<td><code>irides</code>, <code>eyewhite</code></td>
<td>inside the eye helpers</td>
<td>not separated</td>
</tr>
<tr class="odd">
<td><code>eyelash</code></td>
<td>eyelash helpers</td>
<td>separated</td>
</tr>
<tr class="even">
<td><code>front hair</code>, <code>back hair</code></td>
<td><code>helper-hair</code></td>
<td>proxy only, and no front and back split</td>
</tr>
<tr class="odd">
<td><code>topwear</code>, <code>bottomwear</code>, <code>legwear</code></td>
<td><code>helper-tights</code>, <code>helper-skirt</code></td>
<td>proxy only</td>
</tr>
<tr class="even">
<td><code>eyebrow</code></td>
<td>none, painted into the skin texture</td>
<td>absent, attached like a garment</td>
</tr>
<tr class="odd">
<td><code>headwear</code>, <code>eyewear</code>, <code>earwear</code></td>
<td>none</td>
<td>absent</td>
</tr>
<tr class="even">
<td><code>neckwear</code>, <code>handwear</code>, <code>footwear</code></td>
<td>none</td>
<td>absent</td>
</tr>
<tr class="odd">
<td><code>tail</code>, <code>wings</code>, <code>objects</code></td>
<td>none</td>
<td>absent</td>
</tr>
</tbody>
</table>
<p>Ten tags are absent. Five have a proxy volume and no appearance. Nine need a partition of geometry that already exists.</p>
<p><code>eyebrow</code> is not a special case. It joins the absent list, which makes <strong>ten</strong>, not nine.</p>
<p>MakeHuman paints it into the skin texture, so it shares the skin’s depth and the depth-order rule gives it no layer of its own. The fix is the same as for every other absent tag. It becomes a separate attached mesh, handled like a garment or an object, with its own geometry and therefore its own depth.</p>
<p>The ten absent tags are <code>eyebrow</code>, <code>headwear</code>, <code>eyewear</code>, <code>earwear</code>, <code>neckwear</code>, <code>handwear</code>, <code>footwear</code>, <code>tail</code>, <code>wings</code> and <code>objects</code>. One route serves all of them.</p>
<p>An earlier draft carved <code>eyebrow</code> out and proposed authoring it against the basemesh. That was wrong twice. It invented a special case where the ordinary one works, and it pointed at the one mesh that must not be edited.</p>
</section>
<section id="the-basemesh-vertex-order-is-frozen" class="level2">
<h2 class="anchored" data-anchor-id="the-basemesh-vertex-order-is-frozen">The basemesh vertex order is frozen</h2>
<p>This is the hard constraint, and it is about <strong>order</strong>, not count.</p>
<p>Two things read the basemesh by index, and both break silently under a permutation.</p>
<p><strong><code>coco.pth</code> weights are per-index.</strong> Each keypoint is a weight vector 19,158 wide. The weights for <code>nose</code> are non-zero at indices 161, 162, 163, 164, 184, 197 and others. Reorder the mesh and the vector still has 19,158 entries, still multiplies, and puts the nose somewhere else.</p>
<p><strong>Every hm08 group is a range.</strong> <code>body</code> is <code>[[0, 13379]]</code>. <code>helper-hair</code> is <code>[[18722, 19149]]</code>. A range is an order claim. Reordering invalidates every group, so it invalidates every mask.</p>
<p>So no part may be merged into the basemesh, and no operation may renumber it. Attached parts carry their own vertex arrays. This is what makes “treat it like a garment” the safe answer rather than merely the tidy one.</p>
<section id="the-count-gate-was-decoration" class="level3">
<h3 class="anchored" data-anchor-id="the-count-gate-was-decoration">The count gate was decoration</h3>
<p>The earlier gate asserted 19,158 vertices. A permutation keeps that count exactly, so the gate passes on the broken input it exists to catch.</p>
<p>The order-sensitive form hashes the face index array, because face indices reference vertex indices and therefore encode the order:</p>
<pre><code>faces        (27420, 3)
sha256       6b98503de9657efce24300113b90bdc5a4e06a87e2f7d7f7067400a563185da4</code></pre>
<p>Permuting the vertices leaves the count at 19,158 and changes that hash to <code>616c75243f...</code>. That is the negative control, and it is the reason the hash replaces the count rather than joining it.</p>
<p><strong>State the coverage honestly.</strong> The face array references vertex indices up to 14741 only, so the hash pins the order of that span and says nothing about 14742 to 19157. The group-range assertions in <code>check_hm08_claims.py</code> cover the remainder. Neither check alone is sufficient, and reporting the hash as though it pinned the whole mesh would be the same error one level down.</p>
</section>
</section>
<section id="why-the-depth-order-needs-no-inpainting" class="level2">
<h2 class="anchored" data-anchor-id="why-the-depth-order-needs-no-inpainting">Why the depth order needs no inpainting</h2>
<p>Render one group with the full scene in the depth buffer. Write colour only where the group owns the fragment. Then render the same group alone. The second render shows the occluded surface, because that surface is real. The difference between the two renders is the amodal region, which See-Through must otherwise invent.</p>
<p>This holds for Half A because the geometry is there. It fails for Half B until the rebuild runs, and that is the entire reason for the rebuild.</p>
<p>One cost is real. A garment shell sits above the skin. Set that offset too small and the two surfaces fight in the depth buffer. Set it too large and the garment floats. The working figure is about 2 mm at body scale, which is a little over two stacked credit cards. Measure the offset per garment. Do not assume it.</p>
</section>
<section id="the-rebuild-stage-by-stage" class="level2">
<h2 class="anchored" data-anchor-id="the-rebuild-stage-by-stage">The rebuild, stage by stage</h2>
<p>Bugs live at interfaces. Each stage names its interface and the check that guards it.</p>
<ol type="1">
<li><p><strong>Pose and render.</strong> ANNY originates the pose. Render N views with colour, depth and the hm08 group index per pixel. Interface: camera convention. Parse the up axis, the rotation order and the units. Do not assume them.</p>
<p>Depth and the group index are intermediates. Depth feeds the control at stage 2. The group index feeds the cross-check at stage 5. Neither one lands beside the image in the corpus. The section below states what the corpus render writes, and that list is shorter.</p></li>
<li><p><strong>Stylize under depth control.</strong> Qwen-Image plus its Apache-2.0 depth ControlNet turns each view into an illustration with hair and garments. Interface: the depth image. Check that the control reached the model, because a dropped control looks like a bad seed.</p></li>
<li><p><strong>Referee the result.</strong> <code>pose-consensus</code> refits the stylized body to the conditioning pose. Report the residual as a percentage of stature. The finger chain gate runs, because <code>handwear</code> is one of the 24 tags. A gate that did not run is a failure, not a waiver.</p></li>
<li><p><strong>Lift to geometry.</strong> TRELLIS.2 or Pixal3D takes the N stylized views and returns a mesh. Interface: view count and camera agreement. Single view is not enough here.</p></li>
<li><p><strong>Segment the new geometry.</strong> P3-SAM cuts the lifted mesh into parts. Interface: part to tag mapping. This mapping is inferred, not true by construction, so it is checked against the hm08 group index that stage 1 rendered.</p></li>
<li><p><strong>Edit one category under a mask.</strong> VoxHammer adds or replaces one tag. Its splice step runs before the decode, so geometry outside the mask does not move. RFD 1048 states this guard.</p></li>
<li><p><strong>Render the layers.</strong> Repeat stage 1 on the rebuilt mesh. Now every tag has geometry, so the depth order gives the layers, and nothing is inpainted.</p></li>
</ol>
<p>Stages 2 and 6 are the only generative steps. Everything they produce is Half B and carries the four conditions.</p>
</section>
<section id="what-the-corpus-render-writes" class="level2">
<h2 class="anchored" data-anchor-id="what-the-corpus-render-writes">What the corpus render writes</h2>
<p>The rebuild above is pipeline. The corpus render is the thing two models train on, and its output list is short and closed.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>output</th>
<th>consumer</th>
<th>why it cannot be recomputed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>the image</td>
<td>both</td>
<td>it is the input</td>
</tr>
<tr class="even">
<td>keypoint positions</td>
<td>the keypoint detector</td>
<td>the pose is authored, so the position is not inferable from the image</td>
</tr>
<tr class="odd">
<td>the 3D shape</td>
<td>Pixal3D</td>
<td>the same, in three dimensions</td>
</tr>
</tbody>
</table>
<p>Nothing else is written. Depth, the hm08 group index, the camera matrix and the material identifier are intermediates of the render. No second annotator runs. No derived column is stored, because a derived column can be recomputed and a stored one can disagree with its source.</p>
<p>A new output is drift unless one of the two consumers asked for it. Name the consumer or drop the output.</p>
<section id="the-keypoints-are-true-by-construction" class="level3">
<h3 class="anchored" data-anchor-id="the-keypoints-are-true-by-construction">The keypoints are true by construction</h3>
<p><code>anny/data/keypoints/coco.pth</code> holds <strong>23</strong> named keypoints, which is COCO-17 plus the six foot points. It is not COCO-17 alone.</p>
<p>Each entry is a weight vector over the mesh vertices. The vectors sum to 1 and the first one has 317 non-zero entries. A keypoint position is therefore a weighted sum of posed vertices. The renderer computes it from the mesh it just posed. No detector runs, and no label is inferred.</p>
</section>
<section id="the-topology-must-be-pinned-or-the-keypoints-land-on-the-wrong-body" class="level3">
<h3 class="anchored" data-anchor-id="the-topology-must-be-pinned-or-the-keypoints-land-on-the-wrong-body">The topology must be pinned, or the keypoints land on the wrong body</h3>
<p>The weight vectors are 19,158 wide. That is the makehuman basemesh with unattached vertices kept.</p>
<pre><code>TopologyConfig(base_mesh="makehuman", remove_unattached_vertices=False)</code></pre>
<p>The default configuration returns 13,718 vertices. A weight vector of width 19,158 cannot multiply it. This resolves the open question in <code>logbook/todo.md</code>, which asks which topology <code>coco.pth</code> targets and suggests the topology may not be exposed. It is exposed. It needs the two arguments above.</p>
<p><code>remove_unattached_vertices</code> is the only argument that moves the count. A sweep over <code>nudity_edits</code>, <code>eyes</code> and <code>tongue</code>, all eight combinations, returns 19,158 every time. Those three flags change faces and not vertices. So one argument decides whether the keypoints can be computed at all, and the other three cannot break it by accident.</p>
<p>Pin the topology in the render configuration and assert the vertex count before the first frame. A silent shape mismatch here would produce keypoints for a different body.</p>
</section>
</section>
<section id="gates-each-with-a-negative-control" class="level2">
<h2 class="anchored" data-anchor-id="gates-each-with-a-negative-control">Gates, each with a negative control</h2>
<p>A check that passes on known-broken input certifies the defect. Each gate ships with an input that must fail.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 50%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>gate</th>
<th>passes on</th>
<th>must fail on</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>coverage</td>
<td>every mesh vertex in a group or the named helper block</td>
<td>a mesh with one unnamed vertex</td>
</tr>
<tr class="even">
<td>depth order</td>
<td>layers composite back to the source render</td>
<td>a layer pair swapped in z</td>
</tr>
<tr class="odd">
<td>pose fidelity</td>
<td>referee residual under the stature bar</td>
<td>the impossible pose control</td>
</tr>
<tr class="even">
<td>finger chain</td>
<td>flat residual from MCP to DIP</td>
<td>the compounding chain control</td>
</tr>
<tr class="odd">
<td>control reached</td>
<td>depth control present in the call record</td>
<td>a run with the control dropped</td>
</tr>
<tr class="even">
<td>provenance</td>
<td>checkpoint and prompt recorded per Half B row</td>
<td>a row with the checkpoint missing</td>
</tr>
<tr class="odd">
<td>vertex count</td>
<td>the posed mesh has 19,158 vertices</td>
<td>a run on the 13,718 default</td>
</tr>
<tr class="even">
<td>vertex order</td>
<td>the face-index hash matches</td>
<td>the mesh permuted, count unchanged</td>
</tr>
<tr class="odd">
<td>basemesh untouched</td>
<td>every added part is its own mesh</td>
<td>any part merged into the basemesh</td>
</tr>
<tr class="even">
<td>output set</td>
<td>the corpus row holds image, keypoints and shape</td>
<td>a row with a fourth output</td>
</tr>
</tbody>
</table>
<p>Report the floor beside each number. A residual with no baseline is not a measurement.</p>
<p>For a fixed corpus, enumerate. A sampled check sees only defects above about 3/n.</p>
</section>
<section id="the-ledger-protocol" class="level2">
<h2 class="anchored" data-anchor-id="the-ledger-protocol">The ledger protocol</h2>
<section id="where-it-lives" class="level3">
<h3 class="anchored" data-anchor-id="where-it-lives">Where it lives</h3>
<p>A repository, not a shared directory and not a chat channel. <code>CLAUDE.md</code> gives the reason under “Why a repository and not a symlink”. A repository has a history, so a change can be traced. It is reviewable, so a widening is a diff somebody approved. <code>repo status</code> reports it.</p>
<p>Place it in <code>default.xml</code> when it is added. An unplaced repository is the drift the six sides exist to stop.</p>
</section>
<section id="the-files" class="level3">
<h3 class="anchored" data-anchor-id="the-files">The files</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 79%">
</colgroup>
<thead>
<tr class="header">
<th>file</th>
<th>role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>HANDOFF.md</code></td>
<td>live state, rewritten in full each session, no history</td>
</tr>
<tr class="even">
<td><code>ledger.jsonl</code></td>
<td>append only, one row per event</td>
</tr>
</tbody>
</table>
<p>Current tag ownership is a fold over <code>ledger.jsonl</code>. It is not a mutable field. A fold cannot disagree with its own history.</p>
</section>
<section id="the-row" class="level3">
<h3 class="anchored" data-anchor-id="the-row">The row</h3>
<p>Essential tuple normal form. No NULLs. <code>retracts</code> is <code>-1</code> when the row retracts nothing, because <code>-1</code> is a value and a NULL is not.</p>
<pre><code>{"seq": 41, "parent": "sha256:...", "agent": "half-b", "kind": "CLAIM",
 "tag": "front hair", "expires": -1, "retracts": -1,
 "artifact": "sha256:...", "body": {"measured": 0.87, "floor": 0.31, "apparatus": "..."}}</code></pre>
</section>
<section id="the-five-kinds" class="level3">
<h3 class="anchored" data-anchor-id="the-five-kinds">The five kinds</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 56%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>kind</th>
<th>means</th>
<th>required</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>LEASE</code></td>
<td>I take these tags until the expiry</td>
<td><code>tag</code>, <code>expires</code></td>
</tr>
<tr class="even">
<td><code>RELEASE</code></td>
<td>I am done, here is the artifact</td>
<td><code>tag</code>, <code>artifact</code></td>
</tr>
<tr class="odd">
<td><code>CLAIM</code></td>
<td>I measured this</td>
<td>measurement, floor, apparatus</td>
</tr>
<tr class="even">
<td><code>RETRACT</code></td>
<td>row <code>retracts</code> is withdrawn, with a reason</td>
<td><code>retracts</code></td>
</tr>
<tr class="odd">
<td><code>BLOCK</code></td>
<td>I cannot proceed, the named precondition is unmet</td>
<td>the precondition</td>
</tr>
</tbody>
</table>
</section>
<section id="the-rules-a-linter-enforces" class="level3">
<h3 class="anchored" data-anchor-id="the-rules-a-linter-enforces">The rules a linter enforces</h3>
<ol type="1">
<li>One holder per tag. A <code>LEASE</code> on a held tag is rejected.</li>
<li>A <code>LEASE</code> carries an expiry. A lease with no expiry is a fork.</li>
<li>A <code>CLAIM</code> carries a floor and an apparatus. A number with no baseline is rejected.</li>
<li>A <code>RETRACT</code> appends. It never edits or deletes. The retraction sits beside what it retracts.</li>
<li>A <code>BLOCK</code> names the precondition. An agent may not turn a <code>BLOCK</code> into a silent skip.</li>
<li>The ledger carries no permissions. A row that asks a peer to widen <code>.claude/settings.json</code> is rejected. <code>CLAUDE.md</code> states this rule and the linter makes it mechanical.</li>
<li>A licence conclusion does not transfer. A peer’s licence <code>CLAIM</code> is a pointer to re-verify. An accurate relay and a mistaken one look the same from the receiving end.</li>
</ol>
</section>
<section id="concurrency" class="level3">
<h3 class="anchored" data-anchor-id="concurrency">Concurrency</h3>
<p>The ledger is a branch. Sync is <code>git push --ff-only</code>.</p>
<p>A rejected push proves the agent wrote against a stale head. The agent refetches, replays its rows onto the new head, and rechecks that its lease still holds. This is compare and swap. It needs no lock server and no new protocol.</p>
<p>Sync is event driven. An agent syncs before it takes a lease and after it releases one. A timed poll is a liveness check. It is not the protocol.</p>
</section>
<section id="the-five-negative-controls" class="level3">
<h3 class="anchored" data-anchor-id="the-five-negative-controls">The five negative controls</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 52%">
<col style="width: 9%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>input</th>
<th>must be</th>
<th>because</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>two <code>LEASE</code> rows on <code>front hair</code></td>
<td>REJECT</td>
<td>one holder per tag</td>
</tr>
<tr class="even">
<td>a <code>CLAIM</code> with no floor</td>
<td>REJECT</td>
<td>a number with no baseline</td>
</tr>
<tr class="odd">
<td>a <code>RETRACT</code> that deletes the target row</td>
<td>REJECT</td>
<td>the parent hash breaks</td>
</tr>
<tr class="even">
<td>a row that widens <code>settings.json</code></td>
<td>REJECT</td>
<td>permission cannot go sideways</td>
</tr>
<tr class="odd">
<td>a push from a stale head</td>
<td>REJECT</td>
<td>the fast-forward rule</td>
</tr>
</tbody>
</table>
<p>A positive control alone proves only that the linter is not uniformly hostile.</p>
</section>
</section>
<section id="garments-come-from-geometry-too-and-cloth-fit-is-how-they-get-there" class="level2">
<h2 class="anchored" data-anchor-id="garments-come-from-geometry-too-and-cloth-fit-is-how-they-get-there">Garments come from geometry too, and cloth-fit is how they get there</h2>
<p>Half A said “render hm08 groups as depth-ordered layers” and stopped at the body. Clothing was left to Half B, the generated half, which is the expensive one. It does not have to be.</p>
<p><strong>hm08 already ships three garment proxies.</strong> <code>helper-tights</code> is 2,674 vertices, <code>helper-skirt</code> is 720 and <code>helper-hair</code> is 428, all in the base mesh and all posed by the same rig as the body. They carry no appearance, which is why the coverage table above marks <code>topwear</code>, <code>bottomwear</code>, <code>legwear</code>, <code>front hair</code> and <code>back hair</code> as “proxy only”. A proxy with no appearance is still a volume with a correct silhouette and a correct depth, and those are the two things a layer needs.</p>
<p><strong>cloth-fit puts a real garment on that volume.</strong> <code>Huangzizhou/cloth-fit</code> implements <em>Intersection-free Garment Retargeting</em>, Huang, Araújo, Kunz, Zorin, Panozzo and Zordan, SIGGRAPH Conference Papers 2025. It is <strong>MIT</strong>, which clears the licence bar outright, and it is CPU-only over PolyFEM, so it needs no GPU and no quantisation and therefore raises none of the generated-synthetic conditions. It is not a generator: it deforms a garment somebody authored onto a body somebody authored, which is constructed rather than sampled.</p>
<p><strong>CORRECTION, BECAUSE THE PREMISE FOR READING IT WAS WRONG.</strong> It was reached for on the understanding that it fits garments to <em>volumes</em>. Its README says the opposite in one line: “For avatars and garments, only <code>.obj</code> triangular mesh is supported.” The inputs are four surfaces – target avatar, source garment, source skeleton and target skeleton, the last two as edge meshes – plus an optional skinning-weight matrix of skeleton nodes by vertices, and vertices project to the nearest bone by distance when it is absent. Whether PolyFEM tetrahedralises internally is unverified here: the paper PDF exceeds the fetch limit and was not read, so this records what the interface takes and makes no claim about the solver.</p>
<p>The correction does not cost the plan anything, and it is worth saying why rather than leaving it to be re-derived. What the method needs is an avatar surface, a skeleton and skinning weights. ANNY supplies all three from one call. The hm08 proxies remain the right target because they are already the garment-shaped surface at the garment’s place on the body; they are simply surfaces rather than solids, which is what the tool wanted anyway.</p>
<p><strong>Adding proxies is the extension point.</strong> Five of the ten absent tags are garments or worn objects – <code>headwear</code>, <code>eyewear</code>, <code>earwear</code>, <code>neckwear</code>, <code>footwear</code> – and each one wants the same treatment <code>helper-tights</code> already has: a proxy group in the mesh, posed by the rig, then a retarget onto it. That is an edit to the partition rather than to the basemesh, so the frozen vertex order above is not disturbed and its hash gate still holds.</p>
<p><strong>And the layer falls out of a subtraction.</strong> Render the body without the garment, render it with, and difference the two. The garment layer’s alpha is where they differ and its depth order is the depth buffer’s, both exact, neither inferred. That is the same construction the keypoints use and it inherits the same property: there is no annotator and no model in the label. It also supplies the negative control this section would otherwise lack – a retarget that intersects the body produces a garment layer with body pixels inside it, so the subtraction detects the failure the tool’s own guarantee is supposed to prevent.</p>
<p>Two limits, stated rather than discovered.</p>
<p><strong>A 2D garment layer composites only in the pose it was drawn in.</strong> The kimono art that prompted this is A-pose, and it lands on an A-pose body and nowhere else. Carrying it to another pose needs a dense correspondence over the body, which is what RFD 1122’s 104 points are for. The two RFDs meet here rather than merely citing each other.</p>
<p><strong>Reproducibility has a floor on the GPU.</strong> <code>cuda_ad_rgb</code> is byte-identical at 16 samples per pixel and stops being so above it, with the disagreement growing as samples rise – 5.8e-11 mean at 64, 1.9e-08 at 1024, worst case 3.6e-07 against one 8-bit level at 3.9e-03, so roughly one eleven-thousandth of one level. Far below anything visible, and fatal to a hash. A render whose evidence is a digest is produced on <code>llvm_ad_rgb</code>, which held byte-identical at every count tested and did so without being pinned to one thread.</p>
<section id="the-tag-count-in-this-document-does-not-match-the-code" class="level3">
<h3 class="anchored" data-anchor-id="the-tag-count-in-this-document-does-not-match-the-code">The tag count in this document does not match the code</h3>
<p>Stated as a defect rather than fixed silently, because the fix is a decision about which list is authoritative and that has not been taken.</p>
<p>This document says “the 24 tags are the 13 body tags plus the 11 head tags” and sources both to <code>common/utils/inference_utils.py</code>. That file holds one list, <code>VALID_BODY_PARTS_V2</code>, with <strong>19</strong> entries. The current vocabulary is a third file the document does not name, <code>common/assets/bodytags_v3.json</code>, with <strong>23</strong> keys: it splits <code>hair</code> into front and back and <code>eyes</code> into <code>irides</code>, <code>eyewhite</code> and <code>eyelash</code>, and carries the danbooru synonyms for each.</p>
<p>So 24 matches neither artefact. The coverage table above is still right about which tags have geometry, which is what it is for; the count in the prose is not.</p>
</section>
<section id="the-quads-exist-and-they-are-discarded-at-annys-python-boundary" class="level3">
<h3 class="anchored" data-anchor-id="the-quads-exist-and-they-are-discarded-at-annys-python-boundary">The quads exist, and they are discarded at ANNY’s Python boundary</h3>
<p>The basemesh is not quad-dominant, it is <strong>pure quad</strong>: <code>mpfb2/3dobjs/base.obj</code> has 18,486 faces and every one of them is a quad, over 19,158 vertices. <code>Anny(...).faces</code> returns 36,108 triangles, which is exactly twice 18,054, so the pairing is thrown away at the API rather than absent from the data.</p>
<p>That matters because the two consumers want different things. cloth-fit takes <code>.obj</code> triangles and nothing else, by its own README. Catmull-Clark subdivision wants quads and degrades on triangles. OpenUSD stores either, since <code>faceVertexCounts</code> is per-face, so the corpus can hold the quads and hand triangles only to the solver.</p>
<p><strong>Triangulation adds faces and never vertices</strong>, which is why this is safe here. The frozen vertex order above is untouched by it and its hash gate still holds, and a deterministic split restores the quads exactly.</p>
<p>One trap, of the same kind the <code>Hips</code>-to-<code>root</code> mapping already produced. <code>base.obj</code> carries 19,158 vertices and ANNY reports 18,056, because the joint cubes are pruned. The quad table indexes the un-pruned mesh, so the index mapping is recorded with it or the restore writes onto the wrong vertices, silently and plausibly.</p>
</section>
<section id="polyfem-does-not-export-to-onnx-and-the-corpus-path-does-not-want-it-to" class="level3">
<h3 class="anchored" data-anchor-id="polyfem-does-not-export-to-onnx-and-the-corpus-path-does-not-want-it-to">PolyFEM does not export to ONNX, and the corpus path does not want it to</h3>
<p>Asked and answered rather than assumed. PolyFEM is C++ under MIT with no PyTorch, TensorFlow or ONNX component anywhere in it. ONNX encodes a static tensor dataflow graph; a barrier-method Newton solve has an active contact set that changes each iteration, with dynamic sparsity, a line search and collision queries. There is no fixed graph to export, so this is a shape mismatch and not a missing feature.</p>
<p>It also buys nothing. The fit is an offline authoring step: one garment against one body is solved once and the result is baked geometry, and nothing in the inference path calls the solver.</p>
<p>What is exportable is a surrogate trained on the solver’s outputs, and its classification is worth stating before somebody assumes the cautious answer. A deterministic FEM solve over assets we hold is <strong>constructed</strong> synthetic, not generated – the same inputs reproduce it and the labels are true by construction – so the four generated-synthetic conditions do not apply to it.</p>
<p><strong>A gate before adoption, from the project’s own README.</strong> It says the code is MIT and then warns to “be mindful of third-party libraries which are used by PolyFEM and may be available under a different license”. MIT on the code is not MIT on the build, and the dependency licences are read before this becomes a <code>&lt;project&gt;</code> in a manifest, not after.</p>
</section>
<section id="a-proxy-is-a-form-and-a-form-is-free" class="level3">
<h3 class="anchored" data-anchor-id="a-proxy-is-a-form-and-a-form-is-free">A proxy is a form, and a form is free</h3>
<p><strong>RETRACTED: proxies do not inherit a garment’s licence, and the first version of this section said they did.</strong> It read that a proxy derived from an encumbered garment is a derivative of it because “shape is usually the protected part”. That is wrong about the thing it was most confident about. A garment is a useful article, so its cut and shape are largely outside copyright and only separable pictorial elements – a print, an applique, a logo – carry it. That is what <em>Star Athletica v. Varsity Brands</em> turned on. A weapon form is functional shape for the same reason. People are free to make body forms and weapon forms, and the retracted paragraph would have blocked a legitimate route on a misreading.</p>
<p>The line that actually holds is narrower. <strong>Copying the file is the problem; re-expressing the form is not.</strong> An authored mesh is somebody’s creative work and a silhouette is not, so decimating their mesh into a proxy copies the asset, while authoring a proxy to the same form does not. Looking at the garment is not what makes the difference, and the earlier framing put the boundary there.</p>
<p>So a proxy is a good way to distribute the shape of clothing that cannot itself be shared. It travels as a placement spec – this class of garment sits here on this body, at this ease – and the recipient supplies their own asset for cloth-fit to retarget onto it. That is also the honest statement of what a proxy is worth: a stand-in that is worse than the real garment wherever the real garment exists, and better than nothing everywhere else.</p>
<section id="the-policy-is-narrower-than-the-law-and-that-is-deliberate" class="level4">
<h4 class="anchored" data-anchor-id="the-policy-is-narrower-than-the-law-and-that-is-deliberate">The policy is narrower than the law, and that is deliberate</h4>
<p>The retraction above stands: a form is free, and nothing here is required to treat a silhouette as encumbered. What follows is chosen anyway, and it is a <strong>decision rather than a derivation</strong>. Saying so is the honest form, because a rule presented as a legal conclusion invites the next reader to check the conclusion, find it too strict, and drop the rule.</p>
<p>Three clauses.</p>
<p><strong>A proxy form is CC0.</strong> Not permissively licensed, not licence-clean with attribution – CC0. A proxy travels further than the corpus it was built for and is the sort of asset that ends up in somebody’s deliverable with no manifest behind it, so the terms have to survive being separated from their provenance.</p>
<p><strong>A proxy is not traced from another thing.</strong> Tracing our own work is fine, and the distinction is authorship rather than method: a form derived from an asset we made carries our provenance forward, and one traced from somebody else’s makes a <code>CITATION.cff</code> that cannot answer where the shape came from. The objection is to the unanswerable record, not to the tracing.</p>
<p><strong>When an exact garment is needed, it is fitted rather than approximated.</strong> This is the clause that makes the other two cheap. Tracing exists to get exactness quickly, and cloth-fit gets exactness properly – an authored garment retargeted onto the body, intersection-free, from inputs whose licences are each answerable. So the policy forbids nothing it does not already replace, which is the test a self-imposed restriction has to pass to survive contact with a deadline.</p>
</section>
<section id="two-alternatives-were-asked-about-and-one-of-them-is-real" class="level4">
<h4 class="anchored" data-anchor-id="two-alternatives-were-asked-about-and-one-of-them-is-real">Two alternatives were asked about, and one of them is real</h4>
<p>The ONNX question above was answered for PolyFEM alone, which left it open whether a different solver would answer it better. Two were named.</p>
<p><strong>AVBD is MIT and is a teaching demo, by its authors’ own words.</strong> <code>savant117/avbd-demo3d</code> implements Augmented Vertex Block Descent out of Utah, and its README says the repository “is not intended to be a super optimized implementation, but an easy to understand demonstration of how to implement the technique”. That is a statement not to depend on it, made by the people who would know. It also carries git submodules, which are blocklisted here, so adopting it would mean vendoring first. On the ONNX question it fails identically to PolyFEM: an iterative solver has no static graph to export.</p>
<p><strong>MuJoCo is the one that reaches ONNX, and two properties are why.</strong> It is Apache-2.0, with documentation under CC BY 4.0 – worth naming, because the blocklist excludes CC-BY-SA and this is not that. MJX is MuJoCo in JAX, so it compiles to a static graph and is differentiable and GPU-resident, which is exactly the thing PolyFEM cannot offer. And MuJoCo’s flexes are 1, 2 or 3 dimensional, with capsule, triangle or <strong>tetrahedral</strong> elements, so the volumetric representation this document first assumed cloth-fit had does genuinely exist here.</p>
<p><strong>The category still decides it, and the category is not the licence.</strong> cloth-fit solves a static fitting problem and its barrier makes intersection-free a guarantee. MuJoCo simulates dynamics under soft constraints, which penalise penetration rather than forbidding it. For the layer subtraction that difference is the whole thing: penetration is what puts body pixels inside the garment layer, which is the negative control this section already names. One tool is correct by construction and the other needs the control run every time.</p>
<p><strong>Unverified, and flagged rather than assumed.</strong> JAX requires static shapes to compile, so anything exportable has a fixed iteration count and fixed-size contact buffers. MJX’s specific limits were not read here, so the export path is recorded as existing rather than as measured, and a number would have to come from a run.</p>
<p>So the split is by stage rather than by preference. Offline corpus authoring, where one garment meets one body once and the result is baked, is cloth-fit’s, and ONNX is irrelevant to it. A garment that must be differentiable inside a training loop, or draped across many bodies in a GPU batch, is MJX’s, and is the only case where the export question has a point. AVBD is neither as it stands.</p>
</section>
<section id="correction-cloth-lives-in-mujocos-warp-backend-not-its-jax-one" class="level4">
<h4 class="anchored" data-anchor-id="correction-cloth-lives-in-mujocos-warp-backend-not-its-jax-one">CORRECTION: cloth lives in MuJoCo’s Warp backend, not its JAX one</h4>
<p>The section above recommended MJX on the grounds that JAX compiles to a static graph, which is what made the ONNX question answerable at all. That reasoning is right about MuJoCo generally and wrong about the case this document needs.</p>
<p>MuJoCo has two GPU backends and only one of them simulates cloth. Counted in the vendored copy at <code>3-interactor/mujoco-riscv64/thirdparty/mujoco</code>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 23%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>backend</th>
<th>flex collision file</th>
<th><code>flex</code> in its collision driver</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MJX / JAX, <code>mjx/_src/</code></td>
<td>none</td>
<td>0</td>
</tr>
<tr class="even">
<td>MJX / Warp, <code>third_party/mujoco_warp</code></td>
<td><code>collision_flex.py</code></td>
<td>720</td>
</tr>
</tbody>
</table>
<p>So the backend that would have exported has no deformables, and the backend with deformables is not the one that compiles to a graph. The ONNX framing does not survive the correction.</p>
<p><strong>What replaces it is better, and it was already here.</strong> ANNY runs on NVIDIA Warp – every run in this workspace announces <code>Warp 1.16.0</code> – and MuJoCo’s flex backend is <code>mujoco_warp</code>, pinned at <code>warp-lang==1.14.0</code>. Warp differentiates through <code>wp.Tape</code>. A differentiable garment-on-body loop is therefore one runtime with no bridge and no export, and the concrete task is reconciling 1.14.0 against 1.16.0 rather than writing a converter.</p>
<p>MuJoCo is also already vendored rather than newly adopted, in <code>thirdparty/</code> where a diff can see it, so the submodule rule is satisfied without further work. Recommending it as a new dependency, as the previous section did, was a failure to look.</p>
</section>
<section id="inflating-the-collision-geometry-and-what-it-costs" class="level4">
<h4 class="anchored" data-anchor-id="inflating-the-collision-geometry-and-what-it-costs">Inflating the collision geometry, and what it costs</h4>
<p>CPU-bound authoring is too slow for volume, so the question is whether the GPU path can be made safe enough. MuJoCo’s own words for <code>margin</code> are “the geometric inflation of the geom surfaces”: contacts are detected below <code>margin + gap</code>, forces are generated below <code>margin</code>, and the two geoms’ margins are summed.</p>
<p>The Warp flex kernel implements it – 109 references in <code>collision_flex.py</code>, with the arithmetic explicit at lines 141, 167 and 199 – and it resolves the objection that would otherwise sink the idea. Flex <code>radius</code> is documented as affecting “both collision detection and rendering”, so inflating it would thicken the visible cloth. <code>flex_margin</code> is a separate array from <code>flex_radius</code> in the kernel, so margin inflates collision alone. Separation at rest is then</p>
<pre><code>geom_margin (body) + flex_margin (garment) + flex_radius (true half-thickness) - penetration</code></pre>
<p>with <code>radius</code> left at the real cloth thickness so the render stays honest. Nothing here depends on MuJoCo’s renderer, since the frames come from Mitsuba over the simulated vertex positions.</p>
<p><strong>The cost is stated rather than buried: margin is not free and it is not a trick.</strong> Forces begin at <code>margin</code>, so the cloth is held off the skin at that distance. For clothing that is arguably the right model rather than an artefact – garments have <strong>ease</strong>, and fabric does not lie on skin – so the offset is a physical parameter that has to be chosen anyway. Six millimetres of ease, four stacked pennies, is a shirt and not an error. What it is not is a guarantee: without CCD filtering the step, a fast or tightly constrained region can cross the margin inside one timestep.</p>
<p>So the bound is measured, in five steps, the last of which is the one that makes the rest mean anything.</p>
<ol type="1">
<li>Drape across the body-by-garment matrix on the GPU.</li>
<li>Record the minimum signed distance from garment surface to body surface, per frame, over the whole run.</li>
<li>Set <code>geom_margin</code> above the worst observed penetration and re-run.</li>
<li>Pass condition: zero frames at negative separation.</li>
<li><strong>Negative control:</strong> run once at <code>margin = 0</code> and confirm the check fails. A penetration check that passes on a known-penetrating configuration certifies the defect.</li>
</ol>
<p>Step 2’s worst case decides the approach. A penny or two can be offset past while the garment still reads correctly. A soda can would hold the clothing visibly off the body, and authoring would go back to cloth-fit – on the CPU path this was trying to leave.</p>
<p><strong>Not yet run.</strong> The vendored MJX pins <code>warp-lang==1.14.0</code> against ANNY’s 1.16.0, so an environment is the blocker rather than any question about the design.</p>
</section>
<section id="ccd-is-declined-and-the-discard-rate-is-what-would-overturn-it" class="level4">
<h4 class="anchored" data-anchor-id="ccd-is-declined-and-the-discard-rate-is-what-would-overturn-it">CCD is declined, and the discard rate is what would overturn it</h4>
<p>Continuous collision detection guarantees a property of the trajectory, and only the endpoint is observed here: the settled drape is rendered and the path is not. A garment that tunnels briefly and settles correctly yields a perfect layer, and one that never penetrates but settles wrong is useless either way.</p>
<p>The exception is genuine but narrow. Tunnelling that ends on the wrong side – a sleeve through an arm, staying there – is a final-state failure and CCD does prevent it. That failure is far cheaper to detect than to prevent, and the detector already exists for another reason: body pixels inside the garment layer, at render time, free. Rule 4 of RFD 1122 already sets the policy, that a failure is discarded rather than fixed, and a corpus can afford to drop frames.</p>
<p>Two things worth knowing before treating this as settled. IPC’s guarantee is conditional on an intersection-free initial state, so CCD preserves an invariant rather than establishing one, and a sleeve initialised inside an arm is not rescued by any solver. And CCD-filtered line search is much of why IPC is CPU-bound, so adding it to the Warp path reintroduces the cost this section exists to escape – “add CCD” and “leave CPU-only” are close to one decision taken twice.</p>
<p><strong>The discard rate decides it.</strong> Drape the corpus, run the render-time penetration check, count rejected frames. A few percent and discarding is plainly right. A third and most of the GPU time is being wasted, at which point CCD or a better initialisation earns its cost. One run answers it, and declining CCD now keeps the decision reversible in a way adopting it would not.</p>
</section>
<section id="the-cc0-form-libraries-are-already-staged" class="level4">
<h4 class="anchored" data-anchor-id="the-cc0-form-libraries-are-already-staged">The CC0 form libraries are already staged</h4>
<p>The proxy policy above asks for forms that are CC0 and untraced, and three projects already supply them, converted to OpenUSD rather than left in their upstream formats: <code>6-datasource/thebasemesh-stage</code> carries thebasemesh.com’s public-domain base meshes at real-world scale with UVs, and <code>kenney-stage</code> and <code>quaternius-stage</code> carry Kenney’s and Quaternius’ CC0 packs. A proxy form authored against those inherits CC0 and answers the provenance question in its <code>CITATION.cff</code> rather than by assertion.</p>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/weftspun\.github\.io\/request-for-discussion");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Serials are OID arcs under the 66606 PEN and are never reused.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/weftspun/request-for-discussion/edit/main/rfd/1121-layers-from-geometry-and-the-missing-categories/DETAILS.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/weftspun/request-for-discussion/blob/main/rfd/1121-layers-from-geometry-and-the-missing-categories/DETAILS.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/weftspun/request-for-discussion">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>